### ISSUE TITLE
simplify in tmap4

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#1003]
tmap3's `tm_shape()` has arguments like `simplify`, etc., but there are gone now. I was looking for any discussion about this (except https://github.com/r-tmap/tmap/issues/599), but cannot find it. Are there still plans to bring it back or not?

**Comment by mtennekes** [comment]
Good question. Not sure.... I don't think it is used that often. And it should require another dependency (`rmapshaper`), although we could list it under suggests. There is also `sf::st_simplify` that we could use, but as far as I remember I liked the mapshaper results better.

If we reinstate `simplify`, shouldn't we also have something that simplifies rasters (i.e. downsamples)? In other words, where does it end? Furthermore, the simplification functions will have some parameters, which are (in tmap3) passed on via `...`, so not really user friendly.

My preference would be to drop it, in the same way as we've dropped `convert2density`. We can easily provide users with code how to simplify shapes (directly from the source-function), so compat is not really an issue.

What is your opinion?

**Comment by Nowosad** [comment]
I also think that dropping this feature is fine. If needed, anyone can just use the rmapshaper beforehand.
