### ISSUE TITLE
Wrong zoom level of tm_tiles()

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#1004]
```r
library(tmap)
data("NLD_prov")

tmap_mode("view")
tm_basemap("CartoDB.PositronNoLabels") +
  tm_shape(NLD_prov, crs = 4236) +
  tm_borders() +
  tm_tiles("CartoDB.PositronOnlyLabels")
```

![image](https://github.com/user-attachments/assets/292a3ffb-0285-4fb4-8456-5c57d6f9a567)

**Comment by mtennekes** [comment]
The default value of `max.zoom.level` was totally off: 1. It should be somewhere around 18, but ideally provider-specific. See #880
