### ISSUE TITLE
Global options for setting fontface/fontfamily

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#1006]
Currently (correct me if I am wrong) it is possible to change fontface or fontfamily only for specified map element (e.g., title). However, in tmap3, there was also a great option to change all of fontfaces/fontfamilies at ones -- do you plan to bring it back?

``` r
library(tmap)
library(spData)

tm_shape(nz) +
  tm_polygons(fill = "Median_income", 
              fill.scale = tm_scale(midpoint = 28000)) +
  tm_title("New Zealand median income")
```

![](https://i.imgur.com/7rCbf9h.png)

``` r

tm_shape(nz) +
  tm_polygons(fill = "Median_income", 
              fill.scale = tm_scale(midpoint = 28000)) +
  tm_title("New Zealand median income") +
  tm_layout(fontface = "italic",
            fontfamily = "serif")
```

![](https://i.imgur.com/aggoDm1.png)

**Comment by mtennekes** [comment]
These options exist but are called `text.font...` in tmap4. DIdn't realise that they also exist in tmap3 under the name `font...`
