### ISSUE TITLE
Question - bivariate map

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#183]
@mtennekes do you plan to implement possibility to create bivariate maps (e.g. http://axismaps.github.io/thematic-cartography/articles/bivariate_choropleth.html)? Or maybe  could be done already?

**Comment by Robinlovelace** [comment]
Coincidentally @eugenividal and I discussed this last week. It can be done and I think the example below with 2 or 3 layers could be useful in some cases, it's just the legend that's tricky to create it seems: ``` r
library(tmap)
data("World")
names(World)
#>  [1] "iso_a3"       "name"         "sovereignt"   "continent"   
#>  [5] "subregion"    "area"         "pop_est"      "pop_est_dens"
#>  [9] "gdp_md_est"   "gdp_cap_est"  "economy"      "income_grp"  
#> [13] "life_exp"     "well_being"   "HPI"
m1 = tm_shape(World) + tm_fill("pop_est", alpha = 0.3, "Purples")
m2 = tm_shape(World) + tm_fill("HPI", alpha = 0.3, palette = "Blues")
m3 = tm_shape(World) + tm_fill("life_exp", alpha = 0.3, palette = "Oranges")
m1 + m2 + m3
```

![](https://i.imgur.com/QvBYJLm.png)

**Comment by mtennekes** [comment]
Wow, be careful there! The order of semi-transparent layers will influence the outcome colors. See for instance `m2 + m1 + m3`.

It would definitely be nice to support bivariate maps. Any ideas how to implement them?

**Comment by tim-salabim** [comment]
https://cran.r-project.org/web/packages/pals/vignettes/bivariate_choropleths.html as a starter?

**Comment by Robinlovelace** [comment]
Indeed - just a starter for 10. The legend in that **pals** package vignette looks awesome, thanks for sharing.

**Comment by tim-salabim** [comment]
more on how to create https://cran.r-project.org/web/packages/pals/vignettes/pals_examples.html at the very bottom

**Comment by Robinlovelace** [comment]
For context / interest - this is I think a 'trivariate' colourscheme generator: https://github.com/jschoeley/tricolore

**Comment by Nowosad** [comment]
@mtennekes this could be useful - https://github.com/Robinlovelace/geocompr/issues/376

**Comment by Nowosad** [comment]
Another (working, but not perfectly integrated with **tmap**) solution to create bivariate maps can be seen below. 
It was inspired by the work of  @sdesabbata (see https://github.com/sdesabbata/BivariateTMap).
@mtennekes can we think of integrating it into **tmap** somehow?

``` r
library(tmap)
library(sf)
library(stars)
library(spData)
library(classInt)
library(lattice)
library(grid)
library(pals)
legend_creator = function(col.regions, xlab, ylab, nbins){
  bilegend = levelplot(matrix(1:(nbins * nbins), nrow = nbins),
                       axes = FALSE, col.regions = col.regions,
                       xlab = xlab, ylab = ylab,
                       cuts = 8, colorkey = FALSE, scales = list(draw = 0))
  bilegend
}
add_new_var = function(x, var1, var2, nbins, style = "quantile"){
  class1 = suppressWarnings(findCols(classIntervals(c(x[[var1]]), 
                                                    n = nbins, 
                                                    style = style)))
  
  class2 = suppressWarnings(findCols(classIntervals(c(x[[var2]]), 
                                                    n = nbins, 
                                                    style = style)))
  
  x$new_class = class1 + nbins * (class2 - 1)
  return(x)
}
# vector example ----------------------------------------------------------
africa = subset(world, continent == "Africa")
africa = add_new_var(africa, 
                     var1 = "lifeExp", 
                     var2 = "gdpPercap", 
                     nbins = 3)

bilegend = legend_creator(stevens.pinkblue(n = 9), 
                          xlab = "lifeExp", 
                          ylab = "gdpPercap", 
                          nbins = 3)

bimap = tm_shape(africa) +
  tm_polygons("new_class", style = "cat", palette = stevens.pinkblue(n = 9)) +
  tm_layout(legend.show = FALSE)

grid.newpage()
print(bimap)
vp = viewport(x = 0.25, y = 0.25, width = 0.25, height = 0.25)
pushViewport(vp)
print(bilegend, newpage = FALSE)
```

![](https://i.imgur.com/thMDqCE.png)

``` r

# raster example ----------------------------------------------------------
data("land")
land = add_new_var(land, 
                   var1 = "trees", 
                   var2 = "elevation",
                   nbins = 3)

bilegend = legend_creator(stevens.pinkblue(n = 9),
                          xlab = "trees", 
                          ylab = "elevation",
                          nbins = 3)

bimap = tm_shape(land) +
  tm_raster("new_class", style = "cat", palette = stevens.pinkblue(n = 9)) +
  tm_layout(legend.show = FALSE)

grid.newpage()
print(bimap)
vp = viewport(x = 0.15, y = 0.45, width = 0.25, height = 0.25)
pushViewport(vp)
print(bilegend, newpage = FALSE)
```

![](https://i.imgur.com/VjVYbom.png)

<sup>Created on 2020-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aspina7** [comment]
Hi all, just thought would flag this [convo](https://github.com/slu-openGIS/biscale/issues/16) , it's not tmap but same principle should apply...

**Comment by Nowosad** [comment]
1. **User input** - my thinking is as following:
- One new argument (e.g., `is_bivariate`, `FALSE` by default). When this argument is `FALSE` then `tm_polygons(c("varA", "varB"))` creates two small multiples, and when this argument is `TRUE` then we have one bivariate map. 
- Every **tmap** color scale style for discrete maps (https://geocompr.github.io/post/2019/tmap-color-scales/) should work for bivariate maps (e.g, `"fisher"`, `"quantile"`, `"equal"`, etc.). It includes `"fixed"` style as well.
- When `is_bivariate` is `TRUE`, then only a subset of color palettes (see below) is possible.
- Probably, there are also some other things to consider, but that is all of what I can think of now...
2. **Color palettes** - The **pals** package and the blog post [""]() could be used as starting points. (I also think there is a lot more to explore in this topic) 
3. **Legend** - I would assume that a proper bivariate legend would have some x and y values on both axis.

**Comment by Nowosad** [comment]
1. **User input** - my thinking is as following:
- One new argument (e.g., `is_bivariate`, `FALSE` by default). When this argument is `FALSE` then `tm_polygons(c("varA", "varB"))` creates two small multiples, and when this argument is `TRUE` then we have one bivariate map. 
- Every **tmap** color scale style for discrete maps (https://geocompr.github.io/post/2019/tmap-color-scales/) should work for bivariate maps (e.g, `"fisher"`, `"quantile"`, `"equal"`, etc.). It includes `"fixed"` style as well.
- When `is_bivariate` is `TRUE`, then only a subset of color palettes (see below) is possible.
- Probably, there are also some other things to consider, but that is all of what I can think of now...
2. **Color palettes** - The **pals** package and the blog post ["How to choose a bivariate color palette?"](https://nowosad.github.io/post/cbc-bp2/) could be used as starting points. (I also think there is a lot more to explore in this topic) 
3. **Legend** - I would assume that a proper bivariate legend would have some x and y values on both axis.

**Comment by moquedace** [comment]
it is possible to save it via tmap_save()

**Comment by Nowosad** [comment]
> it is possible to save it via tmap_save()

Not yet.

**Comment by brettgabriel89** [comment]
is it possible to add a title to the bidirectional Africa map?

**Comment by mtennekes** [comment]
Will be in tmap v4 eventually

**Comment by Rapsodia86** [comment]
Has this been integrated with tmap? Or the [biscale?](https://chris-prener.github.io/biscale/articles/biscale.html) could be implemented?
I only see examples using shapefile as https://r-tmap.github.io/tmap/articles/basics_charts.html?q=biva#bivariate-charts

Thanks! 

> Another (working, but not perfectly integrated with **tmap**) solution to create bivariate maps can be seen below. It was inspired by the work of [@sdesabbata](https://github.com/sdesabbata) (see https://github.com/sdesabbata/BivariateTMap). [@mtennekes](https://github.com/mtennekes) can we think of integrating it into **tmap** somehow?
> 
> library(tmap)
> library(sf)
> library(stars)
> library(spData)
> library(classInt)
> library(lattice)
> library(grid)
> library(pals)
> legend_creator = function(col.regions, xlab, ylab, nbins){
>   bilegend = levelplot(matrix(1:(nbins * nbins), nrow = nbins),
>                        axes = FALSE, col.regions = col.regions,
>                        xlab = xlab, ylab = ylab,
>                        cuts = 8, colorkey = FALSE, scales = list(draw = 0))
>   bilegend
> }
> add_new_var = function(x, var1, var2, nbins, style = "quantile"){
>   class1 = suppressWarnings(findCols(classIntervals(c(x[[var1]]), 
>                                                     n = nbins, 
>                                                     style = style)))
>   
>   class2 = suppressWarnings(findCols(classIntervals(c(x[[var2]]), 
>                                                     n = nbins, 
>                                                     style = style)))
>   
>   x$new_class = class1 + nbins * (class2 - 1)
>   return(x)
> }
> # vector example ----------------------------------------------------------
> africa = subset(world, continent == "Africa")
> africa = add_new_var(africa, 
>                      var1 = "lifeExp", 
>                      var2 = "gdpPercap", 
>                      nbins = 3)
> 
> bilegend = legend_creator(stevens.pinkblue(n = 9), 
>                           xlab = "lifeExp", 
>                           ylab = "gdpPercap", 
>                           nbins = 3)
> 
> bimap = tm_shape(africa) +
>   tm_polygons("new_class", style = "cat", palette = stevens.pinkblue(n = 9)) +
>   tm_layout(legend.show = FALSE)
> 
> grid.newpage()
> print(bimap)
> vp = viewport(x = 0.25, y = 0.25, width = 0.25, height = 0.25)
> pushViewport(vp)
> print(bilegend, newpage = FALSE)
> 
> ![](https://camo.githubusercontent.com/1f1972784cf459ec3164a590190dba57a251308c5068c61f8044b36a432b0950/68747470733a2f2f692e696d6775722e636f6d2f6577397a4654682e706e67)
> 
> # raster example ----------------------------------------------------------
> data("land")
> land = add_new_var(land, 
>                    var1 = "trees", 
>                    var2 = "elevation",
>                    nbins = 3, 
>                    style = "equal")
> 
> bilegend = legend_creator(stevens.pinkblue(n = 9),
>                           xlab = "trees", 
>                           ylab = "elevation",
>                           nbins = 3)
> 
> bimap = tm_shape(land) +
>   tm_raster("new_class", style = "cat", palette = stevens.pinkblue(n = 9)) +
>   tm_layout(legend.show = FALSE)
> 
> grid.newpage()
> print(bimap)
> vp = viewport(x = 0.15, y = 0.45, width = 0.25, height = 0.25)
> pushViewport(vp)
> print(bilegend, newpage = FALSE)
> 
> ![](https://camo.githubusercontent.com/dbcf018ec71a0c953d4f5d2f9e3bdd8c865560764bb83849507275e0db9556a7/68747470733a2f2f692e696d6775722e636f6d2f6d57386b7750762e706e67)
> 
> Created on 2020-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)
