### ISSUE TITLE
Outside position of attributes (scale bar, compass) for facets

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#194]
@mtennekes - as a default `tm_raster()` plots the first raster in a raster stack. Is there a way to plot all of the rasters in a raster stack (for example in a similar fashion to `tm_facets()`)? If not, are you interested in implementing this option?

``` r
library(raster)
library(tmap)
fn = system.file("external/test.grd", package = "raster")
s = stack(fn, fn)

tm_shape(s) +
  tm_raster()
```

![](https://i.imgur.com/9NpEhwX.png)

Created on 2018-05-01 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mtennekes** [comment]
Good suggestion, done!

**Comment by Nowosad** [comment]
Awesome! Works as expected.

**Comment by gponce-ars** [comment]
Hi,

I'm using tmap 3.0 and trying to perform the same action discussed here,  visualization of stack with tmap.

I have a stack of annual rasters which resolution is 30m, extent (12,250 x 7,866 ) and datatype is FLT4S. The extent is pretty small, see below, just the SE corner in AZ, US (box).  

![image](https://user-images.githubusercontent.com/20215136/84710950-16844880-af1a-11ea-82b4-720d49b7a729.png)

The snippet below is running and doesn't seem that it is going to finish anytime soon(already ~ 3hrs)... Right now is using 1 core at full and memory just 183GB out of 850 GB and I already set rasterOptions to memory and chunk size to pretty high values. 

```
library(raster)
library(sf)
library(tmap)

# Both datasets are in EPSG:4326.
# Open shapfile
v_shp_allot<- st_make_valid(st_read('data/allot.shp'))
# Open multiband file and get just the last 6 years
r_spei_13_18 <- stack('data/spei_1987_2018.tif')[[27:32]]

# Map polygon over each raster facet (year)
map_spei <- tm_shape(v_shp_allot) + tm_polygons()
map_spei1 <- map_spei + 
  tm_shape(r_spei_13_18) + tm_raster(alpha = 0.7)

map_spei1

```
Any hint to "speed up" this process?

Thanks!

**Comment by gponce-ars** [comment]
Thanks, @Nowosad 
I'll try those ideas in that same order and report back.

**Comment by gponce-ars** [comment]
Hi @Nowosad @mtennekes 

I did try the tmap dev version and it works way faster than before.  I got my sf, stars, and sp updated, thanks @Nowosad.  
Since all the facets share same extent, is it possible to add a scale_bar and compass outside of the facets?  I tried but couldn't find an option to place them outside. 

```
r_stack <- stack('data/SPEI_S12_1987 2018.tif')
r_spei_13_18 <- r_stack[[27:32]]
names(r_spei_13_18) <- paste0("Yr_",2013:2018)
rb_spei_13_18 <- brick(r_spei_13_18)

figure1_map <- tm_shape(rb_spei_13_18,is.master = TRUE) +
               tm_raster (title = '',
                          legend.is.portrait = FALSE, 
                          legend.format = list(text.align='center'),
                          style="cont", midpoint = 0, n = 12,
                          palette =  scico::scico(12, palette = 'romaO') 
                        ) +
               tm_layout(main.title= 'SPEI\u2081\u2082\u2098 (2013-2018)', 
                         main.title.size = 1.5, 
                         main.title.position = 'center',  
                         inner.margins= c(0.0,0.0,0.0,0.0), 
                         outer.margins = c(0.05,0.05,0,0), 
                         legend.title.size = 0,
                         legend.text.size = 0.8,
                         legend.outside = TRUE,
                         legend.outside.position = 'bottom',
                         legend.outside.size = .08,
                         legend.just = c('center','top'),
                         legend.position = c('center','TOP'),
                         panel.labels = as.character(c(2013:2018)), 
                         panel.label.height=1.5, panel.label.size=1.5, 
                         frame = FALSE, frame.lwd = NA, panel.label.bg.color = NA,
                         design.mode=TRUE
                        ) +
                tm_grid(labels.inside.frame = FALSE, labels.size = 1,
                          col = "black", n.x = 4, n.y = 4, lines = FALSE,
                          labels.rot = c(0, 90)) + 
                tm_shape(v_az_allot) + 
                  tm_polygons(border.col = 'black', alpha=0, border.alpha = 0.5) +
                tm_shape(v_az_pima_ranches) +
                  tm_polygons(border.col = 'black', alpha=0, border.alpha = 0.5) +
                tm_facets(nrow=2)  +
                tm_xlab('Longitude', size = 2, space = 0.0) + 
                tm_ylab('Latitude', size = 2, space = 0.0) 
                #tm_compass(position=c('LEFT', 'bottom')) +
                #tm_scale_bar(position = c('RIGHT', 'bottom'), 
                #   breaks = c(0, 100, 200), 
                #   text.size = 1) 

figure1_map   
stars object downsampled to 1248 by 802 cells. See tm_shape manual (argument raster.downsample)
```
![image](https://user-images.githubusercontent.com/20215136/85507014-69a76c80-b5a6-11ea-8b9c-6391b547cc46.png)

Is it possible to add a scale bar and compass in this way?  I tried in the code above (commented)  but that displays on each facet. 

![image](https://user-images.githubusercontent.com/20215136/85508145-56959c00-b5a8-11ea-9351-cf5dfea7c8e4.png)

**Comment by mtennekes** [comment]
Unfortunately, that is not possible yet, and not easy to implement. However, it would be useful, so I'll keep it in mind.

**Comment by zwang31** [comment]
Just wondering if we can use tmap now to add a scale_bar and compass outside of the facets? I also need this in my multi-faceted map. Thank you!

**Comment by mtennekes** [comment]
That will be possible in tmap4
