### ISSUE TITLE
time slider support

### ISSUE THREAD

**Issue by ffinger** [r-tmap/tmap#195]
It would be great if tmap could support time sliders in the "view" mode, to be able to plot spatio-temporal data. This could be achieved via this leaflet plugin: [https://github.com/socib/Leaflet.TimeDimension](https://github.com/socib/Leaflet.TimeDimension).

**Comment by mtennekes** [comment]
Would be awesome! Did you already found an R wrapper around this plugin?

The straightforward way to implement this in tmap, is by using facets, and let these facets be shown as frames. This would take some effort, so it will probably not be included in the next update.

**Comment by ffinger** [comment]
No, I haven't found any R wrapper, haven't searched neither. 

On May 18, 2018 4:50:14 PM GMT+01:00, mtennekes <notifications@github.com> wrote:
>Would be awesome! Did you already found an R wrapper around this
>plugin?
>
>The straightforward way to implement this in tmap, is by using facets,
>and let these facets be shown as frames. This would take some effort,
>so it will probably not be included in the next update.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mtennekes/tmap/issues/195#issuecomment-390250346

-- 
Sent from my Fairphone. Please excuse my brevity.

**Comment by jebyrnes** [comment]
@mtennekes do you have a reprex of that - it's still the missing feature, IMHO....

**Comment by mtennekes** [comment]
Cleaning up all issues that are not relevant for the first release of tmap v4.
