### ISSUE TITLE
palette alpha doesn't get passed to tm_fill?

### ISSUE THREAD

**Issue by dana-rg** [r-tmap/tmap#241]
Thanks for this package, I've found it really useful for easily generating nice static maps.

One thing I'm wondering - is is possible to set the transparency of part of the color palette in tm_fill (rather than setting alpha for the entire layer)? I'm not sure if this is a limitation of the package, or if I'm going about it the wrong way.

I'm trying to make a bivariate chloropleth map using a continuous palette.  I'd like to use pure colors (e.g. pure red and pure blue scales) so that there is no ambiguity about the meaning of each color shown and so that the low end of the scale does not have any color. So I'm creating my own palette. Then I'm adjusting the top layer's transparency (similar to what is discussed in #183 ). But I don't like having white at the low end of my color scale on the top layer, since it mutes the colors below (which compromises the accuracy of the how the bottom layer is shown since the low end of the bottom scale is also white.)

I'd prefer if the palette on the top layer was totally transparent at the low end of the scale. So I'm trying to set the alpha value in the palette input colors, but the map produced doesn't reflect those alpha values.

This is an example of what I want to do: both layers have palettes that are 100% transparent at the low end, while the high end of the top layer scale is 50% transparent:

```
# R 3.5.0
# tmap 2.0
# R Studio 1.1.453

library(tmap)
tmap_mode("plot")
data(NLD_prov)

MypalBlue <- c(rgb(0,0,1,0), rgb(0,0,1,1)) # bottom layer: from clear to blue
MypalRed <- c(rgb(1,0,0,0), rgb(1,0,0,0.5)) # top layer: from clear to 50% transparent red

tm_shape(NLD_prov) +
  tm_fill(col = "pop_men", palette = MypalBlue, style = "cont") +
tm_shape(NLD_prov) +
  tm_fill(col = "pop_women", palette = MypalRed, style = "cont") 
```
But it doesn't work - the transparency value in my palette doesn't show up on my map (doesn't work for both the plot and view modes).  The whole map just looks red - MypalRed shows up as alpha = 1 at the low and high ends of the scale, the equivalent of MypalRed <- c(rgb(1,0,0,1), rgb(1,0,0,1)). So here's my current workaround - both palettes are white at the low end, with a 50% transparency for the entire top layer.
```
MypalBlue <- c(rgb(1,1,1), rgb(0,0,1)) # bottom layer: white to blue
MypalRed <- c(rgb(1,1,1), rgb(1,0,0)) # top layer: white to red

tm_shape(NLD_prov) +
  tm_fill(col = "pop_men", palette = MypalBlue, style = "cont") +  
tm_shape(NLD_prov) +
  tm_fill(col = "pop_women", palette = MypalRed, style = "cont", alpha = 0.5)
```
The issue with this is that the low end of the scale is white. For the top layer this mutes the colors below which makes the blue values seem lower than they are. 

If there isn't a way to pass an alpha value to tm_fill, maybe I just wait for #183  (which might be better than what I'm trying to do since I won't have to limit how dark the red gets so I can make maps with more contrast.) Or perhaps I will categorize my data into quantiles and manually assign colors to each combination of quantiles. 

It might also be useful to have transparency at one end of the scale for other applications too (e.g. overlaying data on imagery.)

**Comment by mtennekes** [comment]
Thanks for your question. Currently, it seems that the alpha channel of the colors is ignored and managed by `alpha`. Even `qtm(NLD_prov, rgb(1,0,0,.5))` returns a red instead of a pink map. It think it could be implemented to extract and use the alpha values from the color values.

**Comment by DOSull** [comment]
I've been using tmap in teaching lately and really enjoying it - as have my students (for the most part!)

Is there any prospect of the alpha values in colour palettes being handled in future? It would be nice to be able to consider value-by-alpha mapping using tmap

**Comment by Farewe** [comment]
Hello, I second this as I think it would be a very useful improvement.

**Comment by mtennekes** [comment]
Should be working in tmap v4
