### ISSUE TITLE
future of tmap histogram?

### ISSUE THREAD

**Issue by dylanbeaudette** [r-tmap/tmap#251]
Is it possible to suppress the legend and keep the histogram? I have tried a number of arguments to both `tm_legend` and `tm_smymbols` without success. Using `tmap` 2.0.

**Comment by mtennekes** [comment]
No, unfortunately not.

Actually, I haven't paid any attention to the histogram in tmap 2.0.

I'm thinking about replacing the histogram by an empty viewport in which the user can create custom charts with tmap data, e.g. with `ggplot2`. The advantage is that the tmap histograms does not have to be maintained anymore, and `ggplot2` is obviously much more flexible.

The user interface could be something like:

```
myCustomChart <- function(data) {
  # data is a data.frame with the columns id and col
   require(ggplot2
   ggplot(data) + ...
}

tm_shape(mySF) +
tm_polygons(col = "var1", id = "name", chart = myCustomChart)
```

**Comment by dylanbeaudette** [comment]
Shucks--I really like the histogram. Having the histogram is really important when the color/data mappings deviates from a simple linear relationship.

**Comment by cpreeldumas** [comment]
Any updates on this thread? Having troubling adding a legend histogram in "view" mode. Is `legend.hist` not supported in `tmap_mode("view")`?

**Comment by tylerhoecker** [comment]
I like this idea (of allowing flexibility for a custom plot in a viewport), however, would there be a simple way to determine the color breaks that are used in the map so the same breaks could be used in the ggplot? I'm not sure how to access those breaks, which are calculated 'under the hood' by tmap.

**Comment by Nowosad** [comment]
Hi @tylerhoecker - I am not sure if this is the best approach, but you can try something like this:

``` r
library(tmap)
library(classInt)
library(ggplot2)
library(spData)
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.2.1

tm_shape(world) +
  tm_polygons(col = "lifeExp", style = "fisher", legend.hist = TRUE) 
```

![](https://i.imgur.com/QJR5JqP.png)

``` r

breaks = classIntervals(world$lifeExp, n = 5, style = "fisher")
#> Warning in classIntervals(world$lifeExp, n = 5, style = "fisher"): var has
#> missing values, omitted in finding classes
world$lifeExp_breaks = cut(world$lifeExp, breaks$brks, include.lowest = TRUE)

ggplot(world, aes(x = lifeExp, fill = lifeExp_breaks)) +
  geom_histogram() +
  scale_fill_brewer(palette = "YlOrBr")
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 10 rows containing non-finite values (stat_bin).
```

![](https://i.imgur.com/SnDSs8w.png)

<sup>Created on 2021-11-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mtennekes** [comment]
Remark: the colors of a sequential/diverging ColorBrewer palette also depend on n: only when n is large (>=9) the extremes of the color palette are used. The default setting of this `contrast` argument is implemented in `tmaptools:::default_contrast_seq` and `tmaptools:::default_contrast_div`.

The colors can be obtained for a specific `n` with `tmaptools::get_brewer_pal`:

```r
``` r
library(tmap)
#> Registered S3 methods overwritten by 'stars':
#>   method             from
#>   st_bbox.SpatExtent sf  
#>   st_bbox.SpatRaster sf  
#>   st_bbox.SpatVector sf  
#>   st_crs.SpatRaster  sf  
#>   st_crs.SpatVector  sf

# get default palette names
pals = tmap_options("aes.palette")

# get colors
tmaptools::get_brewer_pal("YlOrBr", n= 3)
```

![](https://i.imgur.com/TExjgEO.png)

``` r
tmaptools::get_brewer_pal("YlOrBr", n= 5)
```

![](https://i.imgur.com/ONYS6EB.png)

``` r
tmaptools::get_brewer_pal("YlOrBr", n= 7)
```

![](https://i.imgur.com/OSblLh6.png)

``` r
tmaptools::get_brewer_pal("YlOrBr", n= 9)
```

![](https://i.imgur.com/9JyV1X0.png)

``` r
tmaptools::get_brewer_pal("YlOrBr", n= 16)
```

![](https://i.imgur.com/ALfyKcL.png)

<sup>Created on 2021-11-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
```

**Comment by moquedace** [comment]
Any updates regarding histograms? While navigating through the topics, I noticed some tests, especially related to `tm_polygons()`. Is there any implementation in `tmap v4` for `tm_raster()`?"

**Comment by mtennekes** [comment]
No updates. However, when the tests work for `tm_polygons`, they will also work for any other layer (only have to add chart arguments, which will be 5 minutes work).

**Comment by mtennekes** [comment]
Made some minor improvements, and now `tm_raster` works:

tm_shape(land) +
	tm_raster("trees",
			  col.chart = tm_chart_histogram())

Feel free to test @moquedace. It is the `charts` branch. Note that so far only `tm_scale_intervals` works with charts.

**Comment by moquedace** [comment]
I couldn't make it work. Does it work together with any other package? I can't find the `tm_chart_histogram()` function

**Comment by moquedace** [comment]
I couldn't make it work. Would installing the branch be that? `devtools::install_github("r-tmap/tmap", ref = "charts")`

**Comment by mtennekes** [comment]
I think so, yes. That branch is still unstable, but in a week or two, I will finish it and merge that branch into master. (Including a fix for https://github.com/r-tmap/tmap/issues/809)

**Comment by moquedace** [comment]
I understood  @mtennekes . `tm_chart_histogram()` didn't work here. I'll wait for it to finish. Thank you very much for the quick responses.

**Comment by mtennekes** [comment]
Implementation done #842, looking for reviewers (@moquedace)
