### ISSUE TITLE
Naming facets using tm_raster

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#273]
Hi @mtennekes ,
vector facets have labels as default. Is it possible to add facet lables to raster facets?

``` r
library(raster)
#> Loading required package: sp
library(tmap)
library(spData)
fn = system.file("external/test.grd", package = "raster")
s = stack(fn, fn)

# polygons - there are facets names ---------------------------------------
tm_shape(seine) +
  tm_lines() +
  tm_facets(by = "name")
```

![](https://i.imgur.com/psvV1cr.png)

``` r


# rasters does not have facets names --------------------------------------
tm_shape(s) +
  tm_raster() +
  tm_facets(free.scales = FALSE)
```

![](https://i.imgur.com/ta91Gk9.png)

<sup>Created on 2019-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mtennekes** [comment]
Good point.

The initial idea behind this, is that when `free.scales = TRUE`, all the facets are assumed to show one variable (since it has one scale).

I can see applications in which you need one scale for multiple variables. For instance, some different indicators that are scaled from 0 to 100. However, we will have to think about the scale title. Since the scale titles are used as facet titles in your suggestion, we also need a title for the scale.

**Comment by mtennekes** [comment]
From a conceptual point of view, it is not just `tm_raster` that would be affected by a change in behaviour. Consider these examples:

``` r
library(tmap)
data(World)
## different scales
tm_shape(World) +
    tm_polygons(c("well_being", "footprint"))
```

![](https://i.imgur.com/cOmvdxR.png)

``` r

# alternative using panel titles:
tm_shape(World) +
    tm_polygons(c("well_being", "footprint"), title = "") +
    tm_layout(panel.labels = c("well_being", "footprint"))
```

![](https://i.imgur.com/uNvtvRo.png)

``` r

## same scale
tm_shape(World) +
    tm_polygons(c("well_being", "footprint")) +
    tm_facets(free.scales = FALSE)
```

![](https://i.imgur.com/xPGOtW2.png)

``` r

# alternative using panel titles:
tm_shape(World) +
    tm_polygons(c("well_being", "footprint"), title = "") +
    tm_facets(free.scales = FALSE) +
    tm_layout(panel.labels = c("well_being", "footprint"))
```

![](https://i.imgur.com/0UjgTvY.png)

<sup>Created on 2019-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

We could use panel titles in all cases, or just when `free.scales = FALSE`. Not sure which is the better option.

@Nowosad What do you think?

**Comment by Nowosad** [comment]
I think the option when `free.scales = FALSE` is better. It seems less disruptive.

**Comment by mtennekes** [comment]
Cleaning up all issues that are not relevant for the first release of tmap v4.
