### ISSUE TITLE
tmap in view mode  display blank in Jupyter, which leaflet R behave normal

### ISSUE THREAD

**Issue by liweiwp** [r-tmap/tmap#288]
I think this may be a bug, I using Jupyter notebook with IRkernel, when output view mode map, the nodebook display nothing.

**Comment by Nowosad** [comment]
@liweiwp can you add a reproducible example?

**Comment by liweiwp** [comment]
![image](https://user-images.githubusercontent.com/1190394/54071905-48861400-42ae-11e9-933b-e31b33a405b0.png)

Can you try this in Jupyter using tmap? I try several times, still cannot get that work.

**Comment by mtennekes** [comment]
Don't know yet. I tried, but even your leaflet code chunk didn't work for me.
You could try this:

```r
x <- tmap_leaflet(qtm(World))
print(x)
```

**Comment by Nowosad** [comment]
Please reopen the issue if the problem still occurs.

**Comment by mherranz** [comment]
> Don't know yet. I tried, but even your leaflet code chunk didn't work for me.
> You could try this:
> 
> ```r
> x <- tmap_leaflet(qtm(World))
> print(x)
> ```

@mtennekes, it does not solve the problem (i.e. displaying as blank as in the other examples). @liweiwp's example still does not work. This issue should not be closed

**Comment by darribas** [comment]
+1 I run into this issue as well. I'm trying to get it to work for the [`gds_env`](https://github.com/darribas/gds_env), it'd be super cool to have that working!

**Comment by michaelgrund** [comment]
Could depend on your used browser, if I run my notebook in Firefox the cell executes successfully without warnings etc., however the interactive map does not appear. If I run it in Chrome everything works and the leaflet map appears.

**Comment by darribas** [comment]
Just a quick note that:

```R
library(tmap)
data("World")
x <- tmap_leaflet(qtm(World))
x
```
works as expected on the [`gds_env`](https://darribas.org/gds_env) in JupyterLab and correctly renders an interactive map. This works in Chrome and Firefox now, and it's amazing!
