### ISSUE TITLE
Why grobs on a leaflet map are missing in the automatically saved html file but are printed fine in the Rstudio browser?

### ISSUE THREAD

**Issue by MyrsiniKat** [r-tmap/tmap#304]
Could you please read my question on stackoverflow
https://stackoverflow.com/questions/56170683/why-grobs-on-a-leaflet-map-are-missing-in-the-saved-html-file-but-are-printed-fi ?
I haven't had an answer yet and I thought to contact you. Thank you very much in advance.

**Comment by mtennekes** [comment]
Strange bug.

Run via R console / RStudio Viewer: working
Run via R console / RStudio show in browser: working
Run via markdown / Rstudio Viewer: working
Run via markdown / Rstudio open in browser: **not working**
Save map with `tmap_save(map, file = "map.html")` and open html in browser: working.

The icons are temporarily saved as pngs in the R tmp directory. The strange thing is that the leaflet output will include the icon data hard-coded into the widget code. This also holds for the markdown document viewed in the browser. You can see this with the browser inspector:

![Screenshot from 2019-05-23 16-13-07](https://user-images.githubusercontent.com/2444081/58260138-33316980-7d76-11e9-8135-52a165cdbfe1.png)

So, the icon images are there, but somehow not shown.

@Nowosad @tim-salabim : any ideas?

**Comment by tim-salabim** [comment]
It seems that for whatever reason, in the rmarkdown the z-index of the grobs is set to lower values than is the case when rendering normally (i.e. via console). I don't know whether that is the actual issue, just something I noticed when trying to reproduce.

leaflet now lets you create your own panes via `addMapPane` that allows to set the z-index for the pane. Maybe you can somehow make sure that the grobs are rendered in a pane that is above the polygon pane?

**Comment by mtennekes** [comment]
What z-indices do you read then?

The icons are already placed in a custom map pane, which is on top (in this case called "overlay03"). The z-index for this pane is set to 403. tmap doesn't set the z-indices for the icons individually. I read 367, 248, 206, and 91. The strange this is that even if I manually delete all the other panes in inspector tool, the icons still don't show up, whereas with a mouse hover, the icon data is there (see screenshot above).

**Comment by tim-salabim** [comment]
I read the same as you when rendered via markdown. When rendered via console (and the icons show) I read 596, 477, 435, 320. Honestly, I have no idea what's going on here. Maybe @schloerke can shed some light?

**Comment by mtennekes** [comment]
I managed to create a minimal example using just leaflet:

```rmd

knitr::opts_chunk$set(echo = FALSE)

```{r}
library(leaflet)
data(breweries91)
leaflet() %>% 
  addTiles() %>% 
  addMapPane("overlay03", zIndex = 403) %>% 
  addMarkers(data = breweries91,
    icon = list(
    iconUrl =  'http://icons.iconarchive.com/icons/artua/star-wars/128/Master-Joda-icon.png',
    iconSize = c(75, 75)), 
    options = markerOptions(pane="overlay03"))
```

**Comment by mtennekes** [comment]
Cleaning up all issues that are not relevant for the first release of tmap v4.
