### ISSUE TITLE
text left or right of scale bar

### ISSUE THREAD

**Issue by rnuske** [r-tmap/tmap#326]
Trying to recreate maps with `tmap` I could not find a way to put the text ("100 m") left or right of a one piece scale bar instead of underneath the scale bar.

`ggspatial::annotation_scale()` seems to do that but has no way to ask for a one piece scale bar of user controlled length in map units.

Is there a way to put the length of the scale bar left or right of the bar?

**Comment by mtennekes** [comment]
Not really, other than reprogramming the scale bar. Honestly, this has a very low priority.

**Comment by rnuske** [comment]
It's a pitty. It's the only thing stopping me right now from fully going tmap. 

Just in case i somehow find time and start fiddeling with the scale, would you be open to adding someting like text_position?

**Comment by mtennekes** [comment]
Sure, feel free to do a pull request. The code that produces the scale bar is here: https://github.com/mtennekes/tmap/blob/master/R/meta_plot_items.R#L572-L632

**Comment by mtennekes** [comment]
Cleaning up all issues that are not relevant for the first release of tmap v4.
