### ISSUE TITLE
Allow a vector of two values for legend.outside.position

### ISSUE THREAD

**Issue by bjoernbos** [r-tmap/tmap#350]
I am trying to position a centered legend under a map. However, I only have one option available to put it underneath the map. But if I place it within the graph, I would have two options available (bottom and center).

Are there plans to make both options available for legends outside a map?
```
library(tmap)
data("World")

tm_shape(World) +
  tm_polygons("HPI",
              style = "cont",
              legend.is.portrait = FALSE) +
  tm_layout(legend.position = c("center", "bottom")) # Two options available
```
<img width="488" alt="grafik" src="https://user-images.githubusercontent.com/32138245/65342070-39bfd880-dbd2-11e9-904a-c3e8ab3adb58.png">

```
tm_shape(World) +
  tm_polygons("HPI",
              style = "cont",
              legend.is.portrait = FALSE) +
  tm_layout(legend.outside = TRUE,
            legend.outside.position = "bottom") # Only one option available
```
<img width="490" alt="grafik" src="https://user-images.githubusercontent.com/32138245/65342090-493f2180-dbd2-11e9-858b-cf29b1149e34.png">

**Comment by mtennekes** [comment]
Thx for the suggestion.

You can apply this little hack:

```r
tm_shape(World) +
    tm_polygons("HPI", style = "cont", legend.is.portrait = FALSE) +
    tm_layout(legend.position = c("center", -.3),
              outer.margins = c(.2, .05, .05, .05))
```

**Comment by mtennekes** [comment]
Possible in tmap v4
