### ISSUE TITLE
Custom pane names?

### ISSUE THREAD

**Issue by johnbaums** [r-tmap/tmap#359]
It doesn't seem to be possible to modify the pane name associated with added layers, meaning that if, e.g., `leafem::addImageQuery` is added, the layer name appears as, e.g., `tmap401`.

![image](https://user-images.githubusercontent.com/818438/67355315-b57ebd80-f5a2-11e9-904e-60f4e142cfe4.png)

I guess something like this will work, but it would be lovely to be able to pass a preferred name to `tm_raster` (etc.). Currently it seems only a numeric value can be passed via `zindex`, which will be prepended with `tmap`.

```R
library(tmap)
library(leafem)
data(land)

m <- (tm_shape(land) + 
    tm_raster('elevation', style='cont', palette='RdBu')) %>% 
  tmap_leaflet
i <- grep('addRasterImage', sapply(m$x$calls, '[[', 'method'))
j <- which(lengths(sapply(m$x$calls[[i]]$args, grep, pattern='^tmap')) > 0)
m$x$calls[[i]]$args[[j]] <- 'elevation'
m %>% 
  leafem::addImageQuery(land$elevation, project=TRUE, layerId='elevation', 
                        digits=0, prefix='')
```

![image](https://user-images.githubusercontent.com/818438/67355354-d0513200-f5a2-11e9-877c-d5facd8ff736.png)

**Comment by mtennekes** [comment]
How did you get the first map?

I tried 

```r
m <- (tm_shape(land) + 
	  	tm_raster('elevation', style='cont', palette='RdBu')) %>% 
	tmap_leaflet

m %>% leafem::addImageQuery()
```

which gives me `Error in inherits(x, "stars") : argument "x" is missing, with no default`

This runs without errors:

```r
m %>% 
	leafem::addImageQuery(land$elevation, project=TRUE, layerId='elevation', 
						  digits=0, prefix='')
```

but doesn't do anything...

**Comment by johnbaums** [comment]
Ah, yes... sorry I was vague. 

Achieving the first image required knowing the layer name, i.e. 

```R
m <- (tm_shape(land) + 
        tm_raster('elevation', style='cont', palette='RdBu')) %>% 
  tmap_leaflet %>% 
  leafem::addImageQuery(land$elevation, layerId='tmap401')
```

With leaflet, one can specify the layer name like this:

```R
library(leaflet)
leaflet() %>% 
  addProviderTiles("OpenStreetMap") %>% 
  leaflet::addRasterImage(land$elevation, layerId='foo') %>% 
  leafem::addImageQuery(land$elevation, layerId='foo')
```

**Comment by mtennekes** [comment]
Cleaning up all issues that are not relevant for the first release of tmap v4.
