### ISSUE TITLE
Continuous landscape legend width control needed

### ISSUE THREAD

**Issue by johnbaums** [r-tmap/tmap#365]
For a `'cont'` styled raster with custom breaks, label alignment is unexpected when using scientific notation with a fixed number of digits. This seems to be because the left-aligned string has leading white space. Is this intended, or was the intention for digits to just define the number of significant digits (in which case perhaps the white space should be stripped out)?

```R
library(raster)
library(tmap)

r <- raster::raster(matrix(runif(100, 0, 4.5), ncol=10))

tmap::tm_shape(r) + 
  tmap::tm_raster(style='cont', breaks=pretty(cellStats(r, range), n=7),
                  legend.is.portrait=FALSE,
                  legend.format=list(scientific=TRUE, digits=2)) +
  tmap::tm_layout(legend.outside=TRUE, 
                  legend.outside.position='bottom')
```
![image](https://user-images.githubusercontent.com/818438/67916906-64e31200-fbeb-11e9-82bd-21e46bb39b09.png)

### sessionInfo()
<details>
  <summary>Click me</summary>

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tmap_2.3-1   raster_3.0-7 sp_1.3-1    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         compiler_3.6.0     later_1.0.0        RColorBrewer_1.1-2 class_7.3-15       tools_3.6.0        digest_0.6.21     
 [8] packrat_0.5.0      lattice_0.20-38    viridisLite_0.3.0  rlang_0.4.0        shiny_1.4.0        DBI_1.0.0          crosstalk_1.0.0   
[15] rgdal_1.4-6        fastmap_1.0.1      e1071_1.7-2        htmlwidgets_1.5.1  rgeos_0.5-2        classInt_0.4-2     leaflet_2.0.2     
[22] grid_3.6.0         sf_0.8-0           R6_2.4.0           XML_3.98-1.20      magrittr_1.5       codetools_0.2-16   promises_1.1.0    
[29] tmaptools_2.0-2    leafsync_0.1.0     htmltools_0.4.0    units_0.6-5        dichromat_2.0-0    mime_0.7           xtable_1.8-4      
[36] httpuv_1.5.2       KernSmooth_2.23-15 lwgeom_0.1-7 
```
</details>

**Comment by tim-salabim** [comment]
Maybe:

```r
sprintf("%0.2f", c(6.11, 13.1, 100.222))
[1] "6.11"   "13.10"  "100.22"
`` 
?

**Comment by johnbaums** [comment]
If we're after 2 sig figs then maybe just wrap the `formatC` result in `sub('^\\s+', '', x)`? Bit hacky though..

**Comment by mtennekes** [comment]
@johnbaums do you need scientific notation? Your examples seems to work well with `scientific = FALSE`.

**Comment by Nowosad** [comment]
@johnbaums can we close this issue?

**Comment by johnbaums** [comment]
It's unresolved, so I guess only close if there's no intention to fix it.

Would `width=0` or `width=-1` be appropriate? 

From the docs: 

> width = 0 will use width = digits, width < 0 means left justify the number in this field (equivalent to flag = "-"). If necessary, the result will have more characters than width. For character data this is interpreted in characters (not bytes nor display width).

```r
formatC(c(6.11, 13.1), digits = 2, format = "fg", width = 0)
## [1] "6.1" "13" 

formatC(c(6.11, 13.1), digits = 2, format = "fg", width = -1)
## [1] "6.1" "13" 
```

**Comment by johnbaums** [comment]
> @johnbaums do you need scientific notation? Your examples seems to work well with `scientific = FALSE`.

Yes, that's quite a bit better but still quite crowded. 

```r
tmap::tm_shape(r) + 
  tmap::tm_raster(style='cont', breaks=pretty(cellStats(r, range), n=7),
                  legend.is.portrait=FALSE,
                  legend.format=list(scientific=FALSE)) +
  tmap::tm_layout(legend.outside=TRUE, 
                  legend.outside.position='bottom')
```

![file181ad2c76f292](https://user-images.githubusercontent.com/818438/80658588-d718ae80-8ac9-11ea-8155-cdfa64c2f377.png)

My understanding is that legend length is determined by the number of legend labels (breaks) - I think it would be great if this could be adjusted.

fwiw, when I posted this issue, I needed a legend at the bottom, but in general positioning a portrait legend to the right solves the problem.

**Comment by mtennekes** [comment]
Full flexibility of landscape legends in tmap v4
