### ISSUE TITLE
fig.align in rmarkdown modifies legend and layer display with tmap_leaflet()

### ISSUE THREAD

**Issue by gaelso** [r-tmap/tmap#398]
Maybe not important for most people but there is a weird interaction between rmarkdown chunk option fig.align='center' and tmap_leaflet().

instead of having the widget centered in the html page it makes the legend and layer items centered. Applies to knitr and bookdown html products.

full rmarkdown reprex:

        ---
        title: "tmap leaflet center legend"
        author: ""
        date: ""
        output: html_document
        ---
        
        blabla
        
        ```{r reprex-ok, echo=F, fig.cap="reprex widget elements ok", fig.align='center'}
        library(tmap)
        library(leaflet)
        
        data("World")
        
        tmap_mode("view")
        
        tm <- #tm_basemap(c("CartoDB.Positron", "Esri.WorldTerrain", "Esri.WorldImagery")) +
          tm_shape(World) +
            tm_polygons("HPI", group = "HPI", title = "") +
          tm_shape(World, name = "Eco") +
            tm_polygons("economy", group = "economy", title = "")
        
        tm 
        ```
        
        blabla
        
        ```{r reprex-center, echo=F, fig.cap="reprex widget elements centered", fig.align='center'}
        tm %>%
          tmap_leaflet() %>%
          leaflet::hideGroup("HPI") 
        ```

**Comment by mtennekes** [comment]
I've checked the generated html

![Screenshot from 2020-03-03 09-46-16](https://user-images.githubusercontent.com/2444081/75763281-eb436800-5d33-11ea-9226-c90efe923f4e.png)

Notice that the second figure is wrapped in an extra div container class figure with text-align=center. This property is passed on to the children html elements, including the text inside the legend. I don't know why `fig.align` is interpreted as `text.align`.

I also don't know why the first figure is not contained in a class=figure div.
