### ISSUE TITLE
Any replacement of smooth_map?

### ISSUE THREAD

**Issue by Si-Chong** [r-tmap/tmap#488]
Since smooth_map() is deprecated and no longer maintained, I wonder if there is any other function that can interpolate coordinates into a sort of density map easily and visualised via tmap?
Any tutorial or example is appreciated. Thanks!

**Comment by mtennekes** [comment]
That would be nice! If I would have twice as much time as I currently have, I would give it a go. 

Do you know of any such alternatives/initiatives within the R-spatial community @rsbivand @edzer @tim-salabim @Nowosad?

**Comment by tim-salabim** [comment]
Way way back I used package fields for that of thing (if I don't misinterpret `smooth_map()` for something it's not).

**Comment by rsbivand** [comment]
@Nowosad do you mean a density map of points (count of points per grid cell), or a gridded smooth of a variable observed at the irregular points?

**Comment by Nowosad** [comment]
@rsbivand I believe the question was for @Si-Chong. 

As a side note - the `smooth_map()` function should still exist in https://github.com/mtennekes/oldtmaptools/.
