### ISSUE TITLE
Suggestion: legend ticks

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#508]
``` r
library(tmap)
library(spData)

# pretty
tm_shape(world) +
  tm_polygons(col = "lifeExp", 
              style = "pretty",
              palette = "viridis")
#> Linking to GEOS 3.8.1, GDAL 3.0.4, PROJ 6.3.2
```

![](https://i.imgur.com/tH3DrLS.png)
@mtennekes have you ever considered adding legend ticks for continuous maps? Right not, it is hard to exactly know which color is connected to which value. (Some examples: https://i.stack.imgur.com/yyDx3.png and https://i.stack.imgur.com/pSXx0.png)

``` r

# cont 1
tm_shape(world) +
  tm_polygons(col = "lifeExp",
              style = "cont",
              palette = "viridis")
```

![](https://i.imgur.com/IJHA8Vy.png)

``` r

# cont 2
tm_shape(world) +
  tm_polygons(col = "lifeExp",
              style = "cont",
              palette = "viridis",
              legend.is.portrait = FALSE)
#> Legend labels were too wide. Therefore, legend.text.size has been set to 0.6. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
```

![](https://i.imgur.com/GyrlGmo.png)

<sup>Created on 2020-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hmandela** [comment]
How can i set legend ticks for continuous maps? I'm using tmap and I  have this difficulty

**Comment by Nowosad** [comment]
Available in the upcoming tmap v4:

``` r
library(tmap)
library(spData)

# cont 1
tm_shape(world) +
  tm_polygons(col = "lifeExp",
              style = "cont",
              palette = "viridis")
#> Deprecated tmap v3 code detected. Code translated to v4
#> Warning: Some legend items do not fit with the specified font size, and
#> therefore were rescaled.
```

![](https://i.imgur.com/EOxpoYx.png)

**Comment by zengyl1992** [comment]
Dear Nowosad, 
The legend ticks of tmap V4 work in tm_polygons function, but does not work in tm_raster( ) function.

tm_shape(land) +
  tm_raster("elevation", col.scale = tm_scale_continuous(values = terrain.colors(9))) +
  tm_shape(World) +
  tm_borders()
![ticks](https://user-images.githubusercontent.com/62234337/220251112-bf26b9d7-2a0b-4e11-b80a-9fa2957e9a2a.png)

**Comment by Nowosad** [comment]
Thanks for letting us know. I opened a new issue for this problem -- https://github.com/r-tmap/tmap/issues/702

**Comment by Nowosad** [comment]
@Yelong-Z I should work now.
