### ISSUE TITLE
allow legend for tm_borders

### ISSUE THREAD

**Issue by behrica** [r-tmap/tmap#51]
Currently the tm_borders does not forsee to have a legend.

In my map I draw a red border arround some polygons and I would be usefull to be able to add a legend, which says:

"---- area of xxxxx"   (where ---- would be a small red line)

**Comment by joelgombin** [comment]
Seconded!

**Comment by mtennekes** [comment]
We could do that: basically, `border.col` will then be upgraded to an aesthetic. There is one major downside: the common borders of neighboring polygons can have only one color. I guess in your application, you probably have selected some polygons, and draw them with a red border on top of the other polygons. In that case, we could also add to possibility to create manual legends as an alternative solution.

**Comment by pat-s** [comment]
pushing this again!

**Comment by mtennekes** [comment]
Is already in tmap v4
