### ISSUE TITLE
tm_fill() can take a color name or a column name, but tm_borders() can only take a color name.

### ISSUE THREAD

**Issue by cboettig** [r-tmap/tmap#515]
Consider this reprex:

```r
library(tmap)
data(World)

#  takes a column name:
tm_shape(World) +
  tm_polygons("HPI")

## Fill takes a column name:
tm_shape(World) +
  tm_fill("HPI")

## border does not:
tm_shape(World) +
  tm_borders("HPI")
## error!


## equivalent version in ggplot works fine with `col` or `fill`: 
ggplot(World) + geom_sf(aes(col=HPI))
```

Thanks for considering! Love `tmap`, students in my class just bumped against this issue trying to reproduce a famous plot.

**Comment by mtennekes** [comment]
Yes, great thing to add. This will be very easy to implement once the plans regarding version 4.0 have been implemented (see https://github.com/mtennekes/tmap/issues/495).

Until then consider this workaround:

``` r
library(tmap)
library(sf)
library(dplyr)

data(World)

World_borders = World %>% 
    mutate(geometry = st_cast(geometry, "MULTILINESTRING"))

tm_shape(World) +
    tm_fill("black") +
    tm_shape(World_borders) +
    tm_lines("HPI", lwd = 2) +
    tm_style("cobalt")
```

![](https://i.imgur.com/7hIaeyY.png)

<sup>Created on 2020-11-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cboettig** [comment]
awesome, thanks!

**Comment by mtennekes** [comment]
Already implemented in v4: see https://mtennekes.github.io/tmap4/index.html

**Comment by cboettig** [comment]
:tada: :tada: looks great! looking forward to the 4.0 release!
