### ISSUE TITLE
Using tmap for heatmaps

### ISSUE THREAD

**Issue by ccamara** [r-tmap/tmap#528]
I know there are several ways to create heatmaps, like `leaflet.extras`'s [`addHeatmap()`](https://bhaskarvk.github.io/leaflet.extras/reference/heatmap.html) for HTML maps or `ggmap` for printed maps (unfortunately, it requires google api key and is quite cumbersome, as it requires knowing bounding box beforehand). However, I was wondering if that is possible with `tmap`, as it makes it extremely easy to have both types of maps (interactive and printed) with the same code (+ I love how easy is to create maps).

I have searched in the issues  and vignettes but have not found any mention to it (and I was almost sure I had asked that same question before here! -sorry if I am repeating myself)

**Comment by Nowosad** [comment]
@ccamara you can create heatmaps (kernel density estimations) on your data first with **SpatialKDE**, and next plot it with **tmap**.
Learn more at https://jancaha.github.io/SpatialKDE/articles/SpatialKDE.html.
