### ISSUE TITLE
tmap_grob creates an empty plot

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#542]
`tmap_grob()` opens a new graphic device, which creates an empty plot (both in RStudio, but also in other sessions; see reprex below). It is a minor inconvenience, but hopefully it could be easily fixed.

``` r
library(tmap)
data(World)

tm1 = tm_shape(World) + tm_polygons("well_being", 
                                    title = "Well-being",
                                    palette = "RdYlGn")

tm1_grob = tmap_grob(tm1)
#> Note that the aspect ratio for which the grob has been generated is 1.4
```

![](https://i.imgur.com/WTF7PNu.png)

<sup>Created on 2021-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Yes, I am aware of it. I already found a way how to solve it, which will be applied in v4.
If it isn't too much effort I'll fix it in v3 as well, but it has low priority.

**Comment by FelipeCarrillo** [comment]
Is this the same issue as below ?:
```
tmap_mode("view")
qtm(World)
```
#The map gets displayed on my browser but an R empty device gets invoked as well.

**Comment by olivroy** [comment]
@mtennekes , another failure in Spatial Data Science with R was the absence of `tmap_grob()`, do you plan to add it back for tmap v4?

```r
pol_pres15$sps1 <- sps[,mr]
tm1 <- tm_shape(pol_pres15) +
          tm_fill("sps1", title = "Shortest path\ncount")
coords[mr] |> 
    st_distance(coords) |> 
    c() |> 
    (function(x) x/1000)() |> 
    units::set_units(NULL) -> pol_pres15$dist_52
library(ggplot2)
g1 <- ggplot(pol_pres15, aes(x = sps1, y = dist_52)) +
        geom_point() +
        xlab("Shortest path count") +
        ylab("km distance")
gridExtra::grid.arrange(tmap_grob(tm1), g1, nrow=1)
```


This is in Chapter 14 https://r-spatial.org/book/14-Areal.html#fig-shortestpath

**Comment by mtennekes** [comment]
`tmap_grob` was already added to tmap4. The first example is working, and I guess the second also? (@olivroy)

If not, please reopen this issue

**Comment by Nowosad** [comment]
@mtennekes -- the first example works, but still creates an empty plot

**Comment by mtennekes** [comment]
Could you check 

`tm1_grob = tmap_grob(tm1, vp = grid::viewport())`

?

That is a trick to bypass grid.newpage. If that works, we can make that the default.

**Comment by Nowosad** [comment]
In a fresh RStudio session, the code above creates an empty plot on a first run, but not on the following ones. You should be able to reproduce that with:

```
tm1_grob = tmap_grob(tm1, vp = grid::viewport())
plot(1)
tm1_grob = tmap_grob(tm1, vp = grid::viewport())
```

(It is still better than the current situation, in which an empty plot is created each time tmap_grob is used)
