### ISSUE TITLE
How to get greater control and consistency on legend.text.size

### ISSUE THREAD

**Issue by francisbarton** [r-tmap/tmap#572]
I would like to be able to specify a particular, consistent font size for legend text.
Currently, the legend on my map (using tm_symbols) — see screenshot below from a plotted map — has text labels with different font sizes, and there is a lot of available whitespace to the right of the text that could be used instead of condensing the label text size.

![image](https://user-images.githubusercontent.com/1819920/122385434-b842d900-cf64-11eb-952d-790975e8de21.png)

I currently have `legend.text.size = 1.2` and `legend.width = 0.6`. When I set `legend.width = 0.4`, with the intention of reducing the amount of whitespace, I get the message:

`Some legend labels were too wide. These labels have been resized to 0.66, 0.58, 0.61, 0.92. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.`

I find this resizing behaviour very unhelpful, especially when there is so much whitespace available that could be used.

How can I:
 * set a generic, larger text size that is the same for all legend text (the text on "Extra Care" in the screenshot is just about OK, the others are too small)?
 * force the legend text to use more of the width of the legend frame, so there is not so much wasted space, and so that `tmap` doesn't automatically resize the text smaller?

**Comment by francisbarton** [comment]
Hmm, when I use
`legend.title.size = 1.2, legend.text.size = 0.8` I get a much neater result when I use tmap_save to export to a PNG:
![image](https://user-images.githubusercontent.com/1819920/122399525-c992e200-cf72-11eb-8eb6-e8275bfd48d6.png)

but it's not quite as good in the plot itself:
![image](https://user-images.githubusercontent.com/1819920/122399787-065ed900-cf73-11eb-8565-194ecbbde08d.png)

**Comment by mtennekes** [comment]
Probably, the overall scale of your displayed map does not fit well. Please experiment with the `scale` option from `tm_layout` before tweaking the other layout options.

If that doesn't work, can you post a reproducible example?

**Comment by francisbarton** [comment]
I'll try to provide a reprex for this soon.

I don't understand the connection between the layout `scale` option and the size of the text in the legend - it would be helpful for me if you can explain why these two things are connected. I will experiment with `scale` nonetheless.

A further note on this that I have just discovered:
when using an outside legend, the legend text is still condensed automatically, but the info message is still displayed in the console output:

> Some legend labels were too wide. These labels have been resized to 0.75, 0.67, 0.70. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
Warning message:
In pre_process_gt(x, interactive = interactive, orig_crs = gm$shape.orig_crs) :
  legend.width controls the width of the legend within a map. Please use legend.outside.size to control the width of the outside legend

These messages are contradictory - when using an outside legend, `legend.width` does not apply, so it is irrelevant to display the suggestion about changing this to make the legend wider.

**Comment by mtennekes** [comment]
An reprex wound indeed be useful also for explanation.

Most of the questions you ask are irrelevant for the development of tmap: I'm currently working on legends for the next major version of tmap (v4). There will be greater flexibility regarding outside legend. On the other hand, it will also be a bit simpler and hopefully more user-friendly.

When a beta version is ready, I'll write a rmd file or open a gh issue and ask for feedback.
