### ISSUE TITLE
qtm() fails in interactive mode with data from zonebuilder

### ISSUE THREAD

**Issue by Robinlovelace** [r-tmap/tmap#577]
See reproducible example below. Can anyone else reproduce this error message? Seems that the geometries are valid, at least according to `sf::st_is_valid()`:

```r
# Error in build process:
# https://github.com/zonebuilders/zonebuilder/runs/3009599916#step:9:233

remotes::install_github("mtennekes/tmap")

library(zonebuilder)
library(tmap)
library(sf)
z = zb_zone(london_c(), london_a())
summary(sf::st_is_valid(z))
plot(z)
mapview::mapview(z) # works
qtm(z) # works
tmap_mode("view")
qtm(z)
```

It says:

```
# Error: Shape contains invalid polygons. Please fix it or set tmap_options(check.and.fix = TRUE) and rerun the plot
```

Will retry after following the instructions...

**Comment by Robinlovelace** [comment]
Interesting: manually fixing them with `sf::st_make_valid()` does not solve it but `check.and.fix` does.

Is that expected? Are there issues with the zonebuilder outputs in that case?

<details>

``` r
library(zonebuilder)
library(tmap)
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
z = zb_zone(london_c(), london_a())
summary(sf::st_is_valid(z))
#>    Mode    TRUE 
#> logical      74
plot(z)
#> Error in plot.sf(x[, cname], main = cname, pal = pal, nbreaks = nbreaks, : plotting list-columns not supported
mapview::mapview(z) # works
```

![](https://i.imgur.com/gh8rChP.png)

``` r
qtm(z) # works
tmap_mode("view")
#> tmap mode set to interactive viewing
qtm(z)
#> Error: Shape contains invalid polygons. Please fix it or set tmap_options(check.and.fix = TRUE) and rerun the plot
qtm(sf::st_make_valid(z))
#> Error: Shape contains invalid polygons. Please fix it or set tmap_options(check.and.fix = TRUE) and rerun the plot
tmap_options(check.and.fix = TRUE)
qtm(z)
#> Warning: The shape z is invalid (after reprojection). See sf::st_is_valid
```

![](https://i.imgur.com/3ZXMbtu.png)![](https://i.imgur.com/0l9oOgN.png)

<sup>Created on 2021-07-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Robinlovelace** [comment]
My guess: the cause is the fact that the input is in a projected (27700) CRS. Maybe we should change the CRS of the object in the package data. Interesting error in tmap in any case...

**Comment by temospena** [comment]
Hi
I think it has to do with sf changes: https://github.com/r-spatial/sf/issues/1649#issuecomment-860231045

try

```r
tmap_mode("view")
sf::sf_use_s2(FALSE)
qtm(z) #works!

```

**Comment by Robinlovelace** [comment]
Thanks Rosa. Confirmed, it works!

``` r
library(zonebuilder)
library(tmap)
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
z = zb_zone(london_c(), london_a())
summary(sf::st_is_valid(z))
#>    Mode    TRUE 
#> logical      74
# plot(z)
# mapview::mapview(z) # works
# qtm(z) # works
tmap_mode("view")
#> tmap mode set to interactive viewing
sf::sf_use_s2(use_s2 = FALSE)
#> Spherical geometry (s2) switched off
qtm(z)
```

![](https://i.imgur.com/WS73Kfm.png)

<sup>Created on 2021-07-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Any ideas of ways to reduce the changes of this issue affecting others?

**Comment by Robinlovelace** [comment]
More browsing suggests that this issue may be a duplicate of https://github.com/mtennekes/tmap/issues/571. Should have checked... Is there a way to set it temporarily? I guess something like this could work in the package function:

``` r
current_s2 = sf::sf_use_s2()
if(current_s2) {
  message("Temporarily setting sf::sf_use_s2(FALSE)")
  sf::sf_use_s2(FALSE)
  # run the operation
  sf::sf_use_s2(TRUE)
}
#> Temporarily setting sf::sf_use_s2(FALSE)
#> Spherical geometry (s2) switched off
#> Spherical geometry (s2) switched on
```

<sup>Created on 2021-07-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Robinlovelace** [comment]
Not sure if this is still an issue, happy to close if sorted.
