### ISSUE TITLE
Interactive Map not Working When Using tmap in RStudio

### ISSUE THREAD

**Issue by CianGraham** [r-tmap/tmap#598]
Hello everyone, 

I don't know what has caused this problem but I assume this is a bug? Basically, I cannot load interactive tmap in my rstudio suddenly today (it used to work perfectly). The code I used is:

`library(tmap)
data("World")
tmap_mode("view")
tm_shape(World) +
    tm_polygons("HPI")`

And you can find attached a screenshot of what is shown in my viewer:
<img width="322" alt="1631806095(1)" src="https://user-images.githubusercontent.com/67740217/133640663-54301850-8442-4187-b5ed-8d96c2d11d10.png">

I tried reinstall the package and this doesn't change the problem.

I am wondering if you have any hints for me to fix this? Thanks!

**Comment by mtennekes** [comment]
Could you try `mapview::mapview(World)` to see if it's `tmap` related?

**Comment by CianGraham** [comment]
> Could you try `mapview::mapview(World)` to see if it's `tmap` related?

Hi Martijn,

Unluckily this command still not working. It is still blank in the viewer of my RStudio and you can find attached image of a screenshot I had (don't know if there is any useful information for you actually):
<img width="968" alt="1631824451(1)" src="https://user-images.githubusercontent.com/67740217/133682065-8832a695-8cfa-47cd-9f52-51156c6503bb.png">

**Comment by CianGraham** [comment]
> Could you try `mapview::mapview(World)` to see if it's `tmap` related?

Also, when I used your code `mapview::mapview(World)`, in the viewer of RStudio a red "stop" button (the one you often see when R is processing a line of code) appears for less than one second and then it changed to those buttons in the screenshot. Hope this could help with the troubleshooting?

Thanks for your reply :)

**Comment by tim-salabim** [comment]
Hi @CianGraham could you please try to open the map in a browser by clicking the little button above the viewer pane and let us know if the map renders as expected in the browser?

**Comment by CianGraham** [comment]
> Hi @CianGraham could you please try to open the map in a browser by clicking the little button above the viewer pane and let us know if the map renders as expected in the browser?

Hi Tim, 

Did you mean the button after the "broom" (clear all viewer item)? If so, it did open my Chrome, but still, nothing there in the browser :(. I have attached the screenshot of my browser

<img width="960" alt="1631862173" src="https://user-images.githubusercontent.com/67740217/133739307-2e5572be-8d20-480b-971b-7cd4975befb6.png">

**Comment by tim-salabim** [comment]
Can you please also attach a screenshot of the browser console (press F12 or Ctrl+Shift+i)? We should see some error messages there...

**Comment by CianGraham** [comment]
> Can you please also attach a screenshot of the browser console (press F12 or Ctrl+Shift+i)? We should see some error messages there...

Hi Tim, here it is :) Thanks for your help in advance!

<img width="960" alt="1631862876" src="https://user-images.githubusercontent.com/67740217/133740725-27087a84-9930-486d-ae07-88151ab0c489.png">

**Comment by CianGraham** [comment]
> Can you please also attach a screenshot of the browser console (press F12 or Ctrl+Shift+i)? We should see some error messages there...

And here is the screenshot from other tabs :)

<img width="280" alt="1631862970(1)" src="https://user-images.githubusercontent.com/67740217/133740863-b1b4115b-cfe8-4433-afa5-9e66e231bf5f.png">

<img width="279" alt="1631862991(1)" src="https://user-images.githubusercontent.com/67740217/133740914-3ff163fb-4dc5-4613-bb75-79615db680ae.png">

<img width="278" alt="1631863008(1)" src="https://user-images.githubusercontent.com/67740217/133740952-451bc6a9-b1c0-4231-85bd-445b32985c3a.png">

**Comment by tim-salabim** [comment]
Ok, not very specific, but maybe updating both **leaflet** and **leaflet.providers** packages helps?

**Comment by CianGraham** [comment]
> Ok, not very specific, but maybe updating both **leaflet** and **leaflet.providers** packages helps?

Hello Tim, I have installed these two packages and still not working :( I will try re-install my RStudio and let you know if it works.

You can find below my code saying these two packages are loaded successfully.

```
> library(tmap)
> library(leaflet)
Warning message:
package ‘leaflet’ was built under R version 4.0.5 
> library(leaflet.providers)
Warning message:
package ‘leaflet.providers’ was built under R version 4.0.5 
> 
> 
> data("World") 
> 
> tmap_mode("view") 
tmap mode set to interactive viewing
> 
> tm_shape(World) + tm_polygons("HPI")
```

**Comment by mtennekes** [comment]
What R version are you using? It may be good to update R and all installed packages.

**Comment by CianGraham** [comment]
> What R version are you using? It may be good to update R and all installed packages.

Thanks! I used to use R 4.0.4 and I re-installed R to the latest version and it works now :) I will close this issue
