### ISSUE TITLE
Issue with `renderTmap()` when only using explicit namespacing

### ISSUE THREAD

**Issue by ColinFay** [r-tmap/tmap#601]
Hey y'all! 

Just stumbled upon this error while building an app that relies on `{tmap}`. 

```r
# Be sure to have a clean R session
.rs.restartR()

# Run the following code
library(shiny)
ui <- function(request){
  tmap::tmapOutput("raster", width = "50%") 
}

server <- function(
  input, 
  output, 
  session
){
  output$raster <- tmap::renderTmap({

  })
}

shinyApp(ui, server)

Listening on http://127.0.0.1:4975
Warning: Error in tmap_leaflet: could not find function "tmap_leaflet"
  [No stack trace available]
```

The issue here comes from the `tmap_leaflet` at:

```r
> tmap::renderTmap
function (expr, env = parent.frame(), quoted = FALSE) 
{
    if (!quoted) 
        expr = substitute(expr)
    expr = substitute(tmap_leaflet(expr, in.shiny = TRUE))
    htmlwidgets::shinyRenderWidget(expr, leafletOutput, env, 
        quoted = TRUE)
}
<bytecode: 0x7ff05ec50c38>
<environment: namespace:tmap>
```

This is solved if we use `getFromNamespace("tmap_leaflet", "tmap")`, which will always find the function. 

I pushed a fix at https://github.com/ColinFay/tmap/commit/430ade0f1e1eba9b0d2192912672039129711e54, let me know if you want me to PR this. 

Cheers, 
Colin

**Comment by mtennekes** [comment]
Thanks @ColinFay 

Two questions:

Is there a reason to run the shiny app without `library(tmap)`? 
Do you know if your solution is also good coding practice (e.g. according to the CRAN police)?

**Comment by ColinFay** [comment]
Hey @MatthieuStigler 

Whenever running a package, you're not doing `library`, so this has impact in two cases:
- When building an app with ˋ{golem}`, where the app is built as a package so you don't do any `library` call (this is actually how I became aware of this issue)
- In the case someone wants to build an extension over `renderTmap` 

When it comes to ˋgetFromNamespace`, this is the recommended way to avoid ˋ:::`. It's ok with the CRAN, we have it in `{golem}` for example
 https://github.com/ThinkR-open/golem/blob/master/R/create_golem.R#L50 

it's also in many others on CRAN https://github.com/tidyverse/ggplot2/blob/master/R/backports.R#L5

**Comment by mtennekes** [comment]
Thanks! Please make a PR

**Comment by mtennekes** [comment]
Hi @Shelmith-Kariuki, I just merged the PR from @ColinFay 

Could you please check if it works? If so, I will submit a version to CRAN.

**Comment by Shelmith-Kariuki** [comment]
I am so sorry for the delay @mtennekes . Yes, it works now.
