### ISSUE TITLE
Alignment lowercase / uppercase position

### ISSUE THREAD

**Issue by statnmap** [r-tmap/tmap#602]
I think I am missing something with lowercase/uppercase `position`.  
Documentation says it depends on margins, but this does not seem to be `inner.margins`.
I was hoping that the alignment accounted for `inner.margins`, as lowercase position is aligned with the map, and uppercase, aligned with the box.  
Instead, there is a small difference in position due to a type of margin it seems I can not control.

I can see the small difference between both the images below, but I do not get why it is not the last image that is true.  

```r
library(tmap)
data("World")

tm_shape(World) +
    tm_polygons("HPI") +
  tm_layout(
    inner.margins = c(0, 0.5, 0, 0.1),
    title = "My title",
    title.position = c("left", "TOP")
  )
```
![image](https://user-images.githubusercontent.com/21193866/134945354-9a52c7f1-3913-4ecb-b3f7-227a6ca7ca7d.png)

```r
tm_shape(World) +
    tm_polygons("HPI") +
  tm_layout(
    inner.margins = c(0, 0.5, 0, 0.1),
    title = "My title",
    title.position = c("LEFT", "TOP")
  )
```
![image](https://user-images.githubusercontent.com/21193866/134945506-7eb2dbbc-ab1c-40f7-8267-47fbf7a0102b.png)

What I expected: lowercase aligned with the map extent.
```r
library(tmap)
data("World")

tm_shape(World) +
    tm_polygons("HPI") +
  tm_layout(
    inner.margins = c(0, 0.5, 0, 0.1),
    title = "My title",
    title.position = c("left", "TOP")
  )
```
![000003](https://user-images.githubusercontent.com/21193866/134945833-93d6d6ce-4819-4918-937f-2c5400ca661a.png)

**Comment by mtennekes** [comment]
I think the difference between lower and upper case is a hard-coded margin, that has nothing to do with inner.margins.
I'm not planning to change this in v3, unless there is an easy-to-fix bug somewhere. 

What would you like to achieve?

I cannot see any difference between the first and the last code chunk.

**Comment by Nowosad** [comment]
@statnmap feel free to reopen the issue if needed
