### ISSUE TITLE
Plotting lines in different colours based upon categorical variables "Groups" and 

### ISSUE THREAD

**Issue by YoungPharoah** [r-tmap/tmap#604]
![image](https://user-images.githubusercontent.com/43537619/136583876-60c4437c-ddd6-4974-b3b3-9233dce39bb3.png)

Hi 

I have been trying to create a map using lines geometry and give each group a colour "Categorical variable", and it errors

 library(tmap)
 tmap_mode("view")
 tm_shape(dataformap) +
   tm_lines(col = "Scheme")

Error: Assigned data `NA` must be compatible with existing data.
i Error occurred for column `Scheme`.
x Can't convert <logical> to <character>.
Run `rlang::last_error()` to see where the error occurred.

**Comment by Robinlovelace** [comment]
Closing for now as there is no reprex. If you can create a reproducible example @YoungPharoah please share and we can reopen this.
