### ISSUE TITLE
Error: Fill argument neither colors nor valid variable name(s)

### ISSUE THREAD

**Issue by benegiocoli** [r-tmap/tmap#616]
Why do I get this error message when the variable is indeed part of the data I am using?

This is the code:

`tm_shape(gwr.map) + tm_fill('White_British', n = 5, style = 'quantile', title = 'Original distribution of x') +
        tm_borders(alpha = 0.8) + tm_layout(legend.text.size = 0.8, legend.title.size = 1.1)`

` tm_shape(gwr.map) + tm_fill('OA.Census.White_British', n = 5, style = 'quantile', title = 'GWR coefficient of x') +
        tm_borders(alpha = 0.8) + tm_layout(legend.text.size = 0.8, legend.title.size = 1.1)`

I only get the error message for the second map, even though if I run  `names(gwr.map)` I get that OA.Census.White_British is one of the variables.

**Comment by Robinlovelace** [comment]
Hi @benegiocoli can you provide a reproducible example? That will make the issue easier to debug, currently it's hard to see what is going on and, even if the issue were fixed, it would be impossible to test. For info on creating a good reprex see here: https://community.rstudio.com/t/faq-how-to-do-a-minimal-reproducible-example-reprex-for-beginners/23061
