### ISSUE TITLE
tm_polygons border.col defined by another data variable

### ISSUE THREAD

**Issue by jflowernet** [r-tmap/tmap#619]
I have the same issue as this Stackoverflow question:
https://stackoverflow.com/questions/67877029/tm-polygons-border-col-should-be-defined-by-another-variable-using-tmap-package

It doesn't seem like the border.col argument of tm_polygon can currently take a data variable so that polygon borders can be different colours based on that variable? If so, would this be possible as an enhancement one day?
Thanks

**Comment by Nowosad** [comment]
@jflowernet -- no, this feature does not exist (yet). You can find similar questions at https://github.com/r-tmap/tmap/issues/56 and https://github.com/r-tmap/tmap/issues/51, and a workaround at https://github.com/r-tmap/tmap/issues/515. It should be possible in tmap v4.

**Comment by jflowernet** [comment]
@Nowosad Apologies for not checking for previous similar questions,and many thanks for the link to the work around. tmap is amazing and looking forward to what tmap v4 brings!
