### ISSUE TITLE
Incompatibility with AMD Ryzen CPU?

### ISSUE THREAD

**Issue by rafaelricco** [r-tmap/tmap#620]
I don't find in any place any mention about this problem, I can install the tmap on my R with no problems, but when I call the library, this error pops:

`> library("tmap")
Error: package or namespace load failed for ‘tmap’:
 Function found when exporting methods from the namespace ‘raster’ which is not S4 generic: ‘all.equal’
In addition: Warning message:
no function found corresponding to methods exports from ‘raster’ for: ‘direction’, ‘gridDistance’`

I try in another notebook that uses Intel CPU, and it goes with no problem, but in both my desktops with AMD Ryzen CPUs I have this issue. 

Am I doing something wrong?

Thank you!

**Comment by Robinlovelace** [comment]
Looks to me like `raster` is not installed. This doesn't look like a bug in `tmap` to me.

**Comment by rafaelricco** [comment]
`raster` package is installed, but returns the same error when I call the library:

`> library("raster")
Carregando pacotes exigidos: sp
Error: package or namespace load failed for ‘raster’:
 Function found when exporting methods from the namespace ‘raster’ which is not S4 generic: ‘all.equal’
In addition: Warning message:
no function found corresponding to methods exports from ‘raster’ for: ‘direction’, ‘gridDistance’ `

And again, this only occurs in my two desktops with AMD CPU, the other ones with Intel CPUs works normal.

**Comment by rafaelricco** [comment]
Solved it, I have to install both packages from this repos:

`install.packages('terra', repos='https://rspatial.r-universe.dev')`
`'install.packages('raster', repos='https://rspatial.r-universe.dev')`

And then it goes normal in mine desktops!
