### ISSUE TITLE
Fresh install of tmap gives following error - package or namespace load failed for tmap. 

### ISSUE THREAD

**Issue by abhargava88** [r-tmap/tmap#621]
Full text of error: 

Error: package or namespace load failed for ‘tmap’:
 Function found when exporting methods from the namespace ‘raster’ which is not S4 generic: ‘all.equal’
In addition: Warning message:
no function found corresponding to methods exports from ‘raster’ for: ‘direction’, ‘gridDistance’ 

Installing via command install.packages('tmap') in R v 4.1.2

**Comment by Robinlovelace** [comment]
See https://github.com/r-tmap/tmap/issues/620
