### ISSUE TITLE
tm_symbols plots big points first regardless of intended data order

### ISSUE THREAD

**Issue by geotheory** [r-tmap/tmap#626]
Plot order of points - which [used to follow](https://stackoverflow.com/a/50360798/1156245) data.frame order - no longer does as far as I can see.

```
require(tmap)
require(dplyr)
require(sf)

d = data.frame(lon = rnorm(1e5, mean = -95.5, sd=4) |> pmin(179) |> pmax(-179),
               lat = rnorm(1e5, mean = 37.5, sd=4) |> pmin(89) |> pmax(-89)) |> 
  group_by(lat = round(lat), lon = round(lon)) |> 
  summarise(n = length(lat), .groups = 'drop') |> 
  arrange(n) |> 
  mutate(id = paste0('id.', as.character(1:n())))

p = d |> st_as_sf(coords = c('lon','lat'), crs = 'WGS84')

print(all(p$id == d$id)) # check order is preserved

tmap_mode("view")

tm_basemap("Stamen.TonerLite") +
  tm_shape(p) +
  tm_symbols(size="n", col = 'n', border.col = 'white', alpha=0.5,
             palette = c('orange','navy'), id = "id",
             legend.size.show = FALSE, scale=2, popup.vars = TRUE)
```

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1282581/152685846-9bc756e9-f6f6-4a58-bfa6-003e0be37c20.png">

The darker higher-value points are clearly not plotting on top.  Reversing the data order (`arrange(desc(n))`) produces the same result.

**Comment by mtennekes** [comment]
This is not possible with tmap3 unfortunately.

Fortunately, it is possible with tmap4:

```r
tm_basemap("Stamen.TonerLite") +
	tm_shape(p) +
	tm_symbols(size="n", fill = 'n', col = 'white', fill_alpha=0.5,
			   fill.scale = tm_scale(values = c('orange','navy')),
			   size.scale = tm_scale(values.scale = 2),
			   plot.order = tm_plot_order("DATA"))
```

![Screenshot from 2022-02-09 21-13-34](https://user-images.githubusercontent.com/2444081/153282579-4626df62-7ef0-4675-a623-bb5b296eee30.png)

The first alpha version of tmap4 will be available in a few weeks, but you can test this code with the v4 branch. "view" mode does not work, but basemaps are available in "plot" mode.

**Comment by geotheory** [comment]
Will v4 offer any improvement in popup/tooltip formatting controls by any chance? I've had to jump to leaflet because of this
