### ISSUE TITLE
Legend outside each small multiple

### ISSUE THREAD

**Issue by jflowernet** [r-tmap/tmap#631]
Hi,

Is it possible to get an individual legend outside each small multiple? The reprex below shows using `free.scales.fill=TRUE` gets a legend inside each small multiple, but adding `tm_layout(legend.outside=TRUE)` results in a single common legend outside, rather than the same legends as before outside each multiple. 

``` r
library(tmap)
data("World")

tm_shape(World) +
  tm_fill(col = "well_being") + 
  tm_facets(by = "continent", free.scales.fill = TRUE)
```

![](https://i.imgur.com/PXgwKRR.png)

``` r
tm_shape(World) +
  tm_fill(col = "well_being") + 
  tm_facets(by = "continent", free.scales.fill = TRUE) + 
  tm_layout(legend.outside = TRUE)
```

![](https://i.imgur.com/titxmgh.png)

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mtennekes** [comment]
tmap4 preview:

```r
tm_shape(World) +
	tm_fill("well_being", fill.free = TRUE) + 
	tm_facets_hstack(by = "continent")
```

![example](https://user-images.githubusercontent.com/2444081/156938372-a8f78970-da0d-4988-a808-ec2cafa4aa11.png)

(see tmap4 branch)

There will vignettes soon, but for now:

* Legends will by default be drawn outside the map.
* When the facets are arranged in a single row (like above) or a single column, the legends will be aligned with the plots.

**Comment by jflowernet** [comment]
Perfect! Many thanks for the response and the amazing package that is tmap. Looking forward to v4
