### ISSUE TITLE
Map output blank when projection is 0 and zoom level is set

### ISSUE THREAD

**Issue by Shelmith-Kariuki** [r-tmap/tmap#633]
Hi in relation to [this issue](https://github.com/r-tmap/tmap/issues/632)

The 'Equal Earth' projection is now visible on the interactive map (see map below)
![image](https://user-images.githubusercontent.com/37449624/156365031-f1d7814a-e18f-4172-984b-9f304c0dbf28.png)

But once I set the zoom level, the map disappears.
![image](https://user-images.githubusercontent.com/37449624/156364938-231ab0c1-0e73-42af-8e0f-5a821cd6a1d5.png)

Here is the piece of code that I am running.

```
library(tmap)
data("World")
tmap_mode("view")

plot_out <- tm_shape(World, projection = "+proj=eqearth") +
  tm_borders() +
  tm_fill("pop_est", id = "iso_a3",
          palette = "Blues",
          title = "") +
  tm_layout(title = "",
            legend.title.size = 1,
            legend.text.size = 0.6) +
  tm_basemap("") +
  tm_view(view.legend.position = c("left","bottom"),
          set.view = c(37.9083264, 0.1768696, 1.5), ## including this line results into a blank output
          projection = 0)

plot_out
```

Is it that the zoom level does not work when projection = 0?

**Comment by Shelmith-Kariuki** [comment]
Hi @mtennekes thank you for feedback. I really hope I can find a way to zoom in on different regions of the world. I will get back to you once I am successful.

**Comment by mtennekes** [comment]
You can @Shelmith-Kariuki  :-)

First, you need to what zoom levels eqearth uses, and which coordinates you are interested in.

Coordinates are shown here:

```r
tmap_mode("plot")
tm_shape(World, projection = "+proj=eqearth") +
	tm_borders() +
	tm_grid()
```

You can use the found coordinates for `set.view`. Suppose you want to zoom in on Northern Africa:

```
tmap_mode("view")
plot_out <- tm_shape(World, projection = "+proj=eqearth") +
	tm_borders() +
	tm_fill("pop_est", id = "iso_a3",
			palette = "Blues",
			title = "") +
	tm_layout(title = "",
			  legend.title.size = 1,
			  legend.text.size = 0.6) +
	tm_basemap("") +
	tm_mouse_coordinates() +
	tm_view(view.legend.position = c("left","bottom"),
			set.view = c(2.5e6, 2.5e6, -13),
			projection = 0)
```

**Comment by Shelmith-Kariuki** [comment]
@mtennekes It works well now ... (#happydance). Thank you so much for all your help.

**Comment by mtennekes** [comment]
You're welcome!
