### ISSUE TITLE
Place two legend items in different spots

### ISSUE THREAD

**Issue by DaphneBeau** [r-tmap/tmap#637]
I have a map with two layers that overlap ; one with rates and another with proportionnal symbols per region. Thus I have two legend items that I would like to place in different spots on my layout. 
I use tm_fill for the rates per polygons and tm_symbols for the propotionnal circles. To specify  the position of the circles I use tm_legend after tm_symbols. It overides the argument legend.position in tm_layout.
Is there a way to bypass this and have the two legend items in different spots?

**Comment by mtennekes** [comment]
This is not possible yet, but will be in the next major release (tmap v4). An alpha version will be released in a few weeks.
