### ISSUE TITLE
plot histogram for continuous variables with high variation in log scale

### ISSUE THREAD

**Issue by bniebuhr** [r-tmap/tmap#638]
Hi,

I am interested in plotting a continuous map in log10 color scale with the histogram of values. I started to follow the script from [this post](https://geocompr.github.io/post/2019/tmap-color-scales/). The histogram works fine for the "lifeExp" variable:

``` r
library(spData) # example datasets
library(tmap)   # map creation
library(sf)     # spatial data reprojection
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

world_moll = st_transform(world, crs = "+proj=moll")

tm_shape(world_moll) +
  tm_polygons(col = "lifeExp",
              legend.hist = TRUE) +
  tm_layout(legend.outside = TRUE) 
```
![](https://i.imgur.com/gaGutPg.png)

<sup>Created on 2022-03-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

However, if I use the "pop" variable, which has much higher variables, the histogram is empty:

``` r
tm_shape(world_moll) +
  tm_polygons(col = "pop",
              legend.hist = TRUE) +
  tm_layout(legend.outside = TRUE) 
```

![](https://i.imgur.com/dKqHwcj.png)

<sup>Created on 2022-03-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I was interested in further transforming a variable like the "pop" one into the continuous log10 scale (style = "log10"), and show the histogram also with the x axis in log10 scale. Something like:

```r
tm_shape(world_moll) +
  tm_polygons(col = "pop", style = "log10",
              legend.hist = TRUE) +
  tm_layout(legend.outside = TRUE) 
```

Is it possible? If not, that is a suggestion for further improvement.

**Comment by mtennekes** [comment]
Thx @bniebuhr 

The second histogram is as expected (by design). It is not empty, but appears so, because the height is dominated by the first bar. You can see this:

```r
tm_shape(world_moll) +
	tm_polygons(col = "pop",palette = "-Reds",
				legend.hist = TRUE) +
	tm_layout(legend.outside = TRUE) 
```
![image](https://user-images.githubusercontent.com/2444081/159085203-f7862706-2fb2-42f2-bb58-3325a5137f18.png)

The current implementation of the histogram is limited in many ways. Hopefully, I can (re)implement a more flexible histogram in tmap4.
