### ISSUE TITLE
How to define the upper legend limit with a continuous scale

### ISSUE THREAD

**Issue by bniebuhr** [r-tmap/tmap#639]
Hi

I am plotting a raster of a continuous variable (`style = "cont"`). The maximum value of the raster is 8, so the legend goes up to this value. However, I want to compare this map with others, and the conituous variable goes up to a higher value (20) in one of them. I want the color scale to be the same among maps, so I would like to set a maximum of 20 in all legends and collor palletes. Is there a way of doing this for continuous maps?

Here the code I used and the output plot.

```r
p_pub_cab_impact <- tm_shape(impact_pub) +
  tm_raster(style = "cont", title = "Impact", 
            palette = jcolors::jcolors("pal12"), midpoint = NA) +
  tm_shape(study_area_sf, name = "Study area") +
  tm_borders() +
  tm_layout(main.title = "Impact - Tourist cabins",
            legend.frame = T, 
            main.title.size = 0.6, legend.title.size = 0.6)
p_pub_cab_impact
```

![image](https://user-images.githubusercontent.com/8031905/159234367-47cc8fe0-77ac-4561-a2a5-82632ebe6613.png)

**Comment by Nowosad** [comment]
You can try to use `breaks`:

``` r
library(tmap)
data(World)

tm_shape(World) +
  tm_fill("life_exp", style = "cont", breaks = seq(0, 100, by = 10))
```

![](https://i.imgur.com/nvdNJZH.png)

<sup>Created on 2022-03-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bniebuhr** [comment]
Great! That works perfectly!

**Comment by mtennekes** [comment]
FYI: in tmap4, `breaks` is replaced with the arguments `limits` and `ticks` in `tm_scale_continuous`: the former if only the limits need to be specified, the latter in case tick labels need to be specified:

 The code will be:

```r
tm_shape(World) + tm_polygons("life_exp", fill.scale = tm_scale_continuous(limits = c(0, 100)))
```

![image](https://github.com/user-attachments/assets/0a33e706-763b-4996-a9f7-fbe6a15762f8)

```r
tm_shape(World) + tm_polygons("life_exp", fill.scale = tm_scale_continuous(ticks = seq(0, 100, by = 10)))
```

![image](https://github.com/user-attachments/assets/3102a00b-1859-442d-8a17-01d6416df0f6)

**Comment by bniebuhr** [comment]
And what option should I use for that for setting the limits of a raster plot, in tmap4?
