### ISSUE TITLE
Large blank space between map and caption when publishing pdf

### ISSUE THREAD

**Issue by Nico-Rojas** [r-tmap/tmap#641]
Hi, 

First of all, thank you so much for this incredible package. It makes life better. 

Now, my issue. I'm working on a paper that includes a tmap. However, when I knit the document a large white blank space appears between the map and the caption. This does not happen for other figures. In the example below, I tried to make the simplest comparison between a tmap figure and a ggplot figure. If you paste all the text below in a white .Rmd document and knit it you will see the problem. 

Thank you so much in any event. 
Best wishes, 
Nico  

---
title: "Two examples ggplot vs tmap"
output: pdf_document
---

```{r, message = F, warning = F, echo = F}
library(tmap)
library(tmaptools)
library(sf)
library(tidyverse)
```

```{r, fig.cap =  "A tmap example that does have a blank space between figure and title", echo = F}
data("World", "land", "rivers", package = "tmap")
tm_shape(World) + 
tm_polygons(col = "income_grp", palette = "OrRd") + 
tm_text(text = "iso_a3", size = "AREA") 
```

```{r, fig.cap =  "A ggplot example that does not have a large blank space between figure and title", echo = F}
data("midwest", package = "ggplot2") 
ggplot(midwest, aes(x=area, y=poptotal)) + 
  geom_point(aes(col=state, size=popdensity)) + 
  geom_smooth(method="loess", se=F) 
```

**Comment by mtennekes** [comment]
I got this:

[issue641.pdf](https://github.com/r-tmap/tmap/files/8397162/issue641.pdf)

(with `tm_layout(asp = 0, outer.bg.color = "grey70")`)

The space between caption and figure is similar between the plots. Is that what you mean?

**Comment by Nico-Rojas** [comment]
Thanks so much @mtennekes. I feel we we see different outputs. This is what I see: 
[issue641_reply.pdf](https://github.com/r-tmap/tmap/files/8398439/issue641_reply.pdf)

Github is hidding the chunk options in my post (although it seems you got them). This is my code 
[issue641_code.txt](https://github.com/r-tmap/tmap/files/8398489/issue641_code.txt)

Do you see the same thing in that case?  I found a workaround by exporting the map in PNG and then using knitr to paste the image. That works perfectly well. But still I'm puzzled by why should be doing that.

**Comment by mtennekes** [comment]
This is my exact code, with """ instead of ``` to make sure you got the raw text:

"""{r, fig.cap =  "A tmap example that does have a blank space between figure and title", echo = F, fig.height=4}
data("World", "land", "rivers", package = "tmap")
tm_shape(World) + 
	tm_polygons(col = "income_grp", palette = "OrRd") + 
	tm_text(text = "iso_a3", size = "AREA") +
	tm_layout(asp = 0, outer.bg.color = "grey70") 
"""

`asp=0` makes sure the map follows the device's aspect ratio. I've set fig.height to 4 to get a landscape map.

**Comment by Nowosad** [comment]
Closing for now. Feel free to reopen it if you have more questions, @Nico-Rojas.

**Comment by Nico-Rojas** [comment]
Thank you so much @mtennekes 

Got it @mtennekes, I could replicate your map. Now, a potential issue with that solution is that even if the white space between the map and the title disappears, there is a new white space that appears at the bottom of the map. 
![white](https://user-images.githubusercontent.com/43378796/165544640-3135a6f6-f733-4df4-9431-ae3ffdc421e1.JPG)


(ps: Thanks @Nowosad )

**Comment by mtennekes** [comment]
That is most likely caused by the aspect ratio: the map is more landscape than the available space, so inner.margins are used to compensate for that with margins at the bottom (where you referred to) and at the top.

The solution would probably be to reduce fig.height a bit (e.g. 3.7 instead of 4).

**Comment by Nico-Rojas** [comment]
Thank you @mtennekes. That works, I reduced the height to 3, and at that point, there was barely any more margin.  Thanks once again for your dedicated answer and for the package 🙏
