### ISSUE TITLE
Customizing palette colors from a categorical variable in tmap

### ISSUE THREAD

**Issue by PauGallesClara** [r-tmap/tmap#643]
Hi! I'm trying to make a cluster map from a categorical variable, and i would like to customize the palette. 
The problem that I see is that i'm doing that as if the map was a made from numerical variable, but my breaks ae factors. Here you have a sample of the code that I've been running with no succes.

`Breaks <-  c("Not significant", "High-High", "Low-Low", "Low-High" ,"High-Low" )

MyPalette <- c("transparent", "red", "blue", "lightblue", "salmon" )
Labels <- c("Not significant", "High-High", "Low-Low", "Low-High" ,"High-Low" )

map_LISA_IA_t =tm_shape(IA_t_sel)+
  tm_polygons(col = "cluster",
              breaks = Breaks,
              labels=Labels,
              paette=MyPalette)`

Any suggestions?

**Comment by PauGallesClara** [comment]
In addition, I would like to say that I'm able to do that using ggplot but i want to use tmap beacuse after I want to use de tmap_leaflet() to make an interactive map. Here you have the sample of the code
`ggplot(data = IA_t_sel) +
  geom_sf(aes(fill = cluster)) +
  scale_fill_manual(values = c("transparent", "red", "blue", "lightblue", "salmon" ), name= "cluster")
  `

**Comment by Nowosad** [comment]
@PauGallesClara can you share the `IA_t_sel` object with us?

**Comment by PauGallesClara** [comment]
Hi Jakub @Nowosad it's my privilege to speak with you. Actually, I've learn all about sf stuf following your tutorials and books...
Here I have a descriptionof the  IA_t_sel object . As you can see below its a sf class with 4 variables. "nom" is the name of the neigbourhood, "IA_t" is the Acumulate Incidence, and "cluster" is the variable of the result of applying a LISA analysis
`> IA_t_sel
Simple feature collection with 61 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 1.057537 ymin: 41.10218 xmax: 1.191152 ymax: 41.18993
Geodetic CRS:  WGS 84
# A tibble: 61 x 4
   nom             IA_t                                                         geometry.x cluster    
 * <chr>          <dbl>                                                      <POLYGON [°]> <fct>      
 1 AEROPORT          0  ((1.146554 41.14369, 1.148681 41.14308, 1.149898 41.14274, 1.1507~ Low-Low    
 2 AGRO-REUS     11111. ((1.07688 41.15442, 1.077995 41.1537, 1.078991 41.15311, 1.08025 ~ Not signif~
 3 AIGÜESVERDS  289812. ((1.097462 41.12139, 1.097536 41.12125, 1.097558 41.12121, 1.0976~ Not signif~
 4 ALCOLEA      450000  ((1.085471 41.15996, 1.085514 41.15992, 1.085546 41.15987, 1.0855~ Not signif~
 5 AMPLE       3155010. ((1.093025 41.15925, 1.093389 41.15909, 1.09398 41.15888, 1.09435~ Not signif~
 6 BELLISSENS   977618. ((1.11669 41.14088, 1.11725 41.14017, 1.117754 41.13953, 1.118095~ Not signif~
 7 BLANCAFORT   105195. ((1.090153 41.13673, 1.090158 41.13663, 1.090176 41.13651, 1.0902~ Not signif~
 8 CARME       3391876. ((1.102069 41.15386, 1.102199 41.15365, 1.102266 41.15353, 1.1025~ High-High  
 9 CARRILET    4297647. ((1.10715 41.15048, 1.107714 41.14998, 1.108013 41.14971, 1.10825~ High-High  
10 CASC ANTIC  1745009. ((1.106835 41.15551, 1.106891 41.15528, 1.107023 41.1548, 1.10706~ High-High  
# ... with 51 more rows`

**Comment by Nowosad** [comment]
Have you just tried:

```r
MyPalette <- c("transparent", "red", "blue", "lightblue", "salmon" )

map_LISA_IA_t = tm_shape(IA_t_sel) +
  tm_polygons(col = "cluster",
  palette = MyPalette)
map_LISA_IA_t
```

?

If it does not work -- please save your data (`saveRDS(IA_t_sel, "IA_t_sel.rds"`) and attach the `IA_t_sel.rds` file on this website.

**Comment by PauGallesClara** [comment]
[IA_t_sel.zip](https://github.com/r-tmap/tmap/files/8380491/IA_t_sel.zip)
It doesn't work, so here you have the file attached.
It gives me the error "invalid palette"

**Comment by Nowosad** [comment]
@PauGallesClara,

the main problem here was that **tmap** does not understand the `transparent` color. Try using `NA` instead. Also -- you only specify six colors, but have seven categories.

```
library(sf)
library(tmap)
IA_t_sel = readRDS("IA_t_sel.rds")
MyPalette = c("transparent", "red", "blue", "lightblue", "salmon", "blue")

tm_shape(IA_t_sel) +
  tm_polygons("cluster")

tm_shape(IA_t_sel) +
  tm_polygons("cluster",
              palette = MyPalette)

MyPalette2 = c("yellow", "red", "blue", "lightblue", "salmon", "brown")
tm_shape(IA_t_sel) +
  tm_polygons("cluster",
              palette = MyPalette2)

MyPalette3 = c(NA, "red", "blue", "lightblue", "salmon", "blue")
tm_shape(IA_t_sel) +
  tm_polygons("cluster",
              palette = MyPalette3)
```

**Comment by PauGallesClara** [comment]
Hi !!
I've tried your examples, and in the palette 2 excamples it creates a grey category in in the High-Low value.
In the palette3 example although its being improved the "grey" categoru for the High-Low valueremains.
So I've created a 4palette example where now the High-low value gets salmon (as disired). But the legend now is empty !! do you know why is that?

`MyPalette4 = c(NA, "red", "blue", "lightblue","salmon", "orange", "yellow")
map_LISA_IA_t=tm_shape(IA_t_sel) +
  tm_polygons("cluster",
              palette = MyPalette4)
tmap_leaflet(map_LISA_IA_t)`

**Comment by Nowosad** [comment]
My suggestion for now is to use `"white"` instead of `NA`. It seems that `NA` does not work in the interactive mode.

**Comment by Nowosad** [comment]
@mtennekes -- it seems that a transparent color does not work the interactive mode:

```r
library(tmap)
library(sf)
temp = tempfile()
download.file("https://github.com/r-tmap/tmap/files/8380491/IA_t_sel.zip", temp)
con = unz(temp, "IA_t_sel.rds")
IA_t_sel = readRDS(gzcon(con))

# works
MyPalette4 = c("white", "red", "blue", "lightblue","salmon", "orange", "yellow") 
map_LISA_IA_t = tm_shape(IA_t_sel) + tm_polygons("cluster", palette = MyPalette4) 
tmap_leaflet(map_LISA_IA_t)

# issue
MyPalette4 = c(NA, "red", "blue", "lightblue","salmon", "orange", "yellow") 
map_LISA_IA_t = tm_shape(IA_t_sel) + tm_polygons("cluster", palette = MyPalette4) 
tmap_leaflet(map_LISA_IA_t)

# issue
MyPalette4 = c("#00000000", "red", "blue", "lightblue","salmon", "orange", "yellow") 
map_LISA_IA_t = tm_shape(IA_t_sel) + tm_polygons("cluster", palette = MyPalette4) 
tmap_leaflet(map_LISA_IA_t)
```

**Comment by PauGallesClara** [comment]
I see... anyway I've changed NA for "white" and then changed the opacity as it follows

`MyPalette5 = c("white", "red", "blue", "lightblue","salmon", "white", "white")
map_LISA_IA_t=tm_shape(IA_t_sel) +
  tm_polygons("cluster",
              palette = MyPalette5, alpha = 0.5)
tmap_leaflet(map_LISA_IA_t)`

Thank you very much or your time and detailed explanaitons Jakub !!!

**Comment by mtennekes** [comment]
By design, tmap separates color from alpha (transparency).

I don't know anymore by heart how to get the job done in the current tmap version, but in **tmap4** it will be:

```r
MyPalette4 = c("white", "red", "blue", "lightblue","salmon", "orange", "yellow") 
MyAlphas = c(0.5, 1, 1, 1, 1, 1, 1)

tm_basemap(server = "OpenStreetMap") + 
tm_shape(IA_t_sel) + 
  tm_polygons(fill = "cluster", 
    fill.scale = tm_scale_categorical(values = MyPalette4, value.neutral = "blue"), 
    fill_alpha = "cluster", 
    fill_alpha.scale = tm_scale_categorical(values = MyAlphas), fill_alpha.legend = tm_legend_combine("fill")) +
tm_layout(legend.bg.color = "#F2EFE9") # to match OSM background
```

Which gives in `"plot"` mode:

![image](https://user-images.githubusercontent.com/2444081/161251564-791686ca-2534-481a-aa74-75bdb66e140f.png)

and in `"view"` mode:

![image](https://user-images.githubusercontent.com/2444081/161251794-57b920c2-80b8-4dac-82c6-f84dc606e593.png)

**Comment by PauGallesClara** [comment]
Thank you @mtennekes for adding thid comment . Also really helpful !!
