### ISSUE TITLE
for loop in R

### ISSUE THREAD

**Issue by maahiir** [r-tmap/tmap#645]
Hi
I am trying to write a for loop in r to convert multiple variables with similar character pattern in r to as.factor
Below is the function I wrote, R runs the code, does not show any error, but does not give the desired output. There is a logical error, can someone help me correct this error?

for (i in grep(pattern = "hml35_", x=tanre)) {
    tanre$i<-as.factor(tanre$i)
}

Thank you so much!

**Comment by Robinlovelace** [comment]
Hi @maahiir it's a good question but I don't think this is the right place: this the issue tracker for the {tmap} package so a question on for loops is off topic. I suggest asking in a more general place like StackOverflow of the RStudio community, with reference to a reproducible example: https://community.rstudio.com/t/faq-tips-for-writing-r-related-questions/6824
