### ISSUE TITLE
Argument "green" is missing

### ISSUE THREAD

**Issue by AGeographer** [r-tmap/tmap#653]
Hi,
I came across a weird error message, which might be generated by the `tm_raster()` function which seems to call `terra`'s `coltab()` function (Robert Hijmans thinks it is not an error from `terra`, see https://github.com/rspatial/terra/issues/618).   
I have created a categorical raster dataset called _clutter_ and wanted to draw a map with the `tmap` package. This same code has worked last October without problems. However, with the latest CRAN version of the `terra` and `tmap` package I get the error message below running the following code:  
```
library(tmap)
tm_shape(clutter) +
  tm_raster(# we set the classification to categorical
            style = "cat",
            # we delete empty labels
            labels = labels[labels != ""],
            # and use our custom colors
            palette = clutter.colors)
```
`Error in rgb(terra::coltab(.x)[[1]], maxColorValue = 255) : 
  argument "green" is missing, with no default`

In `tm_raster()` the following is used: 
```
 labels[labels != ""]
[1] "water"             "coniferous forest" "open land"         "airport"          
[5] "industrial"        "urban"             "dense urban"       "wetland"  
```
and
```
clutter.colors
[1] "blue"      "darkgreen" "grey"      "yellow"    "black"     "red"       "darkred"  
[8] "limegreen"
```
and, of course:
```
clutter
class       : SpatRaster 
dimensions  : 403, 448, 1  (nrow, ncol, nlyr)
resolution  : 90, 90  (x, y)
extent      : 578475, 618795, 5026455, 5062725  (xmin, xmax, ymin, ymax)
coord. ref. : NAD83(CSRS) / UTM zone 18N (EPSG:2959) 
source      : memory 
name        : landuse 
min value   : airport 
max value   : wetland 
```
Unfortunately, I cannot share _clutter_ due to licensing issues.
Any idea what's going on here?
Thanks.
Tim

**Comment by Nowosad** [comment]
Does `library(tmap); tm_shape(clutter) +   tm_raster()` alone work?

**Comment by Nowosad** [comment]
@AGeographer `drop.levels = TRUE` seems to be a solution to your problem:

```r
tm_shape(clutter) +
  tm_raster(
    style = "cat",
    labels = labels[labels != ""],
    palette = clutter.colors,
    drop.levels = TRUE)
```

**Comment by AGeographer** [comment]
It still throws the error message, but it works. Thanks!
