### ISSUE TITLE
Add stretch parameter(s) in tm_raster() and tm_rgb().

### ISSUE THREAD

**Issue by aterhorst** [r-tmap/tmap#655]
I am working with Landsat 8 surface reflectance imagery. Surface reflectance is expressed as 16-bit integer values. I prefer not to rescale Landsat data to 8-bit.

When I use tm_rgb(), I set the max.value parameter to the highest 16-bit value in my raster stack. However, the result is a dark image. It would be nice if tm_raster() and tm_rgb() allowed users to stretch the data like plotRGB() allows.

Thanks for considering this feature request.

**Comment by aterhorst** [comment]
Perhaps adding a min.value= option would help?

**Comment by mtennekes** [comment]
Great idea. I don't have time to implement this feature in v3, but it will be included in v4.

**Comment by aterhorst** [comment]
Thank you. I think passing the raster::stretch parameters through would be nice, especially if we are working with 16-bit image data.

From: mtennekes ***@***.***>
Date: Tuesday, 10 May 2022 at 6:04 pm
To: r-tmap/tmap ***@***.***>
Cc: Terhorst, Andrew (Data61, Sandy Bay) ***@***.***>, Author ***@***.***>
Subject: Re: [r-tmap/tmap] Add stretch parameter(s) in tm_raster() and tm_rgb(). (Issue #655)

Great idea. I don't have time to implement this feature in v3, but it will be included in v4.

**Comment by Nowosad** [comment]
Related: https://github.com/r-tmap/tmap/issues/345
