### ISSUE TITLE
Need to merge yield data from .RDS data frame for each GDMID with shape file and plot the map filled with yield

### ISSUE THREAD

**Issue by rkjha2** [r-tmap/tmap#657]
Hello,

I am trying to plot an Indian district shapefile filled with modeled yield, corresponding to each GDMID, common in shapefile and .rds dataframe. I need to first merge the Yield data with respect to each GDMID from the .RDS file with the district shapefile of India. Each district is represented by a GDMID. After merging, the Indian district map filled with modeled yield values needs to be plotted. Shape file has five features, and one of them is "GDMID".

I feel there is something wrong with my code for merging and plotting by ggplot.

I have provided my files in the given link. [[link in 1][1]](https://drive.google.com/drive/folders/1dNmGTI8_c9PK1QqmfIjnpbyzuiCXgxFC?msclkid=4816425dd04111ec912cf8b4175aa93c)

I am new to the spatial mapping with R so needs help clarity with steps.

Thanks in advance,
Ranjeet

**Comment by Nowosad** [comment]
@rkjha2 -- please use websites designed for asking such questions (e.g., https://gis.stackexchange.com/). The GitHub issue tracker is mostly for bug reports and enhancement proposals.
