### ISSUE TITLE
quick thematic map plot qtm() function doesn't add plot titles correctly when knitting .Rmd document

### ISSUE THREAD

**Issue by hulsiejames** [r-tmap/tmap#660]
I am currently writing a .Rmd (R markdown document) on downloading and visualising the Local Authority Districts (LADs) and transport regions of the UK within Rstudio.
```
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          2.0                         
year           2022                        
month          04                          
day            22                          
svn rev        82229                       
language       R                           
version.string R version 4.2.0 (2022-04-22)
```

I am doing this in a .Rmd so that this document can be hosted on github as a vignette. 

I am having an issue whereby I have four separate plots which should all have unique titles set with `qtm(title = 'desired_title')` as per the [documentation][1], however all titles are being assigned to my first plot and none of the plots after, even though the other plots are building correctly (legend, polygon colours etc.)

I have been knitting the document locally to view my changes rather than uploading every edit to GH to visualise my edits (```knitr version: 1.39```) 

Here are the steps to **reproduce my issue**: 
Note: code inbetween __ lines indicate seperate code chunks within the .Rmd

```
______________________
library(sf)    
library(tmap)  
library(dplyr)
______________________

______________________
# Download data from the openinfra repo
url_regions_lad = "https://github.com/udsleeds/openinfra/raw/main/data-small/lads_joined_2021.geojson"
url_transport_regions = "https://github.com/udsleeds/openinfra/raw/main/data-small/regions_new.geojson"
______________________

______________________
# Load data into a Simple Features frame
regions_lad = read_sf(url_regions_lad)
transport_regions = read_sf(url_transport_regions)
______________________

______________________
# Set tmap mode to interactive
tmap::tmap_mode('view') # After this, all tmap::qtm() plots will be interactive
______________________

______________________
# Here we create the interactive plots
sf::sf_use_s2(use_s2 = FALSE)
regions_lad %>% tmap::qtm(title = 'LADs of UK & NI')
______________________

______________________
# Here we create an interactive plot of all LADs, coloured by the region they reside in
tmap_options(max.categories = 78) # Increase max categories so every (78) transport region has its own colour
regions_lad %>% tmap::qtm(fill = 'Region_name', title = 'LADs of UK & NI coloured by region')
______________________

______________________
# Here we plot the transport regions of England
transport_regions %>% tmap::qtm(title = 'Transport regions of England')
______________________

______________________
# Here we create the coloured interactive plot of England's transport regions
transport_regions %>% tmap::qtm(title = 'Coloured transport regions of England', fill = 'Region_name')
______________________
```
Note that `sf::sf_use_s2(use_s2 = FALSE)` is a [fix][2] for errors ([1][3] [2][4]) due to an [upgrade][5] to the sf package

**What I expect**:<br> 
I expect to see each of the four plots with their own respective titles added, much like this
![](https://i.imgur.com/QK3XwUA.png)

**What I get**: <br>
Instead I have all four of my plot titles (the most recently created being the top title) added to the first plot and none after.
![Single plot with all 4 titles on][6]

The figures themselves are building correctly (This one has coloured all LADs based on the LAD region name as expected specifying `fill='Region_name'`) ![][7] with the exception of titles, as can be seen in the example above of coloured LADs, there is no title in the plot despite using `regions_lad %>% tmap::qtm(fill = 'Region_name', title = 'LADs of UK & NI coloured by region')`

[See the plot title issues on the vignette hosted on GH here][8]

__________________________________________________________________________________________________________

I should also note that running the same code as a .R script (rather than a .Rmd rendered with knitr) included below does have the desired outcome - that is four seperate interactive plots within the 'Viewer' pane of Rstudio each with the correct plot title, I can switch between plots using (![](https://i.imgur.com/GGD8pmT.png))

However as I was looking to uploaded this as a vignette tutorial I would still like this to work as such. I just don't know if this may be an issue with tmap::qtm or the knitr package, or how these two packages interact and was hopeing someone has come across this issue before. 

**R script**
```
library(sf)    # Simple Features (sf) library for storing geospatial data 
library(tmap)  # tmap library for interactive plots
library(dplyr) 


# Download data from the openinfra repo
url_regions_lad = "https://github.com/udsleeds/openinfra/raw/main/data-small/lads_joined_2021.geojson"
# Load data into a Simple Features frame
regions_lad = read_sf(url_regions_lad)


# Download data from the openinfra repo
url_transport_regions = "https://github.com/udsleeds/openinfra/raw/main/data-small/regions_new.geojson"
# Load data into a Simple Features frame
transport_regions = read_sf(url_transport_regions)

# Set tmap mode to interactive
tmap::tmap_mode('view') # After this, all qtm() plots will be interactive

# Here we create the  interactive plots
sf::sf_use_s2(use_s2 = FALSE)
regions_lad %>% tmap::qtm(title = 'LADs of UK & NI')

tmap_options(max.categories = 78) # We increase max categories so that every transport region has its own colour
regions_lad %>% tmap::qtm(fill = 'Region_name', title = 'LADs of UK & NI coloured by region')


transport_regions %>% tmap::qtm(title = 'Transport regions of England')

# Here we create the interactive plot of England's transport regions
transport_regions %>% tmap::qtm(title = 'Coloured transport regions of England', fill = 'Region_name')
```

  [1]: https://rdrr.io/cran/tmap/man/qtm.html
  [2]: https://github.com/r-spatial/sf/issues/1649#issuecomment-860231045
  [3]: https://github.com/r-tmap/tmap/issues/577
  [4]: https://github.com/r-tmap/tmap/issues/571
  [5]: https://github.com/r-spatial/sf/issues/1649
  [6]: https://i.stack.imgur.com/bSOUh.png
  [7]: https://i.stack.imgur.com/NijPl.png
  [8]: https://udsleeds.github.io/openinfra/articles/regions.html

**Comment by mtennekes** [comment]
Same as https://github.com/r-tmap/tmap/issues/441:

Titles are added afterwards via some javascript code: https://github.com/r-tmap/tmap/blob/master/R/view_add_leaflet_titles.R

This does not work when there are several maps in the same html page, as your example shows.

Someone ideas how to fix this? @tim-salabim do you know any leaflet plugin/add-on to add map titles like these?

**Comment by Robinlovelace** [comment]
You can embed the self-standing html maps with `knitr::include_url()` if I remember correctly.

**Comment by tim-salabim** [comment]
@mtennekes sorry, I don't. leaflet has a `addControl` which might work better? Re, your JS code, I think it is because you're looking for `document.getElementsByClassName(\"leaflet-top leaflet-left\")[0];` which will always find the first on the page/document and thus place all of them in the first map I guess. Maybe something like:

```js
var tldiv = document.getElementsByClassName(\"leaflet-top leaflet-left\");
var lnth = tldiv.length;
tldiv = tldiv[lngth-1];
```
could work (assuming it finds 2 `tldiv`s when there are two maps on the page)?
