### ISSUE TITLE
tmap4: backward compability

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#662]
Hi @mtennekes - I am now testing tmap4 on some older code examples. The below one seems not to work. Is this an oversight or an expected behavior?

``` r
library(tmap)
library(spData)

tm_shape(nz) + 
  tm_fill() +
  tm_layout(title = "tm_shape(nz) +\n  tm_fill()", title.size = 0.7)
#> Error in tm_layout(title = "tm_shape(nz) +\n  tm_fill()", title.size = 0.7): argument 1 matches multiple formal arguments
```

<sup>Created on 2022-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Nowosad** [comment]
``` r
library(tmap)
library(terra)

nz_elev = rast(system.file("raster/nz_elev.tif", package = "spDataLarge"))

tm_shape(nz_elev) + tm_raster(alpha = 0.7)
#> Error in tm_raster(alpha = 0.7): unused argument (alpha = 0.7)
```

<sup>Created on 2022-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Nowosad** [comment]
The `tm_dots()` function is missing.

**Comment by Robinlovelace** [comment]
For the record, I've been testing v4.0.0 with @temospena and have found low levels of backwards compatibility. Happy to share some more reproducible examples here if that would be useful. My thinking: fine for there to be some breaking changes as this is a major revamp of the package but the fewer breaking changes the better to minimise pain. I guess that's the purpose of this issue!

**Comment by Nowosad** [comment]
``` r
library(spData)
library(tmap)

# not allowed
ma1 = tm_shape(nz) + tm_fill(col = "red")
#> Error in tm_fill(col = "red"): argument 1 matches multiple formal arguments

# allowed
ma3 = tm_shape(nz) + tm_borders(col = "blue")
```

<sup>Created on 2022-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Nowosad** [comment]
This action returns an error in tmap3, but now is gives some (?!) output:

``` r
library(tmap)
library(spData)
tm_shape(nz) + tm_fill(fill = nz$Land_area)
```

![](https://i.imgur.com/HfL61lA.png)

<sup>Created on 2022-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Nowosad** [comment]
``` r
library(tmap)
library(spData)

# works
map_nza = tm_shape(nz) +
  tm_fill(fill = "Land_area", fill.legend = tm_legend(title = "Some map title!!"))
map_nza
```

![](https://i.imgur.com/paElPnU.png)

``` r
# fails
map_nza2 = tm_shape(nz) +
  tm_fill(fill = "Land_area", fill.legend = tm_legend(title = expression("Area (km"^2*")")))
map_nza2
#> Warning in is.na(l$title): is.na() applied to non-(list or vector) of type
#> 'expression'
#> Error in comp$title == "": comparison is not allowed for expressions
```

tmap3 allows to provide expressions as legend titles. Also, as we discussed -- it would be great to be able to use markdown in such cases.

**Comment by mtennekes** [comment]
Backwards compatibility is very important, but at this stage in development way to early to expect that (still some to-dos: https://github.com/r-tmap/tmap/issues/599). But you mentioned some good points @Nowosad I'll come back to these issues.

**Comment by mtennekes** [comment]
> Hi @mtennekes - I am now testing tmap4 on some older code examples. The below one seems not to work. Is this an oversight or an expected behavior?
> 
> ```r
> library(tmap)
> library(spData)
> 
> tm_shape(nz) + 
>   tm_fill() +
>   tm_layout(title = "tm_shape(nz) +\n  tm_fill()", title.size = 0.7)
> #> Error in tm_layout(title = "tm_shape(nz) +\n  tm_fill()", title.size = 0.7): argument 1 matches multiple formal arguments
> ```
> 
> Created on 2022-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)


In tmap3, the titles (main title, title, panel titles) were indeed created via `tm_layout`.

In tmap4, these will be regarded/treated as map components, like compasses and scale bars. The big advantage is that it is possible to create multiple ones, e.g.

```r
tm_shape(nz) + 
	tm_fill() +
	tm_title("tm_shape(nz) +\n  tm_fill()", size = 1.2, position = tm_pos_auto_in()) +
	tm_title("2nd title", size = 0.8, position = tm_pos_in("right", "bottom"))
```

Note 1. Currently the default of title is to be placed outside the frame (`tm_pos_auto_out`), but this default setting could be changed
Note 2. Backwards compatibility can be achieved by creating a `tm_title` element under the hood when the user calls `tm_layout(title = ...)`

**Comment by mtennekes** [comment]
> ```r
> ```r
> library(tmap)
> library(terra)
> 
> nz_elev = rast(system.file("raster/nz_elev.tif", package = "spDataLarge"))
> 
> tm_shape(nz_elev) + tm_raster(alpha = 0.7)
> #> Error in tm_raster(alpha = 0.7): unused argument (alpha = 0.7)
> ```
> 

`tm_raster` does not use `alpha` but `col_alpha`.

This is an (ugly) artefact of our attempt to harmonise the visual variable names. As I think of it now, we don't have to harmonise the visual variable names _that_ strict. The tmap4 design allows for non-harmonic visual variable names.

So I am happy to change `col_alpha` to `alpha`. 

Similar for `tm_fill`, which uses only one color visual variable, which is `"fill"` (BTW: I've now removed `"col_alpha"`, because there already is `"fill_alpha"`). To me, `tm_fill(fill = "x")` feels a bit repetitive, but it is consistent with `tm_polygons(fill = "x", col = "y")`. Alternatively, we _could_ switch back to `"col"` and `"border.col"`
Let me know your opinions @Nowosad and @Robinlovelace

**Comment by mtennekes** [comment]
> ```r
> library(tmap)
> library(spData)
> tm_shape(nz) + tm_fill(fill = nz$Land_area)
> ```

R is sometimes too flexible: the numbers are translated to colors (just like `plot(1:100, col=1:100, pch = 16)`).
Now I've added visual value checks, so should through an error now (error message to be improved).

**Comment by Nowosad** [comment]
`tm_compass` and `tm_scale_bar` are missing

**Comment by Nowosad** [comment]
``` r
library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.3, PROJ 8.2.1; sf_use_s2() is TRUE
library(tmap)
#> Warning: multiple methods tables found for 'area'
#> 
#> Attaching package: 'tmap'
#> The following object is masked from 'package:datasets':
#> 
#>     rivers
library(terra)
#> terra 1.5.50
library(spData)
nz_elev = rast(system.file("raster/nz_elev.tif", package = "spDataLarge"))

# works
tm_shape(nz_elev) +
  tm_raster()
#> SpatRaster object downsampled to 1141 by 877 cells.
```

![](https://i.imgur.com/T0ozMx9.png)

``` r
nz_region = st_bbox(c(xmin = 1340000, xmax = 1450000,
                      ymin = 5130000, ymax = 5210000),
                    crs = st_crs(nz_height)) |> 
  st_as_sfc()

# fails
tm_shape(nz_elev, bbox = nz_region) +
  tm_raster()
#> SpatRaster object downsampled to 1141 by 877 cells.
#> Error in m[, 1:2, drop = FALSE]: subscript out of bounds
```

<sup>Created on 2022-07-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Nowosad** [comment]
What is the current recommended way to add a map title? `tm_layout()` does not have the `title` argument...

**Comment by Nowosad** [comment]
Superseded by https://github.com/r-tmap/tmap/issues/694
