### ISSUE TITLE
Fullscreen Toggle

### ISSUE THREAD

**Issue by Saadi4469** [r-tmap/tmap#668]
Good day,

How can I add a fullscreen toggle to a `tmap` in `R` `Shiny`?

Thank you,

**Comment by oduilln** [comment]
Tmap uses leaflet when plotted in R Shiny. So you can use the fullscreen control plugin from the leaflet.extras package:
[https://bhaskarvk.github.io/leaflet.extras/reference/fullscreen.html](https://bhaskarvk.github.io/leaflet.extras/reference/fullscreen.html
)

To convert a tmap plot to leaflet, you use tmap_leaflet(), so you would have something like:

```
library(tmap)
library(leaflet.extras)

data(World)

tmap <- tm_shape(World) +
  tm_polygons("pop_est")

leaflet_map <- tmap_leaflet(tmap) 

leaflet_with_fullscreen <- leaflet_map %>%
  addFullscreenControl()
```

You might need to adapt my example for shiny, but the renderTmap and tmapOutput code converts to leaflet at some point
