### ISSUE TITLE
Some district is unmapped

### ISSUE THREAD

**Issue by peasantxuan** [r-tmap/tmap#669]
tm_shape(Botswana_shp_same_diff_female_30year) +
  tm_polygons(
    col = "Prevalence",
    pal = viridis(10, direction = -1)
  ) +
  tm_facets(by = "level_0") +
  tm_layout(legend.outside.size = 0.2)
![截屏2022-07-14 01 06 20](https://user-images.githubusercontent.com/103459652/178851844-08e3cb21-d9ce-46d8-a9d4-4e11502a5931.png)

In different time, it will lack different data.
![截屏2022-07-14 01 07 39](https://user-images.githubusercontent.com/103459652/178851971-cc87c22e-8388-423c-912b-1ed2cb68ff2b.png)

**Comment by Nowosad** [comment]
@peasantxuan -- try some arguments in `tm_facets()` such as `free.coords = FALSE` `drop.units = FALSE`, etc.
