### ISSUE TITLE
Map of polygon attributes differs between tmap and ggplot

### ISSUE THREAD

**Issue by edmundseto** [r-tmap/tmap#670]
I'm working with redlining spatial data from the Mapping Inequalities website: https://dsl.richmond.edu/panorama/redlining/

I noticed when I use tmap in either view or plot mode, the mapped attributes (fill and text) differs from what I get using ggplot2 for this particular dataset.  Ggplot2 matches the maps on the Mapping Inequality website, and matches maps I created in ArcGIS.  The code below should reproduce the issue, using the data from the Mapping Inequalities website: https://dsl.richmond.edu/panorama/redlining/#loc=5/39.1/-94.58&text=downloads

```
library(sf)
library(tmap)
library(ggplot2)

holc_sf <- read_sf("redline_fullshpfile/shapefile/holc_ad_data.shp")

holc_sf$holc_grade <- factor(holc_sf$holc_grade)

# there are some issues with the geometry, fix with this...
holc_valid_sf <- st_make_valid(holc_sf)

# bound tmap just to Seattle (but the problem is there even if I don't use the bbox)
tmap_mode("view")
tm_shape(holc_valid_sf, bbox=st_bbox(holc_valid_sf[holc_valid_sf$city=="Seattle",])) + 
  tm_polygons(col="holc_grade", palette = c("green", "blue", "yellow", "red", "black"),
                                      popup.vars=c("state", "city", "name", "holc_id")) +
tm_shape(holc_valid_sf, bbox=st_bbox(holc_valid_sf[holc_valid_sf$city=="Seattle",])) +
  tm_text("holc_id")
```
![Rplot_tmap1](https://user-images.githubusercontent.com/33795479/181130102-a0cef3e7-3d1b-45a1-89ce-a6c3e0aa40d2.png)

```
# versus what I get when I use ggplot
ggplot(holc_valid_sf) + 
  geom_sf(aes(fill=holc_grade), alpha=0.5) +
  scale_fill_manual(values = c("green", "blue", "yellow", "red", "black")) +
  geom_sf_text(aes(label=holc_id)) + 
  coord_sf(xlim = c( st_bbox(holc_valid_sf[holc_valid_sf$city=="Seattle",])$xmin, 
                                  st_bbox(holc_valid_sf[holc_valid_sf$city=="Seattle",])$xmax ),
                    ylim = c( st_bbox(holc_valid_sf[holc_valid_sf$city=="Seattle",])$ymin, 
                                    st_bbox(holc_valid_sf[holc_valid_sf$city=="Seattle",])$ymax ) )
```
![Rplot2b](https://user-images.githubusercontent.com/33795479/181130138-590c7fd8-cebe-4301-a2dc-ac6cc581ffcb.png)

Comparing the two maps, I noticed the labeled IDs of the polygons changed, as well as the fill color corresponding to the redlining grade category.  I did get warnings, which maybe related to the issue?  After running tmap, I got these warnings:
```
Warning messages:
1: The shape holc_valid_sf contains empty units. 
2: The shape holc_valid_sf contains empty units. 
```
And after running ggplot, I got these warnings:
```
Warning messages:
1: In st_point_on_surface.sfc(sf::st_zm(x)) :
  st_point_on_surface may not give correct results for longitude/latitude data
2: Removed 127 rows containing missing values (geom_text). 
```

I explored further, and noticed if I subset the data to just Seattle polygons before using tmap, the resulting map no longer jumbles the mapped attributes, and I didn't get the warnings about "empty units".

```
# filtering just the Seattle data and mapping it doesn't have this issue
tm_shape(holc_valid_sf[holc_valid_sf$city=="Seattle",]) + 
   tm_polygons(col="holc_grade", palette = c("green", "blue", "yellow", "red", "black"),
                                      popup.vars=c("state", "city", "name", "holc_id")) +
tm_shape(holc_valid_sf[holc_valid_sf$city=="Seattle",]) + 
   tm_text("holc_id")
```

![Rplot_tmap2](https://user-images.githubusercontent.com/33795479/181130169-b38a7836-e939-4a02-bfe2-e3df6898cf16.png)

Finally, it does seem like the "shape contains empty units" issue is the problem.  Removing empty units seemed to solve the issue, and produce maps that matched ggplot.

```
# removing "empty units"
not_empty <- holc_valid_sf[!st_is_empty(holc_valid_sf),]

tm_shape(not_empty, bbox=st_bbox(not_empty[not_empty$city=="Seattle",])) + 
  tm_polygons(col="holc_grade", palette = c("green", "blue", "yellow", "red", "black"),
              popup.vars=c("state", "city", "name", "holc_id")) +
  tm_shape(not_empty, bbox=st_bbox(not_empty[not_empty$city=="Seattle",])) +
  tm_text("holc_id")
# this produced a map similar to those created above with ggplot and tmap with Seattle data subset.
```

Although tmap clearly provided me with a warning, I conveniently disregarded it, and it still output a map --  but an incorrect map.  I'm not sure if this is a bug or not, but I wanted to share this in case others see a similar warning, as the warning probably shouldn't be ignored.

My apologies if this is obvious to tmap experts.

**Comment by mtennekes** [comment]
A bit late, but in tmap4 this is not an issue anymore:


```{r}
library(sf)

sf_use_s2(FALSE)

holc_sf <- st_read("~/Downloads/mappinginequality.json") |> 
	st_make_valid() |> 
	st_crop(tmaptools::bb("Elliott Bay", ext = 10))

tm_shape(holc_sf) +
	tm_polygons(fill = "label") +
	tm_text("label")
```

![Screenshot 2024-12-27 at 21 52 46](https://github.com/user-attachments/assets/f8322521-40a0-4e97-9ecb-f277078c8ede)

Hopefully still relevant @edmundseto If you have any further questions please let us know!
