### ISSUE TITLE
Linetype of legend entities not correct

### ISSUE THREAD

**Issue by Robinlovelace** [r-tmap/tmap#672]
I'm not 100% sure this is a bug, and confident it will be fixed in v4.0.0 if it is, but thought it worth reporting my experience:

```r
zone_cents = st_centroid(zones_od)
zone_cents_rail = zone_cents[desire_rail, ]
bb = tmaptools::bb(desire_rail, ext = 1.1)
desire_rail_plot = rbind(
  st_sf(data.frame(Geometry = "Desire line (original)"), geometry = desire_rail$geometry),
  st_sf(data.frame(Geometry = "Leg 1 (origin to station)"), geometry = desire_rail$leg_orig),
  st_sf(data.frame(Geometry = "Leg 2 (station to station)"), geometry = desire_rail$leg_via),
  st_sf(data.frame(Geometry = "Leg 3 (station to destination)"), geometry = desire_rail$leg_dest)
) 
desire_rail_plot = desire_rail_plot |> 
  mutate(lty = case_when(Geometry == "Desire line (original)" ~ 2, TRUE ~ 1))
# tmaptools::palette_explorer()
tm_shape(desire_rail_plot, bbox = bb) +
  tm_lines(col = "Geometry", palette = "Set2", lty = desire_rail_plot$lty) +
  tm_shape(bristol_stations) + tm_dots(col = "red") +
  tm_shape(zone_cents_rail) + tm_dots(col = "black")
```

Result, the lty values are not right, only the original desire lines are dotted in the map but not in the legend:

![image](https://user-images.githubusercontent.com/1825120/187092197-7180a98b-9951-4748-9541-8f2636bec757.png)

It seems that because the first 3 values of the `lty` column/vector are 2, the first 3 legend entries are dashed. Full reprex in commit below.

**Comment by mtennekes** [comment]
I'm surprised that it renders something without throwing an error :-)) `lty` isn't a visual variable in V3, so it shouldn't be allowed to specify more than 1 value. 

In V4, things are much better:

```r
tm_shape(desire_rail_plot, bbox = bb) +
  tm_lines(
    col = "Geometry", 
    col.scale = tm_scale_categorical(values = "brewer.set2"), 
    lty = "Geometry", 
    lty.scale = tm_scale_categorical(values = c("dashed", "solid"), 
    lty.legend = tm_legend_combine("col"))
```

The code is a bit longer here and there, but I hope you see the benefits. I haven't tested this code btw
