### ISSUE TITLE
Maps arranged in grid don't align

### ISSUE THREAD

**Issue by jflowernet** [r-tmap/tmap#674]
Hi,
I'm trying to arrange 2 maps and a legend in a grid, as shown below. I've tried using packages `grid`, `gridExtra` and `cowplot` as demonstrated in #338 but I have a problem because I want the top edges of the maps to align and the legend to be right justified. The reprex illustrates the issue; I want the World map and Africa map to be aligned along their top edge, and the legend right aligned within its cell. The `just = ` arguments in `viewport` don't do anything.

``` r
library(tmap)

data(World)

#a world map
world_map <- tm_shape(World) +
  tm_borders()

#africa only
africa <- World |>
  dplyr::filter(continent == "Africa")

africa_map <- tm_shape(africa) +
  tm_fill(col = "income_grp", legend.show = FALSE)

#legend for Africa map
africa_map_legend <- tm_shape(africa) +
  tm_fill(col = "income_grp") +
  tm_layout(legend.only = TRUE)


#1: arrange maps and legend using grid package
library(grid)

grid.newpage()

pushViewport(viewport(layout = grid.layout(nrow = 2, ncol = 2)))

print(world_map, vp = viewport(layout.pos.row = 1, layout.pos.col = 1))
#NOTE: just = arguments do not seem to change the layout. Including to illustrate how the alignment should be
print(africa_map_legend, vp = viewport(layout.pos.row = 2, layout.pos.col = 1, just = "right"))
print(africa_map, vp = viewport(layout.pos.col = 2, just = "top"))
```

![](https://i.imgur.com/Pyefe2C.png)

``` r

#2: arrange maps and legend using gridExtra
library(gridExtra)

africa_map_grob <- tmap_grob(africa_map)
#> Note that the aspect ratio for which the grob has been generated is 1.4
```

``` r
africa_legend_grob <- tmap_grob(africa_map_legend)
#> Note that the aspect ratio for which the grob has been generated is 1.4
```

``` r
world_map_grob <- tmap_grob(world_map)
#> Note that the aspect ratio for which the grob has been generated is 1.4
```

``` r

grid.arrange(arrangeGrob(world_map_grob, africa_legend_grob, ncol = 1), africa_map_grob, ncol = 2)
```

![](https://i.imgur.com/hcEhW0w.png)

``` r
#another method:
grid.arrange(world_map_grob, africa_legend_grob, africa_map_grob, layout_matrix = cbind(c(1,2), c(3,3)))
```

![](https://i.imgur.com/3PdN6Q8.png)

``` r

#3: arrange maps and legend using cowplot package
library(cowplot)

p1 <- plot_grid(world_map_grob, africa_legend_grob, ncol = 1)

plot_grid(p1, africa_map_grob, ncol = 2)
```

![](https://i.imgur.com/llqjclt.png)

<sup>Created on 2022-09-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mtennekes** [comment]
Please look at
1. the aspect ratio of device (or grid layout cell)
2. the aspect ratio of the shape, and
3. and the outer.margins

Which are related. Most likely Africa will have extra top and bottom outer margins because the aspect ratio of grid layout cell is lower (meaning more 'portraity') than the shape of Africa.

Run `tmap_design_mode()` and then your code to see these extra outer margins (which are in green). 
To solve it, you could either change the column widths, or change the aspect ratio of the overall device. It's a bit trial-and-error.

**Comment by jflowernet** [comment]
Apologies for not replying - thank you for the options @mtennekes, very much appreciated, and thanks for closing this @Nowosad !
