### ISSUE TITLE
Error: Fill argument neither colors nor valid variable name(s)

### ISSUE THREAD

**Issue by novalabdl** [r-tmap/tmap#675]
Why this eror coming up when i run this code:
# show result in map # 

legend_title = expression("Fixed: Local R2")
map_fbgwr1 = tm_shape(Krucil_shp1, bbox = bbox_new)+
  tm_fill(col = "fmb__localR2", title = legend_title, palette = magma(256), style = "cont")+
  tm_borders(col = "white", lwd= .1)+
  tm_compass(type = "arrow", position = c("left","top"), size = 3) +
  tm_scale_bar(breaks = c(0,1,2), text.size = 0.7, position = c("left","bottom"))+
  tm_layout(bg.color = "white") 
map_fbgwr1+tm_shape(Krucil_shp1)+
  tm_borders(col = "blue", lwd = .5)
  
  The code before this error
  
  # attach data #

attach(Krucil_shp1)

modeling OLS 

ex1<-Indeks~Dimensi_kesehatan+Dimensi_pendidikan+Dimensi_Std_Hidup
model1<-lm(formula = ex1, data = Krucil_shp1)

 result OLS 
summary(model1)

 score VIF 
vif(model1)

 res map 

Krucil_shp1$res_kruc<-residuals(model1)
legend_title = expression("Residual OLS")
map_krucil = tm_shape(Krucil_shp1, bbox = bbox_new)+
  tm_fill(col = "res_kruc", title = legend_title, palette = magma(256), style = "cont")+
  tm_borders(col = "white", lwd= .1)+
  tm_compass(type = "arrow", position = c("left","top"), size = 3) +
  tm_scale_bar(breaks = c(0,1,2), text.size = 0.7, position = c("left","bottom"))+
  tm_layout(bg.color = "white") 
map_krucil + tm_shape(Batas_desa) +
  tm_borders(col = "white", lwd = .2)

 Fixed Bandwith 

fbw<-gwr.sel(ex1,
             data = Krucil_shp1,
             coords = cbind(e,s),
             longlat = TRUE,
             adapt = FALSE,
             gweight = gwr.Gauss,
             verbose = FALSE)
fbw

 fit gwr based on fixed badnwidth 

fb_GWR<-gwr(ex1,
            data = Krucil_shp1,
            coords = cbind(e,s),
            longlat = TRUE,
            bandwidth = fbw,
            gweight = gwr.Gauss,
            hatmatrix = TRUE,
            se.fit = TRUE)
fb_GWR

 data frame for output gwr 

fb_gwr_out<-as.data.frame(fb_GWR$SDF)
Krucil_shp1$fmb_localR2<-fb_gwr_out$localR2

**Comment by Nowosad** [comment]
I am guessing, but have you tried to use `"fmb_localR2"` instead of `"fmb__localR2"` in `tm_fill()`?

**Comment by novalabdl** [comment]
> I am guessing, but have you tried to use `"fmb_localR2"` instead of `"fmb__localR2"` in `tm_fill()`?

Thank you! problem solved, small mistakes make me depresses,LOL
