### ISSUE TITLE
Stars Package Error When Downloading Tmap

### ISSUE THREAD

**Issue by tshirazi99** [r-tmap/tmap#676]
Hi! 

I have been having trouble installing tmap, and I believe it has something to do with the "stars" package.  This is the error I get: 

```
Error: package or namespace load failed for ‘tmap’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stars’
In addition: Warning message:
package ‘tmap’ was built under R version 4.0.5 
```

I have tried installing and uninstalling the "stars" package by running `install.packages("stars")`, and I get the following error: 

Warning in install.packages :
  installation of package ‘stars’ had non-zero exit status

**Comment by Robinlovelace** [comment]
This is an issue with the {stars} package. You can see installation instructions and, if you have carefully followed them for your OS (Mac has some specific needs), you could consider opening an issue in the issue tracker there: https://github.com/r-spatial/stars/

It may be worth updating your version of R to the latest version also. Good luck!
