### ISSUE TITLE
tmap does not include Barbados and other Caribbean islands

### ISSUE THREAD

**Issue by paulapereda** [r-tmap/tmap#677]
tmap does not include Barbados and other Caribbean islands.

**Comment by Robinlovelace** [comment]
Hi @paulapereda I don't think this is a {tmap} package issue but about the input dataset, which may be deliberately simplified. Out of interested have you tried the `world` dataset in {spData}? May have the same issue..

**Comment by Nowosad** [comment]
{tmap} uses spatial data from https://www.naturalearthdata.com/. If you need to download this data (also in a higher resolution/ more detailed version), you can use the rnaturalearth package -- https://cran.r-project.org/web/packages/rnaturalearth/index.html
