### ISSUE TITLE
No expressions in legend title

### ISSUE THREAD

**Issue by itati01** [r-tmap/tmap#678]
Hi,
may be this issue is related to #55 and #587. It would be nice to have expressions for legend titles (i.e. for units). Using expressions instead of strings currently results in
```
Error in rep(if (!is.ena(g[[aname("title", xname)]])[1]) { : 
  attempt to replicate an object of type 'language'
In addition: Warning message:
In is.na(x) : is.na() applied to non-(list or vector) of type 'language'
```
Code to reproduce:
```
library(tmap)
data(World)
tm_shape(World) +
  tm_polygons(col="HPI",
    # error
    title=bquote("dummy, "~kg~ha^{-1})
   # works 
   # title="dummy, kg/ha"
)
```
Or is there another way to achieve this?
Thanks!

P.S. I am using tm_raster().

**Comment by mtennekes** [comment]
Apologies for the delay. Yes that would indeed be a nice feature, although due to lack of time it is not high on my priority list. 
I am not familiar with `bquote`, but as a workaround you can probably use the function `expression` as illustrated in the example of `?tmaptools::calc_densities`.

**Comment by itati01** [comment]
Thanks. Good to know the alternative approach with `expression`.
