### ISSUE TITLE
display labels outside of plot canvas

### ISSUE THREAD

**Issue by mauritsvzb** [r-tmap/tmap#679]
I have a tmap plot and would like to add a label to it. I know how to plot a label inside the plot canvas of the map:

```
predictmap_ti <-
    tm_basemap("Esri.WorldImagery") +
    tm_shape(raster_ti) +
    tm_raster("layer", 
              palette="YlOrRd", 
              legend.show = FALSE,
              title = "Relative selection", 
              style = "fixed", 
              breaks = c(0, .10, .20, .30, .40, .50, .60, .70, .80, .90, 1),
              labels = c("0.0 - 0.1","0.1 - 0.2", "0.2 - 0.3","0.3 - 0.4","0.4 - 0.5",
                         "0.5 - 0.6", "0.6 - 0.7","0.7 - 0.8", "0.8 - 0.9", "0.9 - 1.0")) +
    tm_shape(land[land@data$land == "land",]) +
    tm_fill("black") +
    tm_layout(outer.margins = c(.1,.1,.1,.1),
          legend.bg.color = "white", 
          legend.position = c("left", "top"), 
          legend.width = 0.35, 
          legend.height = 1, 
          legend.outside = TRUE,
          fontfamily = "Times") + 
   tm_credits("A", position = c("LEFT","TOP"), size = 1.5)
)
```

But for consistency purposes with other figures for my MS, i would like to have the label shown outside the plot canvas. How could i achieve this? I tried adjusting the `position` parameter in the` tm_credits()`, but this seems to only move around the label within the canvas, and any extreme value would make the label disappear, rather than cross the border. Any suggestions ?

`predictmap_ti + tm_credits("A", position = c(0.95,0.9), size = 1.5, fontfamily = "Times")`

**Comment by Nowosad** [comment]
@mauritsvzb how about using `tm_layout(title = "A")`?

**Comment by mauritsvzb** [comment]
This seems to still plot a label inside the plotting canvas.

**Comment by Nowosad** [comment]
Sorry, I meant `tm_layout(main.title = "A")`.

**Comment by mauritsvzb** [comment]
Sweet works perfectly! And how would i increase the vertical white space between the label and plot?

**Comment by Nowosad** [comment]
I do not thing this is possible.

**Comment by mauritsvzb** [comment]
Ok, i realised i could try to pretend the main title consists of multiple lines. So what i tried is 

```
tm_layout(main.title = "A
                          ")
```

and it worked.
