### ISSUE TITLE
fontface does not work in `tm_text()`

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#686]
``` r
library(tmap)
data(World)
africa = subset(World, continent == "Africa")

tm_shape(africa) +
  tm_text("name", size = "AREA")
```

![](https://i.imgur.com/zeHOZDA.png)

``` r

tm_shape(africa) +
  tm_text("name", size = "AREA",
          fontface = "italic")
```

![](https://i.imgur.com/uv1QEmT.png)

``` r

tm_shape(africa) +
  tm_text("name", size = "AREA",
          fontface = "bold")
```

![](https://i.imgur.com/HPAE3NI.png)

``` r

tm_shape(africa) +
  tm_text("name", size = "AREA",
          fontface = "bold.italic") +
  tm_credits("OH NO")
```

![](https://i.imgur.com/MrEEjGs.png)

``` r

tm_shape(africa) +
  tm_text("name", size = "AREA",
          fontface = "bold.italic") +
  tm_credits("OH YES", fontface = "bold.italic")
```

![](https://i.imgur.com/FPX1Cqf.png)

<sup>Created on 2022-12-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mtennekes** [comment]
It's working in v4 :-)
Fixing it in v3 has low priority, but PRs are welcome

**Comment by Nowosad** [comment]
Hi @mtennekes -- I tried to look at a place in code to fix it, but I failed. Can you point me to the place where tm_text's features are defined?

**Comment by mtennekes** [comment]
https://github.com/r-tmap/tmap/blob/master/R/process_text.R
line 98, 98 should take over the global options

**Comment by Nowosad** [comment]
It is fixed in the development version of tmap (see the v4 branch).
