### ISSUE TITLE
tm_bubbles size and color - only one legend shows.  

### ISSUE THREAD

**Issue by loureynolds** [r-tmap/tmap#690]
I will post a reproducible example if needed - but I can't seem to be able to show both legends (for color AND size) when tm_bubble refers to both - in this case color indicates the type of site and the size indicates alumnium concentration.  I am fine with two different legends.   
stssub is an sf object.  The map produces fine (and I really prefer to use tmap because I like the map), but only the legend for color (Sitetype) shows. 
 
al<- stssub %>%
  filter(Analyte=="Aluminum, Total") %>% 
   tm_shape()+
  tm_bubbles(size="Result",col="Sitetype",  alpha=0.5, title.col="Site Type")
al

**Comment by mtennekes** [comment]
I assume you use 'plot' mode? (Bubble legend is not implemented yet for view mode)
If so, a reproducible example will help.
