### ISSUE TITLE
How can I install tmap v4?

### ISSUE THREAD

**Issue by zengyl1992** [r-tmap/tmap#701]
Thank you for great tmap package! But how can I install tmapV4? 
I try the latest development version via "install_github("r-tmap/tmap")",  but it is still tmapv3.3.

**Comment by Nowosad** [comment]
Hi @zengyl1992 the tmap v4 is still a work in progress, missing various features and functions. 
However, if you are interested in testing it, you may download it with `install_github("r-tmap/tmap@v4")`

**Comment by zengyl1992** [comment]
Many thanks to you!

**Comment by mtennekes** [comment]
You're welcome @zengyl1992 Let us know if you have suggestions or find any bugs.

**Comment by Yingjie4Science** [comment]
Installation error on Windows

library(remotes)
install_github("r-tmap/tmap@v4")


installing *source* package 'tmap' ...
   ** using staged installation
   ** R
   Error in parse(outFile) : 
     C:/Users/pc/AppData/Local/Temp/RtmpgDQJyc/Rbuild76dc58657f56/tmap/R/tmapGridInit.R:171:34: unexpected '>'
   170:                         
   171:                         gt = gt |>
                                         ^
   ERROR: unable to collate and parse R files for package 'tmap'

**Comment by Nowosad** [comment]
Hi @Yingjie4Science what's your R version? Is it >4.1?

**Comment by Yingjie4Science** [comment]
Hi @Nowosad  No, I have not updated my R, it is "R version 3.6.1 (2019-07-05)"

**Comment by Nowosad** [comment]
tmap4 uses the pipe operator in its code that was added to R in version 4.1 (https://www.infoworld.com/article/3621369/use-the-new-r-pipe-built-into-r-41.html)
