### ISSUE TITLE
Default behavior for numeric variables in tm_text

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#709]
My expectation would be that `tm_text()` would print the provided values; so when I provide a character variable, it will print these characters, and when I provide a numeric variable, it will print these numbers. Unfortunately, this is not the case in tmap v4:

``` r
library(terra)
library(sf)
library(tmap)
tmap_mode("plot")
set.seed(2021-09-09)
small_ras = rast(matrix(1:16, 4, 4, byrow = TRUE))
crs(small_ras) = "EPSG:4326"
polys = st_as_sf(as.polygons(small_ras, na.rm = FALSE))

# replaces values with letters
tm_shape(polys) +
  tm_borders() +
  tm_text(text = "lyr.1")
```

![](https://i.imgur.com/mzIJVui.png)

``` r

# works as expected
polys$lyr1 = as.character(polys$lyr.1)
tm_shape(polys) +
  tm_borders() +
  tm_text(text = "lyr1")
```

![](https://i.imgur.com/zCCQ6J9.png)

<sup>Created on 2023-03-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mtennekes** [comment]
Fixed. Some tmap4 education:


The default scales are defined per visual variable and per data class. See  https://github.com/r-tmap/tmap/blob/v4/R/tmap_options.R#L108-L118

(Detail: the data classes do not exactly correspond with classes in R. Details upon request)
I've changed the class 'num' of visual variable text, from "categorical" to "asis", which makes more sense indeed.

Have you noticed/seen the function I()? This will work in your example, even without the last fix (#709):

```r
tm_shape(polys) +
    tm_borders() +
    tm_text(text = I("lyr.1"))
```

It takes the values as is, so using the tm_scale_asis`.
