### ISSUE TITLE
view mode: points not sharp when WebGL enabled (upstream to `leafgl`)

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#719]
With `tm_options(use.WebGL = T)` the `leafgl` package is used for fast rendering of polygons, lines and points (in view mode). However, points look not as sharp: 

```r
tm_shape(metro) + tm_symbols(fill = "pop2020", size = .5) + 
  tm_options(use.WebGL = TRUE)
```

<img alt="Screenshot 2023-03-28 at 11 17 50" src="https://user-images.githubusercontent.com/2444081/228190140-12ea60ac-e332-4425-a324-6710cf490deb.png">

```r
tm_shape(metro) + tm_symbols(fill = "pop2020", size = .5) + 
  tm_options(use.WebGL = FALSE)
```

<img alt="Screenshot 2023-03-28 at 11 18 05" src="https://user-images.githubusercontent.com/2444081/228190121-585cdb86-2ac0-4bac-a71b-af7b3dae5d08.png">

The second one looks sharper (that is, the borders of the points), at least on a good monitor (if you cannot see it, click on the images and zoom in).

Apart from that, the border colors cannot be set with leafgl. Is that by design or a bug?

@tim-salabim you are probably the one to ask;-)

**Comment by tim-salabim** [comment]
Is this on main or the v4 branch?

**Comment by tim-salabim** [comment]
Ok, I'll have a look. I fear there's nothing much we can do, as these circle borders are drawn as part of the shaders used in Leafelt.glify
