### ISSUE TITLE
tm_text not responding to text style, rotation and font change using tmap package in R studio on Windows

### ISSUE THREAD

**Issue by aonojeghuo** [r-tmap/tmap#720]
I've tried a few examples I've seen online to label polygons. tm_text in tmap is not responding to changes in text names beyond sans, serif and plain and wont change the fontface to bold or bold italic.I am also having chalenges rotating text to avoid clutter. Do I need another library apart from tmap for this?

   tm_shape(raster)+tm_raster()+tm_shape(poly)+tm_polygon()  + tm_text("adm1_name", size = 0.6,xmod=-0.02,ymod =0.4, fontfamily= "sans",fontface="bold.italic", just="center", auto.placement =F ,col = "gray10", along.lines=T)

In the example below, a font family called Keras was used but this isn't working in my own environment. Is there a way to rotate text by about 40 degrees for example? I have also had challenges with breaking labels e.g South Carolina with South and Carolina on 2 different lines (probably specifying breaking after spaces in a polygon name).
[
https://stackoverflow.com/questions/61133963/how-to-tweak-the-text-angle-in-some-counties-with-tmap ](url)

**Comment by Nowosad** [comment]
Some improvements to tm_text are expected, but cannot promise anything.
