### ISSUE TITLE
Consider renaming `tm_scale_bar()`

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#722]
Hi @mtennekes -- I've been thinking -- would it make sense to rename (in a long term) `tm_scale_bar()` to `tm_scalebar()` to remove any confusion with the rest of the `tm_scale_` functions?

**Comment by mtennekes** [comment]
Yes, good point! We can safely do that, with `tm_scale_bar()` still co-existing and throwing deprecation warnings.
