### ISSUE TITLE
tm_legend vs tm_scale question tmap4

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#725]
Hi @mtennekes -- I've been working on tmap4 updates in the mapping chapter of the geocompr book. It made me think about some (ideological) overlap of `tm_scale()` and `tm_legend()`. E.g., changes in `tm_scale_intervals()` (e.g., `breaks`) also impact the legend. Thus, why do we need to separate functions/arguments? What was your motivation behind it?

**Comment by Nowosad** [comment]
Regarding histograms: I would say that a separate argument (e.g., `fill.chart()`) is needed here. I assume most people want to add a histogram along the legend (and not to replace it)
.

**Comment by mtennekes** [comment]
Yes, it makes sense to add `x.chart` for each visual variable `x`. Then the code would be e.g.:

```r
tm_shape(World) +
  tm_polygons(
    fill = "economy", 
    fill.scale = tm_scale_categorical(values = "Oranges"), 
    fill.chart = tm_histogram(position = c("left", "bottom"))
```

**Comment by Nowosad** [comment]
Looks good.
