### ISSUE TITLE
Pointer issues in facets/interactive mode

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#726]
Note that the pointer (red circle) is locked on 0,0 in the top map, and "hides" behind polygons in the bottom map:

```r
library(spData)
library(tmap)
tmap_mode("view")
world_coffee = left_join(world, coffee_data, by = "name_long")
facets = c("coffee_production_2016", "coffee_production_2017")
tm_shape(world_coffee) + tm_polygons(facets) + 
  tm_facets(nrow = 1, sync = TRUE)
```
![2023-04-13_08-57](https://user-images.githubusercontent.com/3457131/231678747-5c7e508f-458f-4ee7-a409-3bd88396ed71.png)

**Comment by mtennekes** [comment]
Probably an issue with `leafsync` (@tim-salabim), or further upstream.

The same issue:

```r
library(mapview)
library(leafsync)

sync(
  mapview(world_coffee, z = facets[1], alpha.regions = 1),
  mapview(world_coffee, z = facets[2], alpha.regions = 1)) 
``` 
![Screenshot 2023-05-08 at 16 52 54](https://user-images.githubusercontent.com/2444081/236857246-cbd64aa2-a9a9-4586-a170-f0074d707216.png)

**Comment by tim-salabim** [comment]
It' a "feature" of the upstream package. Though I haven't checked for updates in a while...
