### ISSUE TITLE
tm_scalebar bg.color argument does not work

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#729]
``` r
library(tmap)
tmap_mode("plot")
#> tmap mode set to 'plot'
data(NLD_prov)  

tm_shape(NLD_prov) +
  tm_fill("name") +
  tm_scalebar(bg.color = "black")
```

![](https://i.imgur.com/TkdxjAo.png)

**Comment by mtennekes** [comment]
`bg.color` is a standard argument for all map components (legends, compass, scalebar, etc). However, it only is used when there is a frame:

```r
tm_shape(NLD_prov) +
	tm_fill("name") +
	tm_scalebar(bg.color = "gold", frame = T)
```

![image](https://user-images.githubusercontent.com/2444081/236850404-7a0d1e44-b2ab-4e2d-aa21-1dbb87d68915.png)

If you only want to replace the white bar in your scalebar example, you have to use `color.light`:

```r
tm_shape(NLD_prov) +
	tm_fill("name") +
	tm_scalebar(color.dark = "yellow", color.light = "purple", width = 0.8)
```

![image](https://user-images.githubusercontent.com/2444081/236850701-dde0d1f3-0c4a-425e-b6d0-241d6d00a5bc.png)

**Comment by mtennekes** [comment]
Fixed
