### ISSUE TITLE
exporting maps in tmap 4?

### ISSUE THREAD

**Issue by GuiAlDuS** [r-tmap/tmap#732]
I've been using tmap 4 for several weeks and I really enjoy and find very useful all the new improvements made over v3.
It seems the export (_tmap_save()_) function is still not implemented in v4 (?) but do you know if there is any workaround to export the maps into images (other than copy-paste the screen)?

Thanks for your amazing job making this library.

**Comment by Nowosad** [comment]
@GuiAlDuS you can use R graphic devices, e.g.:

```r
png(file = "myplot.png")
my_tmap_object
dev.off()
```

**Comment by mtennekes** [comment]
tmap_save is implemented now in v4. Please check and reopen if there are any issues
