### ISSUE TITLE
Problems in working with IRkernel

### ISSUE THREAD

**Issue by HPDell** [r-tmap/tmap#736]
R Version: 4.2.2
Package Version: 3.3-3
Platform: macOS 13 (M2)

When using **tmap** and **IRkernel** together in a Jupyter Notebook, I found that **tmap** cannot recogonize the correct plot width and height. For example, to create a map of provinces in China, when I set `repr.plot.width=7` and `repr.plot.height=7` (by default), the following map is created.

![image](https://github.com/r-tmap/tmap/assets/17842185/4599eff6-13e9-4f91-965b-1d4a1b2e4a30)

There are much whitespaces. However, when I change `repr.plot.width` to 9 to elimate withespace, the following figure is created

![image](https://github.com/r-tmap/tmap/assets/17842185/ca916d64-6cfe-4551-9d32-ffdcb7aa5cab)

It seems that **tmap** still create a map on a square canvas and then it is put in the center of the repr area. 

Are there any options can overcome this problem?

**Comment by Nowosad** [comment]
Sadly, I do not know IRkernel enough to try to reproduce the issue. You may try to use the current development version (as it has many changes), but I do not have any better advises.
