### ISSUE TITLE
Warnings about legacy package dependencies

### ISSUE THREAD

**Issue by dmkaplan2000** [r-tmap/tmap#738]
Hi,

I noticed that recent versions of `tmap` warn on load that there are dependencies on legacy packages `sp`, `rgdal`, etc. that are going away. I just wanted to make sure that these issues aren't going to impact core `tmap` functionality, i.e., that the package is going to stick around even if these dependencies disappear. I typically use `tmap` with `sf` and `stars`, so I wouldn't expect to be truly relying on any of these dependencies.

Thanks,
David

**Comment by dmkaplan2000** [comment]
Cool, thanks for letting me know.

**Comment by rsbivand** [comment]
For example:
```
library(tools)
pdb <- available.packages()
o1 <- package_dependencies(packages = c("tmap"), pdb, which = "strong", recursive = FALSE, reverse = FALSE)
"sp" %in% o1
# [1] FALSE
o2 <- package_dependencies(packages = o1$tmap, pdb, which = "strong", recursive = FALSE, reverse = FALSE)
sapply(o2, function(x) "sp" %in% x)
#      methods    tmaptools           sf        stars        units         grid 
#        FALSE        FALSE        FALSE        FALSE        FALSE        FALSE 
# RColorBrewer  viridisLite     classInt    htmltools  htmlwidgets  widgetframe 
#        FALSE        FALSE        FALSE        FALSE        FALSE        FALSE 
#      leaflet     leafsync       leafem        stats        abind        rlang 
#         TRUE        FALSE        FALSE        FALSE        FALSE        FALSE 
#        utils 
#       FALSE 
```
so it looks like `leaflet`.

**Comment by mtennekes** [comment]
Thanks @rsbivand I saw that you already issued this https://github.com/rstudio/leaflet/issues/833
