### ISSUE TITLE
sf objects with numerical column names cause Error: lwd argument of tm_lines is not a numeric variable

### ISSUE THREAD

**Issue by itati01** [r-tmap/tmap#756]
Hi,

I want to plot maps from certain attributes of a sf object. Before I join the values, I can successfully create a map showing some categories. After the join, I obtain the error message : `Error: lwd argument of tm_lines is not a numeric variable` - even with the original category column. It seems that this is caused by "special" column names. I use tmap 3.3.3 from CRAN with R 4.1.3. 

The sf object contains lines and polygons. The map should show a single legend for which I use this (shortened) function:
```
plot_map <- function(df,
                     col=NA,   # column name
                     title=NA, # legend title
                     palette=NULL, # palette
                     line.width=1,    # line width
                     colorNA=NA, # color missing values
                     compass.type=NA, # compass type
) {  
  map <- tm_shape(df) + 
      tm_lines(col=col, title.col=title, palette=palette, colorNA=colorNA, lwd=line.width, legend.col.show=F) +
    tm_shape(df) +
    tm_fill(col=col, title=title, palette=palette, colorNA=colorNA, legend.show=F) +
    tm_add_legend(type="fill", labels=names(palette), col=palette, title=title) +
    tm_compass(type=compass.type, position=c(0.98, 0.25), just="right") +
    tm_scale_bar(position=c(0.98, 0.025), just="right") +
    tm_layout(legend.position=c(0.02, 0.025))
  return(map)
}
```

Function calls with dummy data
```
library(sf)
library(tmap)
library(dplyr)

# a dataset with different categories and geometries
pol <- st_sfc(st_polygon(list(cbind(c(0,3,3,0,0), c(0,0,3,3,0)))))
h <- st_sf(WB_CAT="CW", pol)
test <- bind_rows(h, h %>% st_cast("MULTILINESTRING"), h %>% mutate(WB_CAT="RW"))

# 1 is seemingly invalid and is changed to X1
test.data <- data.frame(WB_CAT=c("CW", "TW", "RW"), `1`=c(1, 0, NA))
# my table is a tibble with a real column name `1`
# however, the error also occurs without as_tibble()
test.data.1 <- test.data %>% as_tibble() %>% rename(`1`=X1)
# the palette for the categories
pal <- c("CW"="#00C0C0", "TW"="#20F0B0", "RW"="#0030E0", "LW"="#20B0F0", "TE"="#00E030")

# before join: works
plot_map(test, col="WB_CAT", title="WB category", palette=pal, colorNA="#f0f0f0", compass.type="rose")
# after join: does not work
plot_map(test %>% left_join(test.data.1 %>% select(WB_CAT, `1`), by="WB_CAT"),
         col="WB_CAT", title="WB category", palette=pal, colorNA="#f0f0f0", compass.type="rose")
# after join: does work
plot_map(test %>% left_join(test.data %>% select(WB_CAT, X1), by="WB_CAT"),
         col="WB_CAT", title="WB category", palette=pal, colorNA="#f0f0f0", compass.type="rose")
```

**Comment by mtennekes** [comment]
Hi,

Don't know about the CRAN version of tmap (I have very limited time so have to spend wisely).
However, the code works in tmap4! Though I'm not sure if the produced maps are want you wanted to achieve. I only see a rectangle, but no attributes. The scalebar is not drawn because (so far) it required a CRS. Why the map compass isn't there, I don't know.  Strictly speaking it also requires a CRS, but I assume that I have put north as default.

Please check

**Comment by itati01** [comment]
hi,
thanks for the reply. The function is for the original dataset not this simple example which just should serve as an example. As the workaround is simple (just use column names like X1 instead of 1) and the problem does not occur in tmap4, feel free to close this issue.
