### ISSUE TITLE
No `tm_scale_bar()` in v4

### ISSUE THREAD

**Issue by Robinlovelace** [r-tmap/tmap#769]
It's a super useful function. Just about to install v3 again after hitting this.

```
Error in `tm_scale_bar()`:
! could not find function "tm_scale_bar"
```

**Comment by Nowosad** [comment]
@Robinlovelace -- it is renamed to `tm_scalebar()`
@mtennekes maybe it worth be keeping both (at least for some time), and maybe add a warning then using the `_` version?

**Comment by Robinlovelace** [comment]
What's the benefit of changing it? Seems purely cosmetic and will just mean old code will be less likely to run or generate new warnings.

**Comment by Nowosad** [comment]
There are a bunch of new `tm_scale_*` functions that are used for a totally different purpose from `tm_scale_bar`. See https://r.geocompx.org/adv-map#scales

**Comment by Robinlovelace** [comment]
I see the point: the benefit of changing is that all `tm_scale*` functions refer to scales, continuous, catagorical etc. Are you sure the benefit outweighs the cons associated with this breaking change?

:+1: to keeping both names for the same function, that would fix it.

**Comment by Nowosad** [comment]
I think keeping both names for a some time (a couple of years even) is fine. But the old name should be depreciated at the end.

**Comment by mtennekes** [comment]
Already did, but forgot to export `tm_scale_bar` :-)

**Comment by Robinlovelace** [comment]
Awesome. One by one the the issues are falling like flies. tmap v4 here we come :rocket:
