### ISSUE TITLE
Skipping empty tm_shape polygons or variables in a loop of several polygons and plotting just sub layers with data

### ISSUE THREAD

**Issue by ar-onos** [r-tmap/tmap#790]
I am trying to plot maps using a loop but want the loop to plot all tm_shape variables with data and skip the components without data. Here is a sample:

    Rivers <- ne_download(scale = "large", type = 'rivers_lake_centerlines', category = 'physical', returnclass = "sf")
    

    library(rnaturalearth)
    library(sf)
    library(tmap)
    for(i in unique(NLD_muni$province)) {
    NLDi <- NLD[NLD_muni$province %in% i,]

    Shp_Rivers2 <- st_intersection(Rivers, NLDi )
    tm_shape(NLD_muni[NLD_muni$province %in% i , ]) +  tm_shape(NLD_muni) +
    tm_polygons(col = c("population", "pop_0_14", "pop_15_24",
                "pop_25_44")) +  tm_shape(NLD_muni) + tm_polygons("pop_men") +  tm_shape(Shp_Rivers2) +tm_lines(col= "red") +
    tm_facets(nrow = 2, sync = TRUE) 
    }

In the example above, how can I plot the population data defined in the first tm_shape(NLD_muni[NLD_muni$province %in% i , ]) and skip the next tm_shape(pop_men) if the subset for pop_men is empty? If there is data for pop_men, but no data for Shp_Rivers2, how do I plot only population and pop_men but skip the tm_shape(Shp_Rivers2) bit? My loop crashes instead of plotting the layers with data and moving on to the next i polygon in the loop.  Also, if there is no data for NLD_muni[NLD_muni$province %in% i , ] , how do I skip and go to the next province in the List? Is there an if-else for, next syntax that I can use?

My actual sample has a few different shape files e.g. roads, rivers, and lakes where the different tm_shape variables for a polygon of interest are subset from, so some of these subset come up empty if there is no river going through for example.
P.S: This example may not produce any errors and is just to show you the structure of my plot

**Comment by mtennekes** [comment]
I would approach this with something like this:



```r
# inside the loop or function
# say SHP1, SHP2, and SHP3 are potentially empty sf objects, say with polygons, lines and points respectively.

tm = tm_basemap()
if (nrow(SHP1)) tm = tm + tm_shape(SHP1) + tm_polygons()
if (nrow(SHP2)) tm = tm + tm_shape(SHP2) + tm_lines()
if (nrow(SHP3)) tm = tm + tm_shape(SHP3) + tm_dots()

tm
```

Hope it helps.

**Comment by ar-onos** [comment]
Thanks @mtennekes. This worked
