### ISSUE TITLE
Colors for terra's categorical rasters are wrong

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#791]
@mtennekes see the last example:

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE
library(terra)
#> terra 1.7.46
nlcd_path = system.file("raster/nlcd.tif", package = "spDataLarge")

nlcd_stars1 = read_stars(nlcd_path)
plot(nlcd_stars1)
#> downsample set to 1
```

![](https://i.imgur.com/y7Yv7CK.png)

``` r

nlcd_terra = rast(nlcd_path)
plot(nlcd_terra)
```

![](https://i.imgur.com/ggjIcEQ.png)

``` r

nlcd_stars2 = st_as_stars(nlcd_terra)
plot(nlcd_stars2)
#> downsample set to 1
```

![](https://i.imgur.com/sgSWWAr.png)

``` r

library(tmap)
# works well for stars
tm_shape(nlcd_stars1) +
  tm_raster()
```

![](https://i.imgur.com/mQjl8QL.png)

``` r

tm_shape(nlcd_stars2) +
  tm_raster()
```

![](https://i.imgur.com/snvPvGk.png)

``` r

# colors are broken for terra
tm_shape(nlcd_terra) +
  tm_raster()
#> SpatRaster object downsampled to 1126 by 889 cells.
```

![](https://i.imgur.com/B5l9Xxe.png)

<sup>Created on 2023-10-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mtennekes** [comment]
Ok, it's working again.

What confused me/tmap was the following:

```r
terra::cats(nlcd_terra)
[[1]]
  value     levels
1     0       <NA>
2     1      Water
3     2  Developed
4     3     Barren
5     4     Forest
6     5  Shrubland
7     6 Herbaceous
8     7 Cultivated
9     8   Wetlands
```

@rhijmans Can you explain this? Is the 0-value category always the value for missing data? Or can this be different for other `SpatRaster` objects?

**Comment by rhijmans** [comment]
I think it is not uncommon to have 0 or 255 as NA flag; but it could be any value. It is not something that terra enforces or expects. It is just what is in the file:

```
terra::describe(nlcd_path)[63:66]
#[1] "  Categories:"     
#[2] "      0: NA"       
#[3] "      1: Water"    
#[4] "      2: Developed"
```
