### ISSUE TITLE
tmap4: tm_add_legend "lines" type draws boxes

### ISSUE THREAD

**Issue by DOSull** [r-tmap/tmap#792]
I'm giving tmap4 a try early because I teach with it and thought I might use the 30 Days Maps Challenge to figure it out.

When I use `tm_add_legend` to make a legend combining line colour and type in a single legend, it draws boxes, not lines.

**Comment by Nowosad** [comment]
@DOSull could you prepare a short reprex (https://reprex.tidyverse.org/) showing this issue?

**Comment by DOSull** [comment]
Here's some code. I figured out how to use `tm_legend_combine()` to get my desired result (the top legend). Nevertheless, it still seems wrong that a `"lines"` legend added with `tm_add_legend()` draws boxes... (the bottom legend). I haven't styled the legend elements because drawing boxes not a line segment is the issue I am highlighting.

```
lines <- st_read("example.json")

tm_shape(lines) +
  tm_lines(
    col = "Mode",
    col.scale = tm_scale(
      values = "-Set1"),
    lty = "Mode",
    lty.scale = tm_scale(
      values = c("dotted", "solid")),
    lty.legend = tm_legend_combine("col"),
    lwd = 2) +
  tm_add_legend(
    type = "lines",
    labels = c("Boat", "Road"),
    col.values = "-Set1",
    lty.values = c("dotted", "solid"),
    title = "Wrong way")
```
![image](https://github.com/r-tmap/tmap/assets/8213420/cffa92e4-d36f-4a8f-889d-8e2ed12e2395)
[example.json](https://github.com/r-tmap/tmap/files/12874198/example.json)

**Comment by mtennekes** [comment]
Thx! I've take a look today

**Comment by mtennekes** [comment]
Now it's working.
