### ISSUE TITLE
Strange dull "blue" in single category categorical map

### ISSUE THREAD

**Issue by DOSull** [r-tmap/tmap#797]
This one is a little odd, but is still unexpected behaviour. In a single category map, specifying the colour `"blue"` as the only `value` in `tm_scale_categorical` gives not `#0000ff` but what looks very like the blue colour in the ColorBrewer palette Set1. I checked and something similar happens with some other colours, most obviously `"green"`. Here is code:

```{r}
library(tmap)
library(sf)
library(dplyr)

# make two crossed lines minimal sf dataset
lines <- list(
  matrix(c(0, 0, 1, 1), ncol = 2, byrow = TRUE),
  matrix(c(0, 1, 1, 0), ncol = 2, byrow = TRUE)) %>%
  st_multilinestring() %>%
  st_sfc() %>%
  st_sf(crs = 4326) %>%
  st_cast("LINESTRING") %>%
  mutate(Type1 = "thing",
         Type2 = c("entity", "object")) %>%
  mutate(Type1 = as.factor(Type1),
         Type2 = as.factor(Type2))

map1 <- tm_shape(lines) +
  tm_lines(
    col = "Type1",
    col.scale = tm_scale_categorical(
      values = c("blue"),
      levels = c("thing"))) +
  tm_layout(frame = FALSE)

map2 <- tm_shape(lines) +
  tm_lines(col = "blue") +
  tm_add_legend(
    type = "lines",
    values = c("blue"),
    labels = c("thing"),
    title = "Type1") +
  tm_layout(frame = FALSE)

map3 <- tm_shape(lines) +
  tm_lines(
    col = "Type2",
    col.scale = tm_scale_categorical(
      values = c("red", "blue"),
      levels = c("entity", "object"))) +
  tm_layout(frame = FALSE)

map4 <- tm_shape(lines) +
  tm_lines(
    col = "Type2",
    col.scale = tm_scale_categorical(
      values = "Set1")) +
  tm_layout(frame = FALSE)

tmap_arrange(map1, map2, map3, map4, ncol = 2)
```
This gives the following four maps:

![image](https://github.com/r-tmap/tmap/assets/8213420/89e3d503-5df6-4582-9ea3-ee214e5d66b1)

Map 2 (upper right) shows that setting the colour to a single value and using `tm_add_legend` for this use-case works as expected. And Map 3 (lower left) shows that if there is more than one colour in the `values` specification then they are rendered as expected. Map 4 (lower right) suggests that the rogue dull blue colour is from the Set1 palette.

I checked with `tm_fill` and the same thing happens - the code is longer because making boxes involves more code.

I realise this might be an odd use-case, but maps that show only one thing yet have a key/legend are not unknown.

**Comment by mtennekes** [comment]
Thx @DOSull 
Fixed now, please check.

The problem was ambiguity: "blue" is also recognized by cols4all as a palette name (that included the rogue dull blue). This is solved by prioritising the R colors. The palette "blue" can also be specified via cols4all with the full name, e.g. `"tableau_blue"`.

**Comment by DOSull** [comment]
Interesting! Appears to be fixed now - `"green"` also behaves as expected now!
