### ISSUE TITLE
Setting position with numbers does not work

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#799]
``` r
library(spData)
library(tmap)

# works
tm_shape(nz) +
  tm_polygons("Median_income") +
  tm_layout(legend.position = c("left", "bottom"))
```

![](https://i.imgur.com/Z1lTbc2.png)

``` r

# fails
tm_shape(nz) +
  tm_polygons("Median_income") +
  tm_layout(legend.position = c(0.02, 0.02))
#> Error in l$position$type: $ operator is invalid for atomic vectors
```

**Comment by mad-dos-equis** [comment]
I experienced the same issue when trying to set the legend position directly with numeric values in vector c(), which contradicts the documentation. However, if you are looking for a practical workaround in the meantime, I recommend using the tm_pos_in() function and its pos.h and pos.v options within the legend.position() function. From your code above:

`tm_shape(nz) +
  tm_polygons("Median_income") +
  tm_layout(legend.position = tm_pos_in(pos.h = 0.02, pos.v = 0.02))`

**Comment by Nowosad** [comment]
``` r
library(spData)
library(tmap)

# works
tm_shape(nz) +
  tm_polygons("Median_income") +
  tm_layout(legend.position = c("left", "bottom"))
```

![](https://i.imgur.com/O3R5Tes.png)

``` r

# fails
tm_shape(nz) +
  tm_polygons("Median_income") +
  tm_layout(legend.position = c(0.02, 0.2))
```

![](https://i.imgur.com/swLvu0k.png)
