### ISSUE TITLE
How to install v4 without GH account

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#801]
Hi @Nowosad @Robinlovelace 

I'm teaching v4 right now (and demonstrating GH) but the participants cannot install tmap v4 via:

remotes::install_github("r-tmap/tmaptools")
remotes::install_github("r-tmap/tmap")

It throws an "error API rate limit exceed for..."

Do you know if we could change some setting to fix this, or maybe create a public auth_token?

**Comment by mtennekes** [comment]
Solved thanks to one participant and @olivroy putting it on r-universe:

```r
install.packages("tmap", repos = c("https://r-tmap.r-universe.dev", "https://cloud.r-project.org"))
```

**Comment by Nowosad** [comment]
You can use r-universe (https://r-tmap.r-universe.dev/tmap#):

```r
install.packages('tmap', repos = c('https://r-tmap.r-universe.dev', 'https://cloud.r-project.org'))
```

**Comment by Nowosad** [comment]
Too slow;)
