### ISSUE TITLE
Uninformative error message when specifying bbox as vector

### ISSUE THREAD

**Issue by PPaccioretti** [r-tmap/tmap#810]
I'm using the development version. When specifying a bbox as a vector or matrix without crs attribute, I encounter an error message that lacks informative details. This issue makes it challenging to diagnose and resolve the problem.

``` r
library(tmap)
#> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
#> which was just loaded, were retired in October 2023.
#> Please refer to R-spatial evolution reports for details, especially
#> https://r-spatial.org/r/2023/05/15/evolution4.html.
#> It may be desirable to make the sf package available;
#> package maintainers should consider adding sf to Suggests:.
#> 
#> Attaching package: 'tmap'
#> The following object is masked from 'package:datasets':
#> 
#>     rivers

packageVersion('tmap')
#> [1] '3.99.9000'
data(World)
tm_shape(World, bbox = as.vector(sf::st_bbox(World))) + 
  tm_polygons()
#> Error in if (!maybe_longlat(b)) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2023-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thank you for your dedication!!

**Comment by olivroy** [comment]
This example runs without error in 3.3.4, is this wrong?

What would be the correct code ?

**Comment by mtennekes** [comment]
To start with @olivroy's question: these ones are 'correct':

```r
tm_shape(World, bbox = World) + tm_polygons()
tm_shape(World, bbox = sf::st_bbox(World)) + tm_polygons()
```

Under the hood, the specified bbox argument is feed to `sf::st_bbox`, which accepts many formats. However, I cannot cope unnamed numeric vectors well (imho) :

``` r
sf::st_bbox(c(-180, -89, 180, 83))
#> xmin ymin xmax ymax 
#>   NA   NA   NA   NA
sf::st_bbox(c(xmin = -180, ymin = -89, xmax = 180, ymax = 83))
#> xmin ymin xmax ymax 
#> -180  -89  180   83
```

@edzer Why is this? I would expect a warning here, e.g.: "Names have not been specified:, xmin, ymin, xmax and ymax assumed."

**Comment by Nowosad** [comment]
``` r
library(tmap)
packageVersion('tmap')
#> [1] '3.99.9003'

data(World)
tm_shape(World, bbox = as.vector(sf::st_bbox(World))) + 
  tm_polygons()
#> Warning: Current projection unknown. Long lat coordinates (wgs84) assumed.
```

![](https://i.imgur.com/NjhrnLC.png)
