### ISSUE TITLE
Pacific cantered world map

### ISSUE THREAD

**Issue by andrewmaclachlan** [r-tmap/tmap#812]
Sorry if i am missing something obvious, but is there a way to centre the world map on the pacific (or other places) in tmap?

```{r}
tmap_mode("plot")
data(World)

tm_shape(World) +
  tm_polygons("HPI")
```

**Comment by Nowosad** [comment]
@andrewmaclachlan one possible approach is to reproject your data -- see https://r.geocompx.org/reproj-geo-data#fig:laeaproj2

**Comment by Nowosad** [comment]
Also https://github.com/r-spatial/sf/issues/2058#issuecomment-1353379643

**Comment by andrewmaclachlan** [comment]
thanks Jakub!
