### ISSUE TITLE
Error in `tm_facets()`. free.scales not found.

### ISSUE THREAD

**Issue by olivroy** [r-tmap/tmap#820]
Hi,

Trying to investigate potential problems, I took a look at Spatial Data Science with R.

The [example in Chapter 8](https://r-spatial.org/book/08-Plotting.html#fig-tmapnc) is failing in tmap v4.

``` r
devtools::load_all("~/rrr-forks/tmap")
#> ℹ Loading tmap
library(sf)
#> Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE
system.file("gpkg/nc.gpkg", package = "sf") |>
    read_sf() |>
    st_transform('EPSG:32119') -> nc.32119
tm_shape(nc.32119) + tm_polygons(c("SID74", "SID79"), title="SIDS") + 
    tm_layout(legend.outside=TRUE, panel.labels=c("1974-78", "1979-84")) + 
    tm_facets(free.scales=FALSE)
#> Deprecated tmap v3 code detected. Code translated to v4
#> Error in tm_facets(free.scales = FALSE): unused argument (free.scales = FALSE)
```

<sup>Created on 2024-01-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Should we provide a fix to SDSR or are you able to fix this in tmap v4?

https://github.com/edzer/sdsr/pull/119

**Comment by mtennekes** [comment]
In v3, the `free.scales` argument was global (so for the whole plot) and specified in `tm_facets`.

In v4, each visual variable has its own 'free' argument, and moreover, it can be configured for each of the three faceting dimensions (rows, columns, and pages) separately. 

The code in v4 would be:

```r
tm_shape(nc.32119) + tm_polygons(c("SID74", "SID79"), fill.free = FALSE, fill.legend = tm_legend(title = "SIDS")) + 
	tm_layout(legend.outside=TRUE, panel.labels=c("1974-78", "1979-84")) + 
	tm_facets()
```

What I need to do (note to self) is have a tmap option with the default free.scales, which can be locally changed within  `tm_facets`.

**Comment by olivroy** [comment]
Makes sense, thanks for the reply!

But will the code I shared be backward compatible, or should I add the suggested fix to SDSR?

**Comment by mtennekes** [comment]
It will be backward compatible.

**Comment by mtennekes** [comment]
Done! 

However, I now got an error when running the documentation, which I'm used to do via `devtools::check_man()`.
The NAMESPACE that is generated is not right. Something to do with https://github.com/r-tmap/tmap/blob/master/R/tmap_arrange.R#L51C1-L56C5 and the DESCRIPTION line RoxygenNote: 7.3.0 (recently automatic updated). Do you have any idea, @olivroy ?

**Comment by olivroy** [comment]
@mtennekes I will take a look in 2 days. Maybe updating to 7.3.1 will help?

**Comment by olivroy** [comment]
there are some undocumented arguments in tm_facets and tm 
_text. maybe you need to run `devtools::document()` bgcol free.scales in particular

**Comment by olivroy** [comment]
I think we can close.

Old: 
![image](https://github.com/r-tmap/tmap/assets/52606734/b78fab5a-74c8-473e-bc61-2707b5cab893)

New:

``` r
devtools::load_all("~/rrr-forks/tmap")
#> ℹ Loading tmap
library(sf)
#> Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE
system.file("gpkg/nc.gpkg", package = "sf") |>
    read_sf() |>
    st_transform('EPSG:32119') -> nc.32119
tm_shape(nc.32119) + tm_polygons(c("SID74", "SID79"), title="SIDS") + 
    tm_layout(legend.outside=TRUE, panel.labels=c("1974-78", "1979-84")) + 
    tm_facets(free.scales=FALSE)
#> tm_polygons: Deprecated tmap v3 code detected. Code translated to v4
#> tm_facets: the argument free.scales is deprecated. Specify this via the layer functions (e.g. fill.free in tm_polygons)
```

![](https://i.imgur.com/M9VjzSp.png)

<sup>Created on 2024-02-06 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Nice improvement! thanks for taking care of it!
