### ISSUE TITLE
Not  colorNA = function in V4? and credits outside map

### ISSUE THREAD

**Issue by EmilioCdeP** [r-tmap/tmap#821]
Hello there, thanks 4 the work!
I have to rewrite my code for V4 actualization, and i have some issues. First one is how can i change the pallete and how can i change the color for my missing values. The other one is how can i write my credits outside the map.

here it`s my <V4 code that i want to rewrite to make it work

tm_shape(Madrid_union22,bbox=tmaptools::bb(matrix(c(-3.75, 40.347, -3.589, 40.518),2,2)))+
  tm_fill(col = "SELECCIÓN",style = "cat",format="g", stretch.palette = T, colorNA = "white",
          labels = levels(Madrid_union22$SELECCIÓN),palette="Dark2" )+
  tm_borders(col = "black", lwd = 0.01, alpha = 0.6) +
  tm_layout(main.title = "Seccciones Censales de Madrid",title = "Realizado por: Emilio Coronado", 
            title.position = c("RIGHT", "BOTTOM"),legend.outside = TRUE, main.title.position = "left",
            main.title.color = "darkgrey", title.color = "darkgrey") +
  tm_compass(type="rose",position = c("right", "top")) +
  tm_graticules(alpha = 0.2, labels.size=0.5 ,labels.cardinal = T)

And here its V4 code that i want to improve

tm_shape(Madrid_union22,bbox=tmaptools::bb(matrix(c(-3.75, 40.347, -3.589, 40.518),2,2)))+
  tm_polygons(fill = "SELECCIÓN", col = "black",lwd = 0.0001, col_alpha = 0.2,fill.legend = tm_legend(
    	title = "Seccciones Censales de Madrid"), popup.vars = "CUSEC") +
  tm_credits("Realizado por: Emilio Coronado", position=c("left", "bottom")) +
  tm_compass(position = c("right", "top")) +
  tm_graticules(col ="lightgray", labels.size=0.5 ,labels.cardinal = T)

**Comment by EmilioCdeP** [comment]
Unfortunately i cannot upload objects .shp here, and if i compress it to a zip its too big to upload here too so i don´t know how could i share it with you...

**Comment by EmilioCdeP** [comment]
@mtennekes

**Comment by mtennekes** [comment]
@EmilioCdeP you can simply test if you encounter the same issues with `head(Madrid_union22)` and if so, share that object. Otherwise, send me a link via email to a shared cloud folder.

**Comment by mtennekes** [comment]
Is this still an issue @EmilioCdeP ?

**Comment by EmilioCdeP** [comment]
No, it's solved, thanks! :) @mtennekes
