### ISSUE TITLE
Trouble with Legend and Title Placement in tmap v4

### ISSUE THREAD

**Issue by ailich** [r-tmap/tmap#827]
I switched over to tmap v4 and I'm having trouble placing titles and legends where they should be. Sometimes they are inside when specified outside, sometimes the title and legend overlap when specified at different positions, and sometimes they get cut off from the figure. See simple example below.

``` r
library(sf)
library(tmap)
library(spData)

packageVersion("tmap")
#> [1] '3.99.9000'

# Left/Top and Center/Top overlap
# Legend/Title are inside rather than outside even though tm_pos_out is used
tm_shape(nz)+
  tm_fill(fill = "Island", fill.scale = tm_scale_categorical(values=c("red", "#FFEBBE")))+
  tm_title("a)")+
  tm_layout(legend.position = tm_pos_out("left", "top"), 
            title.position = tm_pos_out("center", "top"))
```

![](https://i.imgur.com/HYQnm4G.png)

``` r

#Legend gets cut off and title on inside
tm_shape(nz)+
  tm_fill(fill = "Island", fill.scale = tm_scale_categorical(values=c("red", "#FFEBBE")))+
  tm_title("a)")+
  tm_layout(legend.position = tm_pos_out("left", "bottom"), 
            title.position = tm_pos_out("center", "top"))
```

![](https://i.imgur.com/ooJXSVz.png)

<sup>Created on 2024-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mtennekes** [comment]
Thanks! There are a little bug in the code, now fixed.

You can set the position of title and legend via `tm_layout`, but the standard (recommended workflow is via the layer functions, in this case `tm_fill` and `tm_title`:

```r
tm_shape(nz)+
	tm_fill(fill = "Island", fill.scale = tm_scale_categorical(values=c("red", "#FFEBBE")),
			fill.legend = tm_legend(position = tm_pos_out("left", "center")))+
	tm_title("a)", position = tm_pos_out("center", "top"))
```

Although for the legends, I see the benefits of setting the position via `tm_layout`, namely in case there are more legends that you would like to place somewhere.

Feel free to reopen this issue if you have further questions.
