### ISSUE TITLE
alpha for raster does not survive reprojection

### ISSUE THREAD

**Issue by mdsumner** [r-tmap/tmap#832]
If we put a  partially transparent raster over we can still see the line : 

```R
library(tmap)
tm_shape(vect(cbind(0:1, 0:1), type = "l")) + 
	tm_lines() + 
	tm_shape(rast(matrix(1))) + 
	tm_raster(col_alpha = 0.2)
```

![image](https://github.com/r-tmap/tmap/assets/4107631/55dfd2f0-02c6-411b-aa3f-d3081061d5ce)

but if reprojection is involved alpha is lost: 

```R
tm_shape(vect(cbind(c(0, 1852 * 60), c(0, 1852 * 60)), type = "l", crs = "+proj=laea")) + 
	tm_lines() + 
	tm_shape(rast(matrix(1), crs = "EPSG:4326")) +
	tm_raster(col_alpha = 0.5)

```

![image](https://github.com/r-tmap/tmap/assets/4107631/f9c58d2e-b2b6-4046-bf69-8c29f0ed35e2)

Came up in a discussion with this example: 

```R
library(sf)
library(terra)
library(spData)
library(spDataLarge)
library(tmap)

nz_elev <- rast(system.file("raster/nz_elev.tif", 
							package = "spDataLarge"))

tm_shape(nz) +
	tm_borders() +
	tm_shape(nz_elev) +
	tm_raster(col_alpha = 0.5)
```

I tried to track it down but got a bit lost, will PR if I find it, thanks!

**Comment by mtennekes** [comment]
Fixed, thx @mdsumner
