### ISSUE TITLE
legend.is.portrait = FALSE not available for tm_bubble

### ISSUE THREAD

**Issue by anjelinejeline** [r-tmap/tmap#834]
Hi I would like to have a horizontal legend when using tm_bubble 
however it seems that the option legend.is.portrait is not available for this function. 
Is there a workaround to create a horizontal legend with tm_bubble ?   
Thanks 
Angela

**Comment by aonojeghuo** [comment]
Hi @anjelinejeline, you could try legend.col.is.portrait = T or legend.size.is.portrait = T and see if it takes them.  col or size will depend on if the legend is based on the bubble sizes or colors.

**Comment by mtennekes** [comment]
This was not available in tmap3 in view mode. Is that what you are referring to?

Anyway, this is the plot mode in tmap4:

``` r
tm_shape(metro) +
    tm_bubbles(size = "pop2020", 
               fill = "pop2010", 
               size.legend = tm_legend(orientation = "landscape", stack = "vertical"),
               fill.legend = tm_legend(orientation = "landscape"))
```

![](https://i.imgur.com/cqCVPZL.png)

<sup>Created on 2024-03-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

and view mode:

<img width="1253" alt="Screenshot 2024-03-07 at 15 43 22" src="https://github.com/r-tmap/tmap/assets/2444081/1d506e8f-5f5c-4297-bdec-6d1f4e63df68">
