### ISSUE TITLE
`tm_lines` results in graphical artifacts

### ISSUE THREAD

**Issue by James-G-Hill** [r-tmap/tmap#835]
I create a simple map with a `states` layer and then a series of lines representing the Eastern coast of the US. I applied a palette to the lines along with a categorical variable. Unfortunately the lines appear to have artifacts, presumably where they maybe overlapping at the ends due to the line width option.

I wondered if this would be temporarily fixable if there was an option that could allow selection of the `butt` or `square` line end type?

![Screenshot 2024-02-12 014946](https://github.com/r-tmap/tmap/assets/2002036/f324bcd8-9bc2-441c-ad51-670d4958d75a)

**Comment by mtennekes** [comment]
In v4, you can change the `lineend` and `line join`. These are arguments of `tm_lines`, passed on to `gpar` (see details there).
E.g.

```r
tm_shape(rivers)+
	tm_lines(col = "scalerank", lwd = 5, lineend = "butt")
```

**Comment by James-G-Hill** [comment]
Thanks @mtennekes I will try this to see if there is an improvement.
