### ISSUE TITLE
tm_chart implemented (histogram, box plot, etc.); please review

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#842]
``` r
## numerical variable

tm_shape(World) + 
    tm_polygons ("HPI", 
                 fill.scale = tm_scale_intervals(), 
                 fill.chart = tm_chart_histogram())
```

![](https://i.imgur.com/z3URT2u.png)

``` r

tm_shape(World) + 
    tm_polygons ("HPI", 
                 fill.scale = tm_scale_continuous(), 
                 fill.chart = tm_chart_histogram(position = tm_pos_out("center", "bottom"), width = 30))
#> Warning: Some legend items or map compoments do not fit well (e.g. due to the
#> specified font size).
```

![](https://i.imgur.com/g6u1CK9.png)

``` r

tm_shape(World) + 
    tm_polygons ("HPI", 
                 fill.scale = tm_scale_intervals(), 
                 fill.chart = tm_chart_donut())
```

![](https://i.imgur.com/oxTR2pv.png)

``` r

tm_shape(World) + 
    tm_polygons ("HPI", 
                 fill.scale = tm_scale_intervals(), 
                 fill.chart = tm_chart_box())
```

![](https://i.imgur.com/K5zZYMo.png)

``` r

tm_shape(World) + 
    tm_polygons ("HPI", 
                 fill.scale = tm_scale_intervals(), 
                 fill.chart = tm_chart_violin())
```

![](https://i.imgur.com/AQ5l6uP.png)

``` r

# with additional ggplot2 code
require(ggplot2)
#> Loading required package: ggplot2
tm_shape(World) + 
    tm_polygons ("HPI", 
                 fill.scale = tm_scale_intervals(), 
                 fill.chart = tm_chart_bar(extra.ggplot2 = theme(panel.grid.major.y = element_line(colour = "red"))))
```

![](https://i.imgur.com/ca8php2.png)

``` r

tm_shape(land) +
    tm_raster("trees",
              col.chart = tm_chart_histogram())
```

![](https://i.imgur.com/QhCFCsq.png)

``` r

## categorical variable
tm_shape(World) + 
    tm_polygons ("economy", 
                 fill.scale = tm_scale_categorical(), 
                 fill.chart = tm_chart_bar())
```

![](https://i.imgur.com/bhpFv02.png)

``` r

tm_shape(World) + 
    tm_polygons ("economy", 
                 fill.scale = tm_scale_categorical(), 
                 fill.chart = tm_chart_donut())
```

![](https://i.imgur.com/frySZxc.png)

<sup>Created on 2024-03-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by LenLon** [comment]
Antarctica is a developing region? I had no idea :-D

**Comment by mtennekes** [comment]
> Antarctica is a developing region? I had no idea :-D

Me neither, but apparently that's what in the data is. 

However, this brings up a question that comes back every now and then: in which CRS should the tmap example data be stored? In tmap3, `World` was in Eckert IV, but in tmap4 (so far) `World` is in 4326 (WGS84). Do we need to implement a "smart" automatic CRS, that is optimised for that bounding box? @Nowosad I thought this has been discussed, but I couldn't find the related issue.

**Comment by Nowosad** [comment]
@mtennekes I think you are looking for this discussion -- https://github.com/r-tmap/tmap/issues/457
