### ISSUE TITLE
Customize histogram in the legend

### ISSUE THREAD

**Issue by anjelinejeline** [r-tmap/tmap#844]
Is it possible to modify the x and y axis of the histogram in the legend? as well as separte it from the colour scale when defining the legend position? 
 I found [this](https://stackoverflow.com/questions/71178203/is-there-any-way-to-customize-legend-histogram-x-axis-or-y-axis-using-tm-layout) old post but I am not sure whether the new version of tmap allows such things now

**Comment by mtennekes** [comment]
It should be possible in v4. Check out #843. If you have concrete use-cases (with examples) that you would like to have, let us know.
