### ISSUE TITLE
how to install v4?

### ISSUE THREAD

**Issue by BlaiseKelly** [r-tmap/tmap#845]
When I load tmap: library(tmap) it gives a line of code to install v4

```
Breaking News: tmap 3.x is retiring. Please test v4, e.g. with
remotes::install_github('r-tmap/tmap')
```

However, this installs v3.99. I can't find how to install v4.

**Comment by Nowosad** [comment]
Hi @BlaiseKelly -- v3.99 is the most current version (we will change the number to v4, when most important functions are stable).
