### ISSUE TITLE
collapse layer selector in mode "view" & scale trans functions (pseudo_log with sigma)

### ISSUE THREAD

**Issue by xtimbeau** [r-tmap/tmap#847]
Hi, thanks for the package and the new v4 option, love the scale stuff (but you should add trans for neg/pos range like pseudo log).

Is there a way to collapse the layer selector in interactive mode (tmap-mode("view"). It stays open and occupy a lot of space on a standard map.

**Comment by mtennekes** [comment]
Hi @xtimbeau thanks for letting me know. This is a view-only option which we still have to migrate. Not a lot of work though :-)

Besides that, I am curious about your suggestion related to the scale. Can you give me an example?

**Comment by xtimbeau** [comment]
hi @mtennekes, you can have a look at the scales package (https://scales.r-lib.org/reference/log_trans.html). Such transformation is very useful for color scales when the range of colors is negative to positive but when a linear scale gives too much room to high absolute value. Using that transform (and the cut parameter associated) allows to improve contrast.

**Comment by mtennekes** [comment]
Ok, I borrowed some code from `scales::pseudo_log_trans`, and implemented a new trans, called `"pseudo_log"`.

Please check if it makes sense @xtimbeau :

```r
World$HPI2 = World$HPI - 30
tm_shape(World) +
	tm_polygons("HPI2", fill.scale = tm_scale_continuous())
tm_shape(World) +
	tm_polygons("HPI2", fill.scale = tm_scale_continuous(trans = "pseudo_log"))
```

The functions from scales has two parameters, `sigma` and `base`. Are both useful?

Could you provide a data example for this scale would be useful?

**Comment by xtimbeau** [comment]
@mtennekes great ! I'll test it and try to factor a nice example.

**Comment by xtimbeau** [comment]
@mtennekes sigma is quite useful as it sets the cut for when the log is smoothed to a linear function. Pseudo log looks like a log above  a few signa (or below a few -sigma) but is linear between -sigma and sigma. Base is also relevant because of that non log linearity.

**Comment by mtennekes** [comment]
Collapse has already been set to TRUE by default (forgot to mention earlier).

I've implemented `tm_scale_continuous_pseudo_log`, with sigma and base. Indeed very handy @xtimbeau this `sigma` parameter!

Also added `tm_scale_continuous_log10`, `tm_scale_continuous_log2`, and `tm_scale_continuous_log` with base. Please check. The only difference between log, log2, log10, is that with a base other than exp(1), the labels will be formatted as `base^x`.
