### ISSUE TITLE
print v3 to v4 translated code in console

### ISSUE THREAD

**Issue by ar-puuk** [r-tmap/tmap#854]
If the package is automatically translating the code from v3 to v4, would it be possible to make the translation print in the console, at least for learning purposes?

It could be a global option.

```{r}
#> tm_lines: Deprecated tmap v3 code detected. Code translated to v4
#> charts not implemented in view mode
```

**Comment by jose-m-maciasiii** [comment]
Support! Mainly I am trying to figure out how to use the v3 legend.hist = TRUE in the new style

**Comment by Nowosad** [comment]
@jose-m-maciasiii see https://github.com/r-tmap/tmap/issues/842

**Comment by mtennekes** [comment]
Done!  https://github.com/r-tmap/tmap/commit/fa7c6e5bc92929d544d0ea5f87c6656cb86ebdfc

Well, not meant for 100% copy-paste, but with a series of messages that also has an educational value (hopefully).

I've tested most of the examples from v3. Please check

**Comment by ar-puuk** [comment]
Thanks a lot. That was a lot of effort you have put into it (I checked the commit). As you said, it is not 100% copy-paste, but it's helpful to begin the edits. There seems to be a lot to learn.

I really appreciate all the effort.

**Comment by mtennekes** [comment]
Thx. Our aim is to make tmap much more intuitive: rather than having to go through a huge list of arguments (even myself!), the systematic approach of v4 will make it a lot easier (hopefully) to find what you're after.

Making it 100% copy-paste is of course possible, but not sure if it's worth the effort.

**Comment by olivroy** [comment]
I think this can be closed! I think users will find them very helpful Great effort by @mtennekes here!
