### ISSUE TITLE
Scales and colour palettes. 

### ISSUE THREAD

**Issue by SebKrantz** [r-tmap/tmap#856]
Hi, I didn't think I would create an issue because of this, but after a fair bit of trying I am not managing to plot a `tm_lines()` using an sf shapefile with linestring geometry, colored by a continuous variable "x", using the "inferno" palette and a log scale for the colouration ("x" has many small values and a few big ones). I hope you can help me out regarding the new API.

**Comment by Nowosad** [comment]
@SebKrantz could you provide us with a simple reproducible example?

**Comment by SebKrantz** [comment]
```r
library(sf)
library(tmap)

# Create example data with random coordinates
set.seed(123)
num_lines <- 15
lines <- st_as_sf(data.frame(
  geometry = st_sfc(lapply(1:num_lines, function(i) {
    st_linestring(matrix(runif(4, min = 0, max = 10), ncol = 2))
  })),
  x = 10^runif(num_lines, min = 0, max = 7)
))

# Attempt to create the tmap plot
tm <- tm_shape(lines) +
  tm_lines(col = "x", palette = "inferno", col.scale = tm_scale_continuous_log()) +
  tm_layout(legend.outside = TRUE)

# Display the map
tmap_mode("plot")
tm

```

**Comment by Nowosad** [comment]
@SebKrantz and what is the problem with the current output (I was able to run it and got a map in result..)?

**Comment by Nowosad** [comment]
In tmapv4, palettes can be set inside scales (e.g.,  `tm_lines(col = "x", col.scale = tm_scale_continuous_log(values = "inferno"))`

**Comment by SebKrantz** [comment]
Ahh ok, thanks. It was not clear to me that palettes argument is redirected to values. I see it is mentioned in the documentation but I somehow missed it thinking that values is related to data ('visual values' sounds like data to me) or to specific values as in ggplot `scale_color_manual()`. Perhaps an example in the tmap4 vignette would help. Anyway, thanks!

**Comment by Nowosad** [comment]
@SebKrantz for now, you can read https://r.geocompx.org/adv-map#scales
