### ISSUE TITLE
Wrong v3 code translation

### ISSUE THREAD

**Issue by olivroy** [r-tmap/tmap#861]
```r
tmap_mode("view")
	m <- tm_shape(NLD_muni) +
		     tm_fill(col="population", convert2density=TRUE, 
                 style="kmeans", 
                 title=expression("Population (per " * km^2 * ")")) +
		     tm_borders("black", alpha=.5) + 
		 tm_shape(NLD_prov) +
		     tm_borders("grey25", lwd=2) +
		tm_style("classic") +
		tm_format("NLD", inner.margins = c(.02, .15, .06, .15)) + 
	    tm_scale_bar(position = c("left", "bottom")) +
	    tm_compass(position=c("right", "bottom"))
```

V4: Nice addition of the compass in "view" mode
![image](https://github.com/r-tmap/tmap/assets/52606734/38bac9f7-97e5-4a3f-bbb7-4f1e22c33d7b)

* ~legend title not passed correctly.~ 
* ~style = "k-means" not passed correctly or maybe `convert2density`.~
* popups not treated the same?
* ~In plot mode, the compass looked better in v3?~
V4 patched!
![image](https://github.com/r-tmap/tmap/assets/52606734/23aef60d-6974-4e3c-b070-41e6b2803e9a)

V3
![image](https://github.com/r-tmap/tmap/assets/52606734/84134656-8955-4d07-9b46-cf494864a772)

* the basemap control doesn't work in v3 anyway

**Comment by mtennekes** [comment]
Nice catch. Several issues here. Also `col` should be redirected to `fill` visual variable.

**Comment by olivroy** [comment]
thank you for your work I know it is a lot of small details. 

Wish I could help more with the barebones

**Comment by mtennekes** [comment]
example works in plot mode. Note that the style `"classic_v3"` is required rather than `"classic"`. I could automatically switch to a `_v3` style in case v3 code is detected in another tmap element.

To do for view mode: 

* popups
* sepia colors for layer selection box and zoom buttons, and background in general.

**Comment by olivroy** [comment]
>  I could automatically switch to a `_v3` style in case v3 code is detected in another tmap element.

I think it is okay as is. Maybe others will have different opinions, my main concern is more about getting the data right, rather than exact color or styling!

Looks fantastic with your most recent fix!
![image](https://github.com/r-tmap/tmap/assets/52606734/c2f0412d-0903-4472-ad3c-b6e3aee1c1bb)

![image](https://github.com/r-tmap/tmap/assets/52606734/8d1ed1fb-9a74-455a-901b-a3fc7c0bef7e)

**Comment by mtennekes** [comment]
Code translation improved. Please check

**Comment by olivroy** [comment]
Hi @mtennekes , thanks for working on this!

Seems like there are still issues on main as of this commit 8fc35ffacab8b02847b4f09f26ea5aa1847040b2

The example I provided in the initial comment errored

Error is 
```r
Erreur dans FUN(X[[i]], ...) : objet 'km' not found
```

Also, the title and breaks are not passed correctly. (it worked in a previous dev version)

![image](https://github.com/r-tmap/tmap/assets/52606734/5824da03-6f94-49b8-a23a-2412c3ad21b5)

**Comment by mtennekes** [comment]
The first example is working again!

Not sure though if it does not break other examples... In order to make the expression title work I had to replace `list` to `alist` (e.g. in https://github.com/r-tmap/tmap/blob/93554e8aab332a9b607e367283e4fbd0e62d8750/R/tm_layers_polygons.R#L238)

**Comment by olivroy** [comment]
Thanks! The build is not working currently (Unknown exports `tm_donut()` and `opt_tm_donut()`. Maybe `check_man()` should be run again

**Comment by mtennekes** [comment]
> Thanks! The build is not working currently (Unknown exports `tm_donut()` and `opt_tm_donut()`. Maybe `check_man()` should be run again

See #869 , should be fixed

**Comment by olivroy** [comment]
Looking good, thanks! 

I think we can close this one

View
![image](https://github.com/r-tmap/tmap/assets/52606734/9f7811e2-9785-4a95-9975-8a1335e6c714)

Plot
![image](https://github.com/r-tmap/tmap/assets/52606734/f0940dda-9cc5-42ae-a3bc-c841edf9ef91)
