### ISSUE TITLE
Faceting broken in v4?

### ISSUE THREAD

**Issue by tylerreed11** [r-tmap/tmap#867]
I downloaded v4 and was having issues running even the example faceting -

```
remotes::install_github('r-tmap/tmap')
library(tmap)
tm_shape(World, crs = "+proj=robin") +
    tm_borders() +
tm_shape(World) +
    tm_polygons("life_exp", fill.free = TRUE) +
tm_facets_wrap("continent", nrow = 1)
```
`Error in vapply(legs2, function(l) { : values must be length 1,
 but FUN(X[[1]]) result is length 8`
Same error when trying to use tm_facets directly.

Still works in the version from CRAN.

**Comment by mtennekes** [comment]
Thx! Should be working, if not please reopen.
