### ISSUE TITLE
`main.title.color` not respected.

### ISSUE THREAD

**Issue by olivroy** [r-tmap/tmap#872]
Code translation tiny issue

```r

tm_shape(World) +
		tm_polygons(c("income_grp", "economy"), title = c("Legend Title 1", "Legend Title 2")) +
		tm_layout(main.title = "Main Title",
				  main.title.position = "center",
				  main.title.color = "blue",
				  title = c("Title 1", "Title 2"),
				  title.color = "red",
				  panel.labels = c("Panel Label 1", "Panel Label 2"),
				  panel.label.color = "purple",
				  legend.text.color = "brown")
```

| V4| V3|
|--------|--------|
| ![image](https://github.com/r-tmap/tmap/assets/52606734/9d54ac11-10fe-4f31-810a-c8e31d862ab6) | ![image](https://github.com/r-tmap/tmap/assets/52606734/2878d812-a40f-4e42-825c-75ca063592b0) | 

Notice that the main title is red in v4.

**Comment by mtennekes** [comment]
Run `tmap_style("v3")` to make this example look like the v3 output. 
Note: `+ tm_style("v3")` does not respect `panel.labels` yet...
