### ISSUE TITLE
interpolate=TRUE from tm_raster in tmap v4?

### ISSUE THREAD

**Issue by marine-ecologist** [r-tmap/tmap#873]
How can I implement interpolate=TRUE in tm_raster in v4?

Looking at the source code, "interpolate" is a remnant of v3, but a translation isn't available and I can't find the direct code to interpolate.

```
v3 = c("alpha", "palette", "n", "style", "style.args", "as.count", 
        "breaks", "interval.closure", "labels", "drop.levels", 
        "midpoint", "stretch.palette", "contrast", "saturation", 
        "interpolate", "colorNA", "textNA", "showNA", "colorNULL", 
        "title", "legend.show", "legend.format", "legend.is.portrait", 
        "legend.reverse", "legend.hist", "legend.hist.title", 
        "legend.z", "legend.hist.z", "auto.palette.mapping", 
        "max.categories", "max.value")
    if (any(v3 %in% names(args))) {
        message("tm_raster: Deprecated tmap v3 code detected. Code translated to v4")
```

**Comment by mtennekes** [comment]
Implemented :-) Please check. These layer-specific options are not included in the`opt_tm_x` functions:

```r
tm_shape(land) + tm_raster("trees", options = opt_tm_raster(interpolate = TRUE))
```

Let me know if it works as expected.

**Comment by marine-ecologist** [comment]
Thanks @mtennekes - I can't seem to reproduce this on ‘tmap’ version 3.99.9001:


> `> tm_shape(land) + tm_raster("trees", options = opt_tm_raster(interpolate = TRUE))`
> Error in opt_tm_raster(interpolate = TRUE) : 
>   unused argument (interpolate = TRUE)
