### ISSUE TITLE
Feature request: scale.values argument to tm_scale_* support flexible resizing. 

### ISSUE THREAD

**Issue by SebKrantz** [r-tmap/tmap#877]
I have an interval scale of the form 

```r
tm_dots(size = "population", 
        size.scale = tm_scale_intervals(breaks = c(0, 1, 2e5, 1e6, Inf), values.scale = 0.3),
        size.legend = tm_legend("City Category", frame = FALSE))
```
The result is
<img width="168" alt="Screenshot at May 13 22-43-05" src="https://github.com/r-tmap/tmap/assets/48053842/fdc67872-7d7e-46fe-9b8b-26962ee08ac8">

Now I want the circle sizes to roughly reflect the city sizes. This does not seem possible using `values.scale`, which only controls the overall size. Passing a function such as `scale.values = exp` or a vector of values of the same length as `breaks` would facilitate flexible resizing. Right now, the only way seems to define a new method for the multiplication operator:

```r
# Define the constructor for the mult_power class
mult_power <- function(x) {
  # Ensure that x is numeric
  if (!is.numeric(x)) {
    stop("Input must be numeric.")
  }
  structure(x, class = "mult_power")
}

# Define the Ops method for the mult_power class
Ops.mult_power <- function(e1, e2) {
  # Detect the operation being performed
  if (.Generic == "*") {
    # Perform exponentiation if the operation is multiplication
    return(mult_power(e1^e2/sqrt(e2)))
  } else {
    # Default to standard operations for other types of operations
    # This calls the standard Ops method after dropping the class
    return(NextMethod(.Generic))
  }
}

```
such that 

```r
tm_dots(size = "population", 
        size.scale = tm_scale_intervals(breaks = c(0, 1, 2e5, 1e6, Inf), values.scale = mult_power(3)),
        size.legend = tm_legend("City Category", frame = FALSE))
```
yields

<img width="178" alt="Screenshot at May 13 22-46-48" src="https://github.com/r-tmap/tmap/assets/48053842/1b429b8b-1e5f-4792-a562-f3450b720226">

However, this is not elegant.

**Comment by SebKrantz** [comment]
Thanks! Appreciate those examples, and would encourage you to include them in the documentation, e.g. of `tm_scale_continuous()`.

**Comment by mtennekes** [comment]
You're welcome. Good idea to add them to the examples!
