### ISSUE TITLE
Broken layer controls in the interactive mode

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#882]
```r
# remotes::install_github("r-tmap/tmap")
library(tmap)
library(terra)
tmap_mode("view")
srtm = rast(system.file("raster/srtm.tif", package = "spDataLarge"))
tm_shape(srtm) +
  tm_raster()
```

![Peek 2024-05-25 18-47](https://github.com/r-tmap/tmap/assets/3457131/2c73cdcb-5db9-481e-bb6a-b4349fdc75a2)

**Comment by mtennekes** [comment]
This issue was also there in v3. It has to do with the missing pane option of `addRasterImage`. The good news it that it seems to be fixed in `leaflet` 2.2.2: https://github.com/r-spatial/leafem/issues/58
When it is added to `leafem::addStarsImage` as well I can add this in `tm_raster` as well.

**Comment by mtennekes** [comment]
Apparently, this is still not fixed (#921) :(

The problem is that raster layers are still placed in the `leaflet-tile-pane` instead of `leaflet-tmap4xx-pane`.

Upstream ping https://github.com/r-spatial/leafem/issues/58

**Comment by szylinski-sa** [comment]
Hi, has this issue progressed at all? Having the problem as described here and in #921. Switching raster layers does nothing, and switching the basemap hides them entirely with no way to bring them back (the raster layers are still checked).

R v4.3.2 (unfortunately not able to install anything else)
tmap v3.3.4
leaflet v2.2.2
leafem v0.2.3.9906 (from install_github)
Windows 10

**Comment by Nowosad** [comment]
Now works fine with the dev version of leafem:

```r
# remotes::install_github("r-tmap/tmap")
# remotes::install_github("r-spatial/leafem")
library(tmap)
library(terra)
tmap_mode("view")
srtm = rast(system.file("raster/srtm.tif", package = "spDataLarge"))
tm_shape(srtm) +
  tm_raster()
```
