### ISSUE TITLE
Option for disabling messages for meta.auto.margins in tm_raster? 

### ISSUE THREAD

**Issue by marine-ecologist** [r-tmap/tmap#885]
I ran into an issue with `stars` and `tmap`, and reinstalled the latest `GitHub` versions which fixed the issue. Everything is working fine now, but I can't seem to find a way of silencing the `meta.auto.margins` messages with `tm_raster`: 

```
data(land, World)

tm_shape(land) +
  tm_raster("elevation", col.scale = tm_scale_continuous(values = terrain.colors(9))) +
 tm_shape(World) +
  tm_borders()
```

returns

```
<====================  meta.auto.margins ===============>
[1] 0.4 0.4 0.4 0.4
</============================================>
Index: <stack_auto>
   by1__ by2__ by3__                              comp  class cell.h cell.v  pos.h  pos.v     z facet_row facet_col stack_auto    stack
   <num> <int> <int>                            <list> <char> <char> <char> <char> <char> <int>    <char>    <char>     <lgcl>   <char>
1:     1    NA    NA <tm_legend_standard_portrait[83]>    out  right center   left    top     1      <NA>      <NA>       TRUE vertical
        legW  legH
       <num> <num>
1: 0.7123815 3.277

```

Setting `warning=FALSE` and `message=FALSE` in `rmarkdown` chunks doesn't suppress the message, nor does `suppressMessages()` or `suppressWarnings()`.

No issues with other `tmap` vector types:

```
 tm_shape(World) +
  tm_borders()
```

Thanks again for all your help, tmap v4 is a learning curve but incredibly versatile!

**Comment by mtennekes** [comment]
This is just a development message that I forgot to remove. It it not there anymore in the latest GH version
