### ISSUE TITLE
v3 to v4 messages should only be signaled once per session

### ISSUE THREAD

**Issue by olivroy** [r-tmap/tmap#890]
Thanks to #854, it is a little easier to know how to switch code from v3 to v4. 

However, these messages can be a little overwhelming. As mentioned in https://github.com/r-tmap/tmap/issues/888#issuecomment-2162866397

I will wait for #851 to do this.

I will use [cli](https://cli.r-lib.org/articles/semantic-cli.html) to do this. https://rlang.r-lib.org/reference/abort.html#muffling-and-silencing-conditions

**Comment by mtennekes** [comment]
Thx! #851 is done, but not sure what the relation with the messaging is...

**Comment by Nowosad** [comment]
I am now trying a lot of old tmap3 code -- I am very impressed with the messages helping to convert the code from the old syntax to the new one. Great work @olivroy @mtennekes
