### ISSUE TITLE
Documentation for v4: suggested update to 

### ISSUE THREAD

**Issue by MatthieuStigler** [r-tmap/tmap#896]
Is there an official documentation for v4, besides "tmap v4: a sneak peek" [(link)](https://mtennekes.github.io/tmap4/index.html#Map_layers_(eg_cartogram))?

It seems that the code on *Multivarite Scales* on that page needs to be updated to:

```
tm_shape(World) +
  tm_fill(fill = tm_mv("well_being", "footprint"), 
          fill.scale = tm_scale_bivariate(scale1 = tm_scale_intervals(breaks = c(2, 5, 6, 8)),
                                          scale2 = tm_scale_intervals(breaks = c(0, 3, 6, 20)),
                                          values = "brewer.qualseq"))
```

Thanks!

**Comment by Nowosad** [comment]
Hi @MatthieuStigler -- I think that https://r.geocompx.org/adv-map is the most current documentation for tmap v4. We also plan to update https://r-tmap.github.io/tmap-book/ some time in the future, when the version 4 is on CRAN.

**Comment by MatthieuStigler** [comment]
ok, thanks for the info!

It would be nice to mention the main reference in the message?

> Breaking News: tmap 3.x is retiring. Please test v4, e.g. with

The problem is that a naive search will rather lead to "tmap v4: a sneak peek" [(link)](https://mtennekes.github.io/tmap4/index.html#Map_layers_(eg_cartogram)), which is sometimes outdated?

Thanks a lot!!

**Comment by Nowosad** [comment]
@MatthieuStigler where I can find the "Breaking News: tmap 3.x is retiring. Please test v4, e.g. with" message? I was unable to find it...

**Comment by MatthieuStigler** [comment]
true, that message comes with tmap `3.3.4`, and presumably was removed with tmap `3.99.9`, my bad. 

So I guess one could consider adding a new message to `3.99.9`, mentioning it's a *massive change* (sic) and pointing to some documentation helping users understand new/different code?

Thanks!

**Comment by Nowosad** [comment]
👍🏻 I like this idea. What do you think @mtennekes?

**Comment by nickbearman** [comment]
> @MatthieuStigler where I can find the "Breaking News: tmap 3.x is retiring. Please test v4, e.g. with" message? I was unable to find it...

Yes I think this is with tmap v3.3-4. 

New users, installing via CRAN `install.packages("tmap")` still get this message:

![image](https://github.com/r-tmap/tmap/assets/6410645/ceb3f9cc-e75c-48f2-8f29-12dbb0b53e8e)


I think this should be updated with a link to more info, as @MatthieuStigler suggests.

**Comment by mtennekes** [comment]
Indeed good idea to add a message to 3.99.9 @MatthieuStigler 

I'm a bit reluctant to send a new 3.x version to CRAN just to make the startup message more informative.

The best we can (and should) do is to make the home page (https://github.com/r-tmap/tmap) up-to-date and to the point. Until our book has been updated, https://r.geocompx.org/adv-map should be mentioned as the main source of documentation.

Please feel free to PR. Atm, I'm working on probably the last big hurdle of tmap4, namely shiny integration.

**Comment by olivroy** [comment]
Note that the documentation for v4 lives on pkgdown site (dev version) https://r-tmap.github.io/tmap/dev/

**Comment by nickbearman** [comment]
I have also added these links to the main text, and corrected a few typos in https://github.com/r-tmap/tmap/pull/901
