### ISSUE TITLE
tmap_grob not working well with gridExtra::grid.arrange

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#905]
```r
library(ggplot2)
library(gridExtra)

g1 = ggplot(iris) + geom_point(aes(x = Sepal.Length, y = Sepal.Width))
tm1 = tm_shape(World) + tm_polygons()

gridExtra::grid.arrange(tmap_grob(tm1), g1, nrow= 1)
```

![image](https://github.com/user-attachments/assets/a19785fd-f3d6-42c6-8605-5dae993a85df)

Working well:

```r
# working well
library(grid)
grid.newpage()

pushViewport(viewport(layout = grid.layout(1,2)))

print(tm1, vp = viewport(layout.pos.col = 1, layout.pos.row = 1))
print(g1, vp = viewport(layout.pos.col = 2, layout.pos.row = 1))
```

![image](https://github.com/user-attachments/assets/4d3bcb01-9d82-4535-902a-ecad9209c6ea)

Triggered by https://github.com/edzer/sdsr/pull/119#issuecomment-2249780424

**Comment by mtennekes** [comment]
Updated `tmap_grob` (FYI @rsbivand @edzer @Nowosad )

Drawing a tmap grob in a viewport with a different aspect ratio from the map somehow doesn't work well. This was already a problem in v3, and so far haven't been able to fix it.

So I opted for a pragmatic solution: I've added two arguments to `tmap_grob`, namely `asp` and `scale`. 

e.g.

```r
library(ggplot2)
library(gridExtra)

g1 = ggplot(iris) + geom_point(aes(x = Sepal.Length, y = Sepal.Width))
tm1 = tm_shape(World) + tm_polygons()

gridExtra::grid.arrange(tmap_grob(tm1, asp = 1.25), g1, nrow= 1)
```

![image](https://github.com/user-attachments/assets/372abd87-0981-49d2-89da-d5470cc35da6)

Note that in case the desired aspect ratio is unknown (or flexible due to different rendering layouts), it is always safer to the aspect ratio lower than that of the map.

**Comment by aonojeghuo** [comment]
Hi @mtennekes . Can tmap_grob be used wit more than one tmap object? For example, in the example above, having 2 maps and one ggplot object.

**Comment by Nowosad** [comment]
@aonojeghuo yes, it can.

**Comment by aonojeghuo** [comment]
> [@aonojeghuo](https://github.com/aonojeghuo) yes, it can.

Thanks @Nowosad . I'm leaving this here in case it is needed by someone else in future. 

     ## arrange tmap objects in individual tmap_grob wraps
      Map1 <- cowplot::plot_grid(tmap_grob(tm1),tmap_grob(tm2),align="v")
      ## Arrange with ggplot2
      cowplot::plot_grid(Map1, g1,ncol=1,rel_heights=c(0.6,0.4))
