### ISSUE TITLE
Large drop of performance for tm_raster() in tmap-4.0 compared with tmap-3.3

### ISSUE THREAD

**Issue by gilbertocamara** [r-tmap/tmap#910]
Dear @mtennekes 

First of all, congratulations on version 4.0 of tmap. It is nicely structured, has a better design, and its graphic output is nicer.

However, I am experiencing a considerable loss of performance in the tmap::tm_raster() function. Consider the following MWE:

``` {r}
red_file <- "https://www.dropbox.com/scl/fi/lzr5m1jjcekonfixdwg5q/SENTINEL-2_MSI_20LMR_B11_2022-08-17.tif?rlkey=zitxhutz2c7s4za16j5n65hjt&dl=1"

green_file <- "https://www.dropbox.com/scl/fi/r52dxruzte68h5s80y753/SENTINEL-2_MSI_20LMR_B8A_2022-08-17.tif?rlkey=86pkz2lxqi00afyjrxqazoo4d&dl=1"

blue_file <- "https://www.dropbox.com/scl/fi/z9490rrfleb4dc8845pqx/SENTINEL-2_MSI_20LMR_B02_2022-08-17.tif?rlkey=6hq2drte6ayubnlomvacdlfd3&dl=1"

# read raster data as a stars object with separate RGB bands
rgb_st <- stars::read_stars(
    c(red_file, green_file, blue_file),
    along = "band",
    RasterIO = list(
        nBufXSize = 1024,
        nBufYSize = 1024
    ),
    proxy = FALSE
)
# open RGB stars
rgb_st <- stars::st_rgb(rgb_st[, , , 1:3],
                        dimension = "band",
                        maxColorValue = 10000,
                        use_alpha = FALSE,
                        probs = c(0.05, 0.95),
                        stretch = TRUE
)
# plot using tmap (code is the same for tmap-3.3 and tmap-4.0
p <- tmap::tm_shape(rgb_st, raster.downsample = FALSE) +
    tmap::tm_raster() +
    tmap::tm_graticules(
        labels.size = 0.8
    ) +
    tmap::tm_layout(
        scale = 0.7
    ) +
    tmap::tm_compass()
p
```

After the images are loaded into the stars object “rgb_st”, the tmap part takes 10 seconds to plot with tmap-3.3 and 45 seconds to plot with tmap-4.0. The code is the same in the two versions. Could you help me improve the performance of tm_raster() in tmap-4.0?

**Comment by mtennekes** [comment]
Large performance drop has been fixed (note-to-self, here https://github.com/r-tmap/tmap/blob/master/R/tmapGridRaster.R#L25-L30)

Your example is great for further improvement of `tm_raster`, thanks for sharing.

I haven't used `st_rgb` before, but it is also discussed here  in #345.

Not sure how to integrate it with tmap. Perhaps the arguments of `st_rgb` could be passed from `tm_scale_rgb`? Not easy, because the scale functions use `data.table`s, so have to convert it to a `stars` first.

The current r-g-b to hex conversion is very basic: it just contains one option: `maxValue`:

```
# using the original rgb_st
tm_shape(rgb_st) +
   tm_rgb(tm_mv_shape_vars(ids = 1:3), col.scale = tm_scale_rgb(maxValue = 10000))
```

Other than the features of `tm_rgb` (and named here #655), what other features would you like to see?

**Comment by gilbertocamara** [comment]
Dear @mtennekes, great job! Many thanks. 

As for the integration of stars::st_rgb into `tmap`, I also unsure on how to proceed. Maybe the stretch options (`probs = c(0.05, 0.95)`, `stretch = TRUE`) could be incorporated in the tm_scale_rgb() function. Stretching based on probabilities is quite useful to equalize band responses, especially in the case of SAR data.

**Comment by mtennekes** [comment]
`tm_scale_rgb` reimplemented  https://github.com/r-tmap/tmap/commit/4e7f35d084881497455e3e2dec7a24a93751fb45
. I've reused `st_rgb`. See

See this script https://github.com/r-tmap/tmap/blob/master/sandbox/vv2.R, which we should convert to vignette(s).
