### ISSUE TITLE
tm_scale_continuous_log not allowing other color palettes

### ISSUE THREAD

**Issue by vtspaid** [r-tmap/tmap#911]
I'm new to tmap so there is probably something obvious that I'm doing wrong but it seems I'm not able to change the color palette of the map when using tm_scale_continuous_log. I also thought that setting the trans argument in tm_scale_continuous would have the same effect as tm_scale_continuous_log but it seems to have no effect at all.

You can see in the following example that the first two plots have the correct color palette but are not on a log scale. The third map is on a log scale but it goes back to the default color.

library(tmap)
library(afrilearndata)

tm_shape(africountries) +
  tm_polygons("gdp_md_est",
              fill.scale = tm_scale_continuous(values = "brewer.oranges"))

tm_shape(africountries) +
  tm_polygons("gdp_md_est",
              fill.scale = tm_scale_continuous(values = "brewer.oranges"),
              trans = "log")

tm_shape(africountries) +
  tm_polygons("gdp_md_est",
              fill.scale = tm_scale_continuous_log(values = "brewer.oranges"),
              trans = "log")

**Comment by mtennekes** [comment]
Thx @vtspaid!  should be working now (let me know if not)

**Comment by vtspaid** [comment]
It's working, thanks for the quick fix
