### ISSUE TITLE
The end of the world ... how to deal with it?

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#929]
One of the very few features in v3 that is not (yet) in v4:

```r
tm_shape(World, projection = "+proj=eck4") + tm_polygons() + tm_style("natural")
```

![image](https://github.com/user-attachments/assets/7d70a678-fd64-48f7-9b5d-43f3ba1dcd13)

This `"natural"` style has a tmap option `earth.boundary` set to `TRUE`.

The v3 implementation is beyond ugly, so I'm looking for a more elegant solution. The main problem was/is that the 'boundary' of the earth is not simply the longlat bounding of -180 - 180 and -90 - 90. A crs with the center at the Pacific or at one of the poles has different earth boundaries.

Does someone know an elegant solution to find the outline of a crs? @Nowosad @edzer @mdsumner

**Comment by edzer** [comment]
Is this not an issue that could/would be solved at the level of PROJ?

**Comment by mdsumner** [comment]
gdal_footprint looks pretty good

```R
library(terra)
r <- project(setValues(rast(), 1), "+proj=eck4")
writeRaster(r, tf <- tempfile(fileext = ".tif"), overwrite = TRUE)
system(sprintf("gdal_footprint %s %s", tf, out <- tempfile(fileext = ".fgb")))

plot(vect(out))

```

I tried running that with the osgeo.gdal api but don't really have the fortitude for that rn.

**Comment by mtennekes** [comment]
Nice pragmatic approach @mdsumner 

In the PROJ issue the function `proj_trans_bounds` was suggested. Is this function available or could this become available in one of the r-spatial packages (`sf`, `PROJ`, ...)?

**Comment by mdsumner** [comment]
Certainly in PROJ, I'll have a try at some point, but don't have much capacity atm.

**Comment by edzer** [comment]
See https://github.com/r-spatial/sf/issues/2415
```r
> st_bbox(st_as_stars()) |> st_transform("+proj=eck4")
     xmin      ymin      xmax      ymax 
-16921203  -8460601  16921203   8460601 
...
> st_bbox(vect(out))
     xmin      ymin      xmax      ymax 
-16921203  -8424632  16908719   8460601 
```
Or the longer path:
```r
> st_bbox(st_as_stars()) |> 
    st_as_sfc() |> 
    st_set_crs(NA) |> 
    st_segmentize(1) |> 
    st_set_crs("OGC:CRS84") |> 
    st_transform("+proj=eck4") -> x
> st_bbox(x)
     xmin      ymin      xmax      ymax 
-16921203  -8460601  16921203   8460601 
```
where the hoop through `NA_crs_` is needed to get the zero distance lines at the poles.

**Comment by mdsumner** [comment]
I didn't think that was what was being asked (right?), and I think Even misunderstood too. I was surprised to see that proj_trans_bounds returns just the 4 numbers. Confirmed with 

```R
library(reticulate)
pyproj <- import("pyproj")

## I have to fix this somewhere back up
pyproj$datadir$set_data_dir("/usr/local/share/proj")
trans <- Transformer$from_crs("EPSG:4326", "+proj=eck4")
trans$transform_bounds(left = -180, bottom = -90, right = 180, top = 90, direction = proj$enums$TransformDirection$FORWARD)

[[1]]
[1] -8460601

[[2]]
[1] -8323299

[[3]]
[1] 8460601

[[4]]
[1] 8323299
``` 

It's the same as raster::projectExtent and reproj::reproj_extent, it's not the visible region boundary, just a fleshed out projected extent.

**Comment by mtennekes** [comment]
Yes, that is correct @mdsumner : I'm looking for the visible boundary, expecting a polygon rather than a box.

**Comment by edzer** [comment]
```r
st_bbox(st_as_stars()) |> 
    st_as_sfc() |> 
    st_set_crs(NA) |> 
    st_segmentize(1) |> 
    st_set_crs("OGC:CRS84") |> 
    st_transform("+proj=eck4") |> 
    plot(axes = TRUE)
```
![x](https://github.com/user-attachments/assets/f98015d1-5003-48ce-bac4-c2a315045d8f)

**Comment by mdsumner** [comment]
also @mtennekes I can't see how to distinguish the edge of the world from NA, in your above example there are missing values literally outside the boundary which is convenient for the footprint approach, but here for example the NAs are just arbitrarily applied

```R
library(terra)
r <- rast("/vsicurl/https://noaadata.apps.nsidc.org/NOAA/G02135/south/daily/geotiff/2024/08_Aug/S_20240823_concentration_v3.0.tif")
pts <- reproj::reproj_xy(xyFromCell(r, 1:ncell(r)), "EPSG:4326", source = crs(r))

r[pts[,2] > -50] <- NA
writeRaster(r, tf <- tempfile(fileext = ".tif"), overwrite = TRUE)
system(sprintf("gdal_footprint %s %s", tf, out <- tempfile(fileext = ".fgb")))

plot(vect(out))
```

and, there are many projections that will simply repeat (it goes out to some factor of pi I noticed, and it's not symmetric in each direction but I'm not sure). So I'm not sure the question is entirely well defined. 

this for example, it's nice that the warper now does this, but I think you're asking for a boundary that doesn't always exist, although I think you could reasonably expect something. 🙏

```R
library(terra)
dsn <- "/vsicurl/https://gebco2023.s3.valeria.science/gebco_2023_land_cog.tif"
r <- project(rast(dsn), rast(ext(c(-1, 1, -1, 1) * 5e7), ncols = 1024, nrows = 1024, crs = "+proj=omerc +lonc=147 +alpha=15"), by_util = TRUE)
plot(r)
```

![image](https://github.com/user-attachments/assets/75a27ebe-67ec-4bd0-93b7-27ca26d8586f)

**Comment by mtennekes** [comment]
> ```r
> st_bbox(st_as_stars()) |> 
>     st_as_sfc() |> 
>     st_set_crs(NA) |> 
>     st_segmentize(1) |> 
>     st_set_crs("OGC:CRS84") |> 
>     st_transform("+proj=eck4") |> 
>     plot(axes = TRUE)
> ```
> 
> ![x](https://private-user-images.githubusercontent.com/520851/363194751-f98015d1-5003-48ce-bac4-c2a315045d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjk4MjYsIm5iZiI6MTcyNTAyOTUyNiwicGF0aCI6Ii81MjA4NTEvMzYzMTk0NzUxLWY5ODAxNWQxLTUwMDMtNDhjZS1iYWM0LWMyYTMxNTA0NWQ4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxNDUyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTMwOTM5YTcyNDljMmNhNzRkNjUzNTE2MDMyYzQ3ZjNjOGZmMmI4YjJmZmY0MTI5YjlmMzk1MmRiMWQzOGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IxFJk9RXxDFrAL4J6MNuIBdXO3kzy3uA4K3JdBAdc20)

Thx @edzer Something along these lines would be sufficient for compatibility with tmap3. However, a test with EPSG 3035 wasn't successful yet:

```r
EU = st_transform(World, crs = 3035)

poly = st_bbox(st_as_stars()) |> 
	st_as_sfc() |> 
	st_set_crs(NA) |> 
	st_segmentize(1) |> 
	st_set_crs("OGC:CRS84") |> 
	st_transform(3035) |> 
	st_as_sf()

tm_shape(EU) + 
	tm_polygons() +
	tm_shape(poly) +
	tm_borders(col = "purple", lwd = 3)
```

![image](https://github.com/user-attachments/assets/ba36c87c-0832-478e-b12d-81ab746dee94)

Yes @mdsumner I'm fully aware that not every crs has such a visible boundary (not even WGS84/Mercator)

**Comment by DOSull** [comment]
```Yes @mdsumner I'm fully aware that not every crs has such a visible boundary (not even WGS84/Mercator)``` 

_Especially_ not Mercator! 

A `tmap` function that resolved this problem for even a fraction of common world projections would be a major achievement as it's very hard problem. A solution requires inferring for any given projection what it's boundary conditions look like. There simply isn't going to be a one-size fits all answer for that problem, at any rate not a simple one at the level I assume you are hoping for.

Finite cyclindrical rectangular projections or even pseudo-cylindrical projections, if you know their central meridian, would allow a solution similar to @edzer's with the great circle appropriately modified, but in many cases the underlying projection will be making such a mess of the world map that colouring in the 'world footprint' appropriately is the least of your problems!

    World$geometry |> st_transform("+proj=moll +lon_0=120") |> plot()

![image](https://github.com/user-attachments/assets/52174d81-5d1a-409b-9573-40a0460ae19e)

That's a simple central meridian shift. Once you start working with oblique forms and shifting projection centres things get even messier. It's a problem that `d3` does a much better job of than `proj`, but that implies a major overhaul of `proj` and even how we approach geospatial data!

If you do figure out an approach, sing it from the rooftops!

**Comment by edzer** [comment]
An attempt to cut out the visible part for orthographic projections is found [here](https://r-spatial.org/book/08-Plotting.html#sec-transform), but I'd admit it's pretty ugly.

**Comment by mdsumner** [comment]
Mercator is the least of the problem, today the problem lies in phonies preventing others learning with specious "correctness". Oh well at least there's terra and no one in python is buying this bs

**Comment by mdsumner** [comment]
I'll admit... why don't you just say that you don't know. Let conversation occur

**Comment by mtennekes** [comment]
I've integrated Edzers solution 

> ```r
> st_bbox(st_as_stars()) |> 
>     st_as_sfc() |> 
>     st_set_crs(NA) |> 
>     st_segmentize(1) |> 
>     st_set_crs("OGC:CRS84") |> 
>     st_transform("+proj=eck4") |> 
>     plot(axes = TRUE)
> ```

into tmap4, which works well for many standard pseudo-cyclindrical projections. That makes it backwards compatible with tmap3, which is in this stadium sufficient. Later, we can see if other projections families (e.g. orthogonal) can be supported as well.



```r
world_projs = 
  c("wintri", 
     "robin", 
    paste0("eck", 1:6), 
    "moll", 
    paste0("wag", 1:7), "eqearth")

tms = lapply(world_projs, function(p) {
	tm_shape(World, crs = paste0("+proj=", p)) + tm_polygons() + tm_style("natural") + tm_title(p)
})
do.call(tmap_arrange, c(tms, list(ncol= 4)))
```

![Rplot](https://github.com/user-attachments/assets/6ecb3f29-c749-4a29-b827-32652b8c6557)
