### ISSUE TITLE
Error in valid.viewport(x, y, width, height, just, gp, clip, mask, xscale

### ISSUE THREAD

**Issue by anjelinejeline** [r-tmap/tmap#935]
Hello, 
I am trying to plot the ADM2 shapefile that can be found here https://www.geoboundaries.org/globalDownloads.html
However I am facing this error 
```
Error in valid.viewport(x, y, width, height, just, gp, clip, mask, xscale,  : 
  invalid 'xscale' in viewport
In addition: Warning message:
The shape World is invalid. See sf::st_is_valid
```
I tried fixing it with tmap_options(check.and.fix = TRUE) and sf_use_s2(FALSE) but none of them worked. 
I read that others faced similar issues https://github.com/r-tmap/tmap/issues/606
But I cannot understand what the problem is in my case given that I can plot it with the [plot](https://r-spatial.github.io/sf/articles/sf5.html) function of sf.

**Comment by anjelinejeline** [comment]
Hello @mtennekes  I am using version 3.3.-4, 
how do you suggest I fix the issue? I really would like to use tmap to make maps instead of other packages.. 

Also, in general I am really struggling with using tmap lately .. some functions seem not work . 
Eg. I am using tm_dots in my code but the arguments related to the title and palette are ignored. 
When I run this simple code 

```
   tm_shape(EIOS_sf) +
   tm_dots(col = "disease", palette="set1", title = "Disease") +
  tm_facets("YearMonth")
```

I get this 
```
── tmap v3 code detected ────────────────────────────────────────────────────────────────
[v3->v4] `tm_dots()`: migrate the argument(s) related to the scale of the visual
variable `fill` namely 'palette' (rename to 'values') to fill.scale = tm_scale(<HERE>).
```
When I change the argument palette to values I still have issue with the title that is ignored. 

I am just wondering whether all these problems are related to the version I am using 

Thanks for your help

**Comment by anjelinejeline** [comment]
Just to continue with the above comment, 
I noticed a very strange behaviour of the package 
If I try to plot the World shapefile from rnaturalearth the plot looks very strange. 
Given all these issues I do believe that there's a problem with the version I am using 

```
World=rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
 tm_shape(World) +

tm_borders(col="black")
Error: Shape contains invalid polygons. Please fix it or set tmap_options(check.and.fix = TRUE) and rerun the plot

tmap_options(check.and.fix = TRUE)
tm_shape(World) +
tm_borders(col="black")
Warning message:
The shape World is invalid. See sf::st_is_valid 
```

![image](https://github.com/user-attachments/assets/e8a5a629-cfc2-402e-b1f2-7a8bd9ad5f3f)

**Comment by mtennekes** [comment]
> Hello @mtennekes I am using version 3.3.-4, how do you suggest I fix the issue? I really would like to use tmap to make maps instead of other packages..
> 
> Also, in general I am really struggling with using tmap lately .. some functions seem not work . Eg. I am using tm_dots in my code but the arguments related to the title and palette are ignored. When I run this simple code
> 
> ```
>    tm_shape(EIOS_sf) +
>    tm_dots(col = "disease", palette="set1", title = "Disease") +
>   tm_facets("YearMonth")
> ```
> 
> I get this
> 
> ```
> ── tmap v3 code detected ────────────────────────────────────────────────────────────────
> [v3->v4] `tm_dots()`: migrate the argument(s) related to the scale of the visual
> variable `fill` namely 'palette' (rename to 'values') to fill.scale = tm_scale(<HERE>).
> ```
> 
> When I change the argument palette to values I still have issue with the title that is ignored.
> 
> I am just wondering whether all these problems are related to the version I am using
> 
> Thanks for your help

The docs are still behind. Without being able to check it should be something like this:

```r
tm_shape(EIOS_sf) +
  tm_dots(
      col = "disease", 
      col.scale = tm_scale(values = "set1"), 
      col.legend = tm_legend(title = "Disease")) +
   tm_facets("YearMonth")
```

**Comment by mtennekes** [comment]
> Just to continue with the above comment, I noticed a very strange behaviour of the package If I try to plot the World shapefile from rnaturalearth the plot looks very strange. Given all these issues I do believe that there's a problem with the version I am using
> 
> ```
> World=rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
>  tm_shape(World) +
> 
> tm_borders(col="black")
> Error: Shape contains invalid polygons. Please fix it or set tmap_options(check.and.fix = TRUE) and rerun the plot
> 
> tmap_options(check.and.fix = TRUE)
> tm_shape(World) +
> tm_borders(col="black")
> Warning message:
> The shape World is invalid. See sf::st_is_valid 
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/145205734/366454407-e8a5a629-cfc2-402e-b1f2-7a8bd9ad5f3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwODcyMDksIm5iZiI6MTcyNjA4NjkwOSwicGF0aCI6Ii8xNDUyMDU3MzQvMzY2NDU0NDA3LWU4YTVhNjI5LWNmYzItNDAyZS1iMWYyLTdhOGJkOWFkNWYzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQyMDM1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjZkMDlmNzZlZWU4OGRmMzMzMmUyYjMzNDZmNDliZDAwM2YwMWY5MWRjNjYyZTFlMzkxY2Y1ZWM4NmYyMDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kDoagacHdfVSZAhVHtXabRdM_pHB10rbfG0gpil1Hs4)



Check this out: https://github.com/r-tmap/tmap/issues/606#issuecomment-2344652187

Instead of using `tmap_options(check.and.fix = TRUE)`, you can do this:

```r
tm_shape(World) +
tm_borders(col="black") +
tm_check_fix()
```

**Comment by anjelinejeline** [comment]
> ```r
>   tm_dots(
>       col = "disease", 
>       col.scale = tm_scale(values = "set1"), 
>       col.legend = tm_legend(title = "Disease")) +
>    tm_facets("YearMonth")
> ```

@mtennekes  this actually works.. when are the docs planned to be updated?

**Comment by mtennekes** [comment]
Docs: don't know yet, I'm still working to make v4 as stable as possible.
For the time being: there is an excellent chapter about tmap4 in https://r.geocompx.org/adv-map

Apologies, it had to be 'fill' instead of 'col'. (This is a breaking change with v3 which we had to do to make the visual variables consistent across different layers: in v4, col is only used for lines and fill for areas)

```r
  tm_dots(
      fill = "disease", 
      fill.scale = tm_scale(values = "set1"), 
      fill.legend = tm_legend(title = "Disease")) +
   tm_facets("YearMonth")
```
