### ISSUE TITLE
Use tm_title across facets

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#940]
Seems not possible yet...

Use case: series of maps (for animation) when panel.labels are not desirable (#937)

**Comment by Rapsodia86** [comment]
And how to get rid of this title now? I did a package update and now I have the name of the variable used in tm_polygons(fill="%sig2", .....)  on top of the map. Looks like from facet, but in this script there is no facet. #937

**Comment by mtennekes** [comment]
With the latest commit, I get this, so without panel:

![image](https://github.com/user-attachments/assets/eecc2f47-1f6e-4528-9869-4e1caf43232a)

**Comment by mtennekes** [comment]
Already fixed earlier:

```r
tm_shape(World) +
  tm_polygons(c("HPI", "well_being")) + 
  tm_title(c("Happy Planet Index", "Well Being"), position = tm_pos_in("right", "top"), bg.color = "gold", frame = T) + 
  tm_layout(panel.show = FALSE)
```

![image](https://github.com/user-attachments/assets/c8929924-58c0-469e-8c6c-e151b742e967)
