### ISSUE TITLE
panels: when to use (by default)?

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#941]
Related to #940

Panel labels can now always be turned off or on by the `panel.show` argument of `tm_layout`

The question for now: are you happy with these defaults?

``` r
library(tmap)
#> 
#> Attaching package: 'tmap'
#> The following object is masked from 'package:datasets':
#> 
#>     rivers
############################
###### Single map
############################
# default: no panels
tm_shape(World) +
    tm_polygons("HPI")
```

![](https://i.imgur.com/uPusAQH.png)

``` r
# with
tm_shape(World) +
    tm_polygons("HPI") +
    tm_layout(panel.show = TRUE)
```

![](https://i.imgur.com/FzpRwoI.png)

``` r
############################
###### Facets defined with multiple variables
############################
# default: with panels
tm_shape(World) +
    tm_polygons(c("HPI", "footprint"))
```

![](https://i.imgur.com/d9q3d2r.png)

``` r
# without
tm_shape(World) +
    tm_polygons(c("HPI", "footprint")) +
    tm_layout(panel.show = FALSE)
```

![](https://i.imgur.com/uLPjOxx.png)

``` r
# default: with panels
tm_shape(World) +
    tm_polygons("HPI") +
    tm_facets("continent")
```

![](https://i.imgur.com/s2BkH7I.png)

``` r
############################
###### Facets defined with multiple variables, single pages
############################
# default: without
tm_shape(World) +
    tm_polygons(c("HPI", "footprint")) +
    tm_facets_pagewise()
```

![](https://i.imgur.com/ccgtrWS.png)![](https://i.imgur.com/KsCtQwb.png)

``` r
# with
tm_shape(World) +
    tm_polygons(c("HPI", "footprint")) +
    tm_facets_pagewise() +
    tm_layout(panel.show = TRUE)
```

![](https://i.imgur.com/NEKN8UH.png)![](https://i.imgur.com/UGsDRLs.png)

``` r
############################
###### Facets defined with 'by' variable
############################
# default: with
tm_shape(World) +
    tm_polygons("HPI") +
    tm_facets("continent")
```

![](https://i.imgur.com/NSg97Px.png)

``` r
# without
tm_shape(World) +
    tm_polygons("HPI") +
    tm_facets("continent") +
    tm_layout(panel.show = FALSE)
```

![](https://i.imgur.com/AlAvjwP.png)

``` r
############################
###### Facet grid
############################
# default: with panels
tm_shape(World) +
    tm_polygons("HPI") +
    tm_facets_grid("continent", "economy")
```

![](https://i.imgur.com/vDqXefW.png)

``` r
# without
tm_shape(World) +
    tm_polygons("HPI") +
    tm_facets_grid("continent", "economy") +
    tm_layout(panel.show = FALSE)
```

![](https://i.imgur.com/5PE53iM.png)

<sup>Created on 2024-09-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Imho, the only case in which panels could not be shown by default is the case of multiple variables (third image above). What do you think @Nowosad @Rapsodia86 @olivroy ?

I've also committed this script here https://github.com/r-tmap/tmap/blob/master/tests/testing_panels.Rmd

**Comment by Nowosad** [comment]
@mtennekes would not it be better if the `tm_facets_pagewise` also return the panel titles. I can think of two reasons for that:

1. All of the facet types would return panel titles by default (so -- consistency)
2. `tm_facets_pagewise` may be used for animations, and then panel titles are often neccesary

**Comment by Rapsodia86** [comment]
I agree with @Nowosad that consistency is important. Whenever any type of tm_facets_ is called, panels should to be visible. I would think that is a logical expectation. 

But I understand you point in case of pagewise. Maybe then, move it to a separate function and name `tm_pagewise()` so maps are shown without a title as default? 

In general, I do like the option to turn panels on/off regardless of a case! Great! Thank you very much:)

**Comment by mtennekes** [comment]
Thx for your input @Nowosad and @Rapsodia86 
I've changed the default: now panels are always visible.

A function `tm_pagewise` would be confusing I guess, same for `tm_pages`. (Because they are still facets, but printed on different pages.)

I also thought about adding a `panel.show` argument to `tm_facets_x`, but prefer not to, because this breaks the tmaps 'grammar of graphics' principles (`tm_facets` is just to define the facets, and has nothing to do with the plotting).

With the `tm_layout(panel.show = FALSE)` option it is good enough (otherwise feel free to reopen this issue)
