### ISSUE TITLE
Collecting indirectly specified arguments not working (!)

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#950]
```r
# works
tm_shape(World, projection = "+proj=robin") +
	tm_polygons()

# does not work
projection = "+proj=robin"
tm_shape(World, projection = projection) +
	tm_polygons()
```

This is caused by `match.call()`. The approach for collecting function arguments is `as.list(match.call(expand.dots = TRUE)[-1])`. For instance `tm_shape`: 

```r
tm_shape = function(shp, 
  bbox = NULL,
  crs = NULL,
  is.main = NA,
  name = NULL,
  unit = NULL,
  filter = NULL,
  ...) {
	args = as.list(match.call(expand.dots = TRUE)[-1])
```

It normally gives me a list with arguments that are explicitly called with their values. However, if arguments are specified indirectly (e.g. via a variable), this variable name is passed through rather than the evaluated value.

Does someone know an elegant way of doing this? Also related: https://rpubs.com/wch/18793 which suggests that also running time can be improved.

I noticed this issue when solving the rev-dep check for `MazamaSpatialPlots` where the v3 argument `projection` is passed on.

**Comment by olivroy** [comment]
We could also ask MazamaSpatialPlots maintainers to update their code to be:

```r
projection <- "+proj=robin"
if (packageVersion("tmap") >= "3.99") {
  tm_shape(World, crs = projection)
} else {
    tm_shape(World, projection = projection)
}
```

**Comment by olivroy** [comment]
Also maybe `rlang::call_match()` works better? https://rlang.r-lib.org/reference/call_match.html?q=match.call#null (probably not)

**Comment by mtennekes** [comment]
Yes, certainly useful, thx. Already implemented in `tm_shape`: 

```r
args_called = names(rlang::call_match()[-1])
args = lapply(as.list(rlang::call_match(defaults = TRUE)[-1]), eval, envir = parent.frame())
```

So args contains the full list, including non-called arguments and also the `...` arguments. And `args_called` just contains the names of the called arguments.

Should be pretty efficient....

**Comment by mtennekes** [comment]
Thx! 

> . I think it is linked to how v3 palettes are resolved.

Backwards compatibility with v3 palettes added (https://github.com/r-tmap/tmap/commit/05bd6c605123cbc773cc09a86b39d60540f51163). Also I've update the messages from https://github.com/r-tmap/tmap/blob/master/R/messages.R. Quite handy this cli package! Could you please review this as I'm new to this package @olivroy ?

The main bug in the MazamaSpatialPlots is not fixed yet. But working on it...

**Comment by mtennekes** [comment]
Fixed! Please check

**Comment by olivroy** [comment]
Looks great! Great work! 

I will take a look at the messages and other things soon!

![image](https://github.com/user-attachments/assets/1590b206-df29-44fc-90c9-70e04f899775)

**Comment by mtennekes** [comment]
Thx! Just changed all other `match.call` to `rlang::call_match`, just for consistency. Hope it's working ok.
