### ISSUE TITLE
Leaflet.glify  JS script-tags injected at wrong position in final HTML page

### ISSUE THREAD

**Issue by knbknb** [r-tmap/tmap#958]
I don't know if this is unique to my machines. Using image ` rocker/geospatial:4.4`, and installing tmap 9002 on that for me option `use.WebGL` seems to be set to TRUE by default, and that cannot be changed. Where does it have to be changed?

Moreover in my final HTML page I get this - the Leaflet.glify are loaded rather early: 

```html
<html> 
<head>
<script src="lib_leaflet/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="lib_leaflet/Leaflet.glify-3.0.1/addGlifyPoints.js">/script>
<script src="lib_leaflet/Leaflet.glify-3.0.1/addGlifyPolygons.js"></script>
<script src="lib_leaflet/Leaflet.glify-3.0.1/addGlifyPolylines.js"></script>
<script src="lib_leaflet/Leaflet.glify-3.0.1/glify-browser.js"></script>
<!-- more third party libs ....
finally...
 --->
<script src="[lib_leaflet/leaflet-binding-2.2.2/leaflet.js"></script>

```

Shortened) 

This creates errors like this in the Browser's devtools console, no points can be drawn:

Uncaught ReferenceError: LeafletWidget is not defined lib_leaflet/Leaflet.glify-3.0.1/addGlifyPoints.js:1
Uncaught ReferenceError: LeafletWidget is not defined lib_leaflet/Leaflet.glify-3.0.1/addGlifyPolygons.js:1
Uncaught ReferenceError: LeafletWidget is not defined  lib_leaflet/Leaflet.glify-3.0.1/addGlifyPolylines.js:1

When I manually change the  order of the `<script>` elements the errrors go away.  

Putting `leaflet-binding-2.2.2` first, _followed_ by Leaflet.libglfy-3.01 libs:

```html
<script src="lib_leaflet/leaflet-binding-2.2.2/leaflet.js]></script>
<script src="lib_leaflet/Leaflet.glify-3.0.1/addGlifyPoints.js"></script>
<script src="lib_leaflet/Leaflet.glify-3.0.1/addGlifyPolygons.js"></script>
<script src="lib_leaflet/Leaflet.glify-3.0.1/addGlifyPolylines.js"></script>
<script src="lib_leaflet/Leaflet.glify-3.0.1/glify-browser.js"></script>
```

...Then points are drawn on the tmap/leaflet map .  
It helps to  install the github version of leafgl with dependencies. hHen the order of `script tags` is correct.

but there are still  errors like this . Which are a mystery to me. I'm giving up.

`: this._map is null            lib_leaflet/Leaflet.glify-3.0.1/glify-browser.js`

No Idea if this is tmap's fault, or leafgl's, or htmlwidget's, or rocker-image, or if my customizaiton is wrong.

I'd like to have the good old `addMarker()` function back. Now it seems impossible to get activate that function.

**Comment by mtennekes** [comment]
I'm still looking for a good default regarding when to enable `WebGL`. Probably FALSE by default, because the border are unsharp. But if the number of features is greater than some threshold and if no unsupported visual variable is used), it makes sense to set it to `TRUE`.

Regardless of this default, this should give you the good old symbols/markers:

```r
tm_shape(metro) + tm_symbols() + tm_view(use.WebGL = FALSE)
# or
tm_shape(metro) + tm_markers() + tm_view(use.WebGL = FALSE)
```

Unfortunately I don't know any of the other libraries, so I can't help there. @tim-salabim or @timelyportfolio ?

**Comment by knbknb** [comment]
Thanks, good to know where to put the `use.WebGL`  option.  

A few days later my build script succeeded again, and `add_markers()` reappeared in the transpiled code. The  glify-based code was gone/no longer generated. I don't remember if an external dependency was upgraded in the meantime, or if some cache directory on my PC was purged, or if I changed something in my setup.

I'll close this for now, will come back when I try again (my project where I use tmap  is only a side-hustle)
