### ISSUE TITLE
tm_raster ignoring col_alpha

### ISSUE THREAD

**Issue by alankjackson** [r-tmap/tmap#966]
Running in RStudio 2024.09.0+375, tmap 3.99.9003

The raster seems to ignore alpha, and the layer manager only turns off the legend, not the rasters.

```{r}
foo <- terra::rast(
  nrows=20, ncols=20,
  xmin=-88.4320615142538, xmax=-87.9239294737916,
  ymin=30.1444683138419, ymax=31.1732638929798,
  vals=sample(1:4, 400, replace=TRUE),
  crs="EPSG:4269"
)

tmap::tmap_options(basemap.server = c("OpenStreetMap"))
tmap::tmap_mode("view") # set mode to interactive plots


tmap::tm_shape(foo) + 
  tmap::tm_raster(col_alpha=0.4,
                  col.scale = tmap::tm_scale_categorical(n.max = 4, values = "brewer.blues",
                                                   value.na = "red"),
                  col.legend = tmap::tm_legend(title = "foo"))
```
![image](https://github.com/user-attachments/assets/9d5c09c3-a439-43d7-97f8-a8129639dcb2)

**Comment by mtennekes** [comment]
Thx @alankjackson This is an issue in an upstream package (leafem) that already has been solved. To make it work, please install the dev version of leafem. See also https://github.com/r-tmap/tmap/issues/959
