### ISSUE TITLE
pkgdown figure rendering

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#971]
In the references, e.g.

https://r-tmap.github.io/tmap/reference/tm_facets.html
https://r-tmap.github.io/tmap/reference/tm_polygons.html

![](https://r-tmap.github.io/tmap/reference/tm_polygons-5.png)

![](https://r-tmap.github.io/tmap/reference/tm_facets-2.png)

some legends overlap with maps, strange....

Do you have any idea @olivroy ? I haven't noticed this with any other rmd documents or vignettes

**Comment by olivroy** [comment]
I don't know how to set settings for a single figure. 

We can set globally in _pkgdown.yml. https://pkgdown.r-lib.org/reference/build_reference.html#figures

Do you think some defaults could be tweaked?

**Comment by mtennekes** [comment]
My guess is that is an inconsistency between these settings and the actual renderings. Or it is something with retina, which has impact on the aspect ratio calculations. Or the inconsistency between the ideal aspect ratio given the specified with and fig.asp.

What probably would solve it is to set both the width and height of the figures: the width via these settings, and the height in the chunks.

**Comment by mtennekes** [comment]
@olivroy I've increased the DPI https://github.com/r-tmap/tmap/blob/master/_pkgdown.yml

Already better (sharper) looking images, and no more overlap between legend and map.

However, still some questions left:

* What is the width of the text? I guess 7.2916667 is not chosen without a reason, but the landscape maps still don't fill the total width (e.g. the first map in https://r-tmap.github.io/tmap/articles/05_tmap_facets.html)
* In the documentation, the examples are rendered inside the chunk. Moreover, the aspect ration is funny, images are rendered at width 1050 by height 1699. I've set the DPI to 144, so 1050/144 =7,292 is correct (same as in config file). But the standard aspect ratio of 1.618 (golden ratio) is flipped to portrait, even though the map is clearly landscape. Do you have any clue how to solve this?

**Comment by mtennekes** [comment]
Solved!

Apparently, the figure width and dpi were ignored for the vignettes.

A solution/work around is to have this header in each vignette:

```r
knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%",
  dpi = 300,
  fig.width = 7.2916667,
  comment = "#>"
)
```

My guess is that `_pkgdown.yml` will determine the figures in the references.
