### ISSUE TITLE
Working at FOSS4G Code Sprint, Belem, Brazil

### ISSUE THREAD

**Issue by nickbearman** [r-tmap/tmap#978]
Hi @mtennekes Just to let you know a couple of us are working on tmap bits at FOSS4G, in Belem, Brazil now (for the next ~8 hours or so). I am going to try the [vignettes](https://github.com/r-tmap/tmap/tree/master/vignettes) probably, we'll see how things go. Let me know if you'd like us to look at anything specific.

**Comment by Nowosad** [comment]
Awesome! Have fun @nickbearman!

**Comment by nickbearman** [comment]
Code sprint all done. 
Thanks for your reply to 979
