### ISSUE TITLE
popup.vars not working as expected...

### ISSUE THREAD

**Issue by jkennedyie** [r-tmap/tmap#982]
Hi. tmap4 tm_dots() view mode is not rendering for me after knitting.  #973 
However, where tmap4 tm_dots() view mode does render (e.g. within RStudio), popup.vars is not working as expected:

- popup.vars = FALSE raises an error 
- popup.vars = named list is not overriding the labels

If any other info needed pls shout.

```
---
title: "tmap test"
output: html_document
date: "`r Sys.Date()`"
---

```{r plot}
library(tmap)

# this works:
tmap_mode("plot")
tm_shape(NLD_muni) + tm_dots()

# HTML after knitting does not render any dots for any of the following. That is one issue.
# But even within RStudio, when dots are rendered, there are issue with the popups:

# In RStudio all variables are in popup as expected:
tmap_mode("view")
tm_shape(NLD_muni) + tm_dots()

# this also returns all variables in popup as expected:
tm_shape(NLD_muni) + tm_dots(popup.vars = TRUE)

# this returns an error...but documentation says should prevent popups:
tm_shape(NLD_muni) + tm_dots(popup.vars = FALSE)

# this displays "code" only in popup as expected (in RStudio, nothing in HTML):
tm_shape(NLD_muni) + tm_dots(popup.vars = c("code"))

# this does not override label of code with New Label as expected:
tm_shape(NLD_muni) + tm_dots(popup.vars = c("New Label" = "code"))


```

**Comment by mtennekes** [comment]
- [ ] `popups = FALSE` is working now
- [ ]  fix popup labels
- [ ] work around strange leaflet bug:

I've managed to create a minimal working example with just leaflet of the following problem: markers are not shown when a pane is added. It works in interactive mode, but not in knitted rmd documents. I suspect there is something wrong with the marker URLs (perhaps blocked?)

@tim-salabim any idea how to fix or work around this? 


```

---
title: "leaflet add markers"
output: html_document
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---


```{r leaflet}
library(leaflet)
library(sf)
data("quakes")

leaflet(quakes) |> 
	leaflet::addTiles() |> 
	leaflet::addMarkers()
```


```{r leaflet2}
leaflet(quakes) |> 
	leaflet::addMapPane("tmap401", zIndex = 401) |> 
	leaflet::addTiles() |> 
	leaflet::addMarkers(options = leaflet::pathOptions(pane ="tmap401"))
```

```

**Comment by tim-salabim** [comment]
Not sure, it does render the markers if we add `leaflet-marker-pane` to the pane definition (I've done this in the browser), see screenshot below.

Seems like a leaflet bug to me...

![image](https://github.com/user-attachments/assets/6965d3e1-780c-430b-94f7-642b1cb9e06d)

**Comment by tim-salabim** [comment]
👍🏽 with `addCircleMarkers` it seems to work as expected

**Comment by mtennekes** [comment]
Should be fixed now (`addMarkers` bug still there but leaflet related, `tm_dots` `tm_bubbles` etc now use `addCircleMarkers` by default. This can be changed with the option `use_circle_makers` (via `tm_view` or `tm_options` or `tmap_options`).

Please check @jkennedyie

**Comment by tim-salabim** [comment]
Is it worth raising this as an issue in leaflet?

**Comment by jkennedyie** [comment]
All bugs that I detected seem fixed in latest version - thank you/JK
