### ISSUE TITLE
Turning off legends with `NULL`?

### ISSUE THREAD

**Issue by Robinlovelace** [r-tmap/tmap#983]
I've just tried turning off the line width legend as follows:

```r
m = tm_shape(rnet_walking_cycling_stratford) +
  tm_lines(
    col = "lts",
    palette = "-viridis",
    lwd = "count",
    lwd.legend = NULL,
    scale = 9
  ) +
  tm_facets("mode")
tmap_mode("plot")
m
```

The legend persists (the image shows why I'd like it turned off in this case):

![image](https://github.com/user-attachments/assets/67f1b763-f090-41fb-acc3-82eb21a8f8a7)

**Comment by Robinlovelace** [comment]
Even when `show = FALSE` is set in `tm_legend()` it shows:

```
m = tm_shape(rnet_walking_cycling_stratford) +
  tm_lines(
    col = "lts",
    palette = "-viridis",
    lwd = "count",
    lwd.legend = tm_legend(show = FALSE),
    scale = 9
  ) +
  tm_facets("mode")
tmap_mode("plot")
m
```

Not sure if that's a bug but was not expected, apologies for lack of reprex, tested on dev version of `tmap`.

**Comment by mtennekes** [comment]
`tm_legend_hide()`

But I agree that `lwd.legend = NULL`, and probably also `show = FALSE` should work.

**Comment by mtennekes** [comment]
These three methods should work now:

```r
tm_shape(World) + tm_polygons("HPI", fill.legend = tm_legend_hide())
tm_shape(World) + tm_polygons("HPI", fill.legend = tm_legend(show = FALSE))
tm_shape(World) + tm_polygons("HPI", fill.legend = NULL)
```

Let me know it that works with your data @Robinlovelace 

Also: which one should we teach?

**Comment by Robinlovelace** [comment]
After first try not working but I likely messed something up. More soon..

**Comment by Robinlovelace** [comment]
Apologies, no time this week. For a quick reprex there can be:

- [ ] Linestring input with at least 2 fields (numeric/character)
- [ ] `lwd` and `col` arguments
- [ ] Testing of turning off one or both `lwd.legend` and `col.legend`

**Comment by mtennekes** [comment]
This one works:

```r
tm_shape(rivers) +
	tm_lines(lwd = "strokelwd", col = "type", col.legend = NULL, lwd.legend = NULL)
```

(Still looking to replace `rivers` for tmap4; suggestions of other linestring data welcome)

**Comment by mtennekes** [comment]
Any follow up @Robinlovelace ? For a MWE you could also post `dput(head(rnet_walking_cycling_stratford))`

**Comment by Robinlovelace** [comment]
Will test now, perfect timing as I'm working on the project with the example now. 

Before: 

![image](https://github.com/user-attachments/assets/ed2165d0-5d20-4c94-8a40-9c191a25648f)

**Comment by Robinlovelace** [comment]
Source:

``` r
m = tm_shape(rnet_walking_cycling_stratford) +
  tm_lines(
    col = "lts",
    palette = "-viridis",
    lwd = "count",
    lwd.legend = tm_legend(show = FALSE),
    scale = 9
  ) +
  tm_facets("mode")
tmap_mode("plot")
m
```

**Comment by Robinlovelace** [comment]
After: same legend, unwanted line width legend elements still there, after trying this syntax:

```r
m = tm_shape(rnet_walking_cycling_stratford) +
  tm_lines(
    col = "lts",
    palette = "-viridis",
    lwd = "count",
    lwd.legend = NULL,
    scale = 9
  ) +
  tm_facets("mode")
```

**Comment by Robinlovelace** [comment]
Reprex: incoming!

**Comment by Robinlovelace** [comment]
Basically: it's due to v3 compatibility mode triggered by `scale =`. So fixed for me!

**Comment by mtennekes** [comment]
Is this solved @Robinlovelace ?

**Comment by Robinlovelace** [comment]
Yes, hence closing the issue 👍
