### ISSUE TITLE
Object `x1` not found error in `tm_scale_intervals(label.format)`

### ISSUE THREAD

**Issue by olivroy** [r-tmap/tmap#984]
From example in https://github.com/r-tmap/tmap/issues/930#issuecomment-2338971622

Here is a similar once that errors

```r
NLD_muni |> 
	tm_shape() +
	tm_polygons(
		fill = "population", fill.scale = tm_scale_intervals(label.format = scales::label_dollar()))
#> Erreur dans fancy_breaks(vec = c(1, 200001, 400001, 600001, 800001, 1000001 : 
#>   objet 'x1' introuvable
```

**Comment by mtennekes** [comment]
Fixed.

What do you think about the labels?

![image](https://github.com/user-attachments/assets/9735e80f-9211-4348-a760-b3c02e220403)


`tm_scale_intervals` contains a parameter `as.count` which is set to TRUE if the data variable is an integer. In this case it is, but somehow it doesn't make sense in this case. It would for instance make sense it the variable would be `number_of_wolfs_spotted`. 

Suggestions to improve this default? Perhaps simply `as.count = FALSE` ? @Nowosad ?

**Comment by olivroy** [comment]
> tm_scale_intervals contains a parameter as.count which is set to TRUE if the data variable is an integer. In this case it is, but somehow it doesn't make sense in this case. It would for instance make sense it the variable would be number_of_wolfs_spotted.

Great that you figured out why it was wrong. I would have never guessed this was the issue.

Probably that a default of `as.count = TRUE` is not accurate enough for integer values. I agreee with you that the default should be `FALSE` in most cases

**Comment by olivroy** [comment]
@mtennekes I just re-ran my code with current main:

```r
World |> 
	tm_shape() +
	tm_polygons(
		fill = "HPI", legend = tm_legend(title = "xa", design = "standard", title.color = "orange", bg.color = "purple", show = T), id = "name",
		fill.scale = tm_scale_intervals(label.format = scales::label_dollar()),
	)

```

And the legend color is not respected. In both view mode and plot mode (expecting font color for legend title orange and background color to be purple)

![image](https://github.com/user-attachments/assets/daa39532-d280-4a0d-8963-477cfd9a790a)

**Comment by mtennekes** [comment]
There is an error in your code: `legend` should be `fill.legend`.
Pls test my latest commit, which provides informative messages.

**Comment by mtennekes** [comment]
as.count now by default FALSE
