### ISSUE TITLE
tm_credits for tm_facets 

### ISSUE THREAD

**Issue by Rapsodia86** [r-tmap/tmap#986]
Hi @mtennekes,
I would like to add a caption to the bottom right corner of my map with facets, but I am not quite sure how?

Example:
```
library(tmap) #3.99.9002
tm_shape(NLD_muni) +
  tm_polygons("pop_men",
              fill.scale = tm_scale_intervals(values = "pu_gn", style = "kmeans", n = 7)) +
  tm_facets_wrap(by = "province")
```
![image](https://github.com/user-attachments/assets/9b43b953-f3ed-4f38-8dc9-152efd2c89d2)

and if I add tm_credits():
```
library(tmap)
tm_shape(NLD_muni) +
  tm_polygons("pop_men",
              fill.scale = tm_scale_intervals(values = "pu_gn", style = "kmeans", n = 7)) +
  tm_facets_wrap(by = "province")+
  tm_credits("TEST CREDITS",position = c("right", "bottom"))
```
![image](https://github.com/user-attachments/assets/b8d5b1cc-1cac-481b-a1f0-9ad8ec0cac41)

Here is what I would like to get (thx Paint 3D 😄)? Did I miss some parameter or a function? 
Thanks! 
![image](https://github.com/user-attachments/assets/dfac472f-fe55-44ca-a8fb-94cda5beea2d)

**Comment by Nowosad** [comment]
I do not know if this is a best solution, but you can do `, position = tm_pos_out()`

``` r
library(tmap)
#> Warning: no function found corresponding to methods exports from 'raster' for:
#> 'area', 'gridDistance'
#> 
#> Attaching package: 'tmap'
#> The following object is masked from 'package:datasets':
#> 
#>     rivers
tm_shape(NLD_muni) +
  tm_polygons("pop_men",
              fill.scale = tm_scale_intervals(values = "pu_gn", style = "kmeans", n = 7)) +
  tm_facets_wrap(by = "province")+
  tm_credits("TEST CREDITS", position = tm_pos_out())
```

![](https://i.imgur.com/Kx7C0zt.png)

**Comment by Rapsodia86** [comment]
Thanks, @Nowosad , for the suggestion!
In my original plot, I do have many more things in the legend (and the number differs depending on a dataset), so I would prefer to have it outside at a fixed position. Thus, when I put two plots with different legends next to each other, the credits/captions would be consistently in the same spot!

**Comment by mtennekes** [comment]
First off topic: did you both use an older version of `NLD_muni`? Because `"pop_men"` has been removed from the new updated data (https://github.com/r-tmap/tmap/issues/967#issuecomment-2507580696)

On topic:

```r
tm_shape(NLD_muni) +
	tm_polygons("pop_0_14",
				fill.scale = tm_scale_intervals(values = "pu_gn", style = "kmeans", n = 7)) +
	tm_facets_wrap(by = "province")+
	tm_credits("TEST CREDITS", position = tm_pos_out(pos.h = "right", pos.v = "bottom"))
```

![image](https://github.com/user-attachments/assets/0efaedb0-6f2e-4db2-bc17-ef61dd75f144)

Take a look at https://r-tmap.github.io/tmap/reference/tm_pos.html#details and let me know it is it clear? I'am planning to write a vignette about this, because it needs some understanding.

In this plot, legends are plotted in the cell.h="right", cell.v="center" (this is determined automatically based on aspect ratio).

In this case, you want to print the credits text in the same cell, but not attached to the top, but to the bottom. That is where `pos.v="bottom"` comes into play

**Comment by Rapsodia86** [comment]
@mtennekes 
Is there a way to make additional adjustments by e.g. providing +/- pnt to make extra shift?
I would like to have those credits at the same level as the facet panels in the upper row, but I cannot make it happen 🙃 

tm_shape(NLD_muni) +
  tm_polygons("pop_0_14",
              fill.scale = tm_scale_intervals(values = "pu_gn", style = "kmeans", n = 7),
              fill.legend =  tm_legend(position = tm_pos_out(pos.v= "center"))) +
  tm_facets_wrap(by = "province")+
  tm_credits("TEST CREDITS", fontface="italic", position = tm_pos_out(pos.h = "right", pos.v = "top"))

![image](https://github.com/user-attachments/assets/4de187a1-d974-4ebd-a665-01d470657075)

tm_shape(NLD_muni) +
  tm_polygons("pop_0_14",
              fill.scale = tm_scale_intervals(values = "pu_gn", style = "kmeans", n = 7),
              fill.legend =  tm_legend(position = tm_pos_out(pos.v= "center"))) +
  tm_facets_wrap(by = "province")+
  tm_credits("TEST CREDITS", fontface="italic", position = tm_pos_out(cell.v="top",pos.h = "right", pos.v = "bottom"))

![image](https://github.com/user-attachments/assets/9cee2008-c7b9-46b5-9df3-5560f1e62765)
