### ISSUE TITLE
Interactive viewing tmap object in vscode terminal over remote SSH

### ISSUE THREAD

**Issue by lmwang9527** [r-tmap/tmap#987]
Not sure this is the right place for this, but just in case it'd helpful to anyone running into similar situation. I use vscode (and its variants) to do work on my server over remote-SSH. Oftentimes, I want to view interactive maps created used tmap in vscode Terminal (R or radian), but the maps would not show up in vscode Viewer tab. (mapview works out of the box for this use case.) I figured out a solution (with the help of Claude) by setting the viewer option:

```{R}
options(viewer = function(url, ...) {
    # Extract the directory path from the URL
    dir_path <- dirname(gsub("file:///", "", url))
    # Start the server in that directory
    servr::httd(dir = dir_path, port = 4321, daemon = TRUE)
    # Open the file in browser using the server URL
    file_name <- basename(url)
    browseURL(paste0("http://localhost:4321/", file_name))
})
```

You can put it in .Rprofile with a check for interactive session and vscode terminal: `if (interactive() && Sys.getenv("TERM_PROGRAM") == "vscode") {...}`

**Comment by mtennekes** [comment]
Never worked with VSC myself, but tested both tmap and mapview.

I noticed that (without your solution) tmap runs quick in plot mode, but in view mode it takes a while before the interactive map is shown (it does appear, but after half a minute or so). You solution works, but only once. After the second interactive map: "createTcpServer: address already in use" and "Error in initialize(...) : Failed to create server"

mapview works instantly, with a message "Browsing http://127.0.0.1:5540".

@tim-salabim any experience with this?

**Comment by tim-salabim** [comment]
IIRC @MilesMcBain implemented the viewer for vsc. Should be defined in the print method. Its defined here
https://github.com/r-spatial/mapview/blob/master/R/print.R

**Comment by mtennekes** [comment]
Now working! Please test @lmwang9527 

Copied this code from mapview; @tim-salabim and @MilesMcBain thanks a lot. Shall I include you in the authors-contributors list of tmap?

Side problem: now we have 21 packages in the imports, 1 above the maximum allowed by CRAN. `servr` is added.
Anything we can do to reduce this list? Will open new topic.

**Comment by lmwang9527** [comment]
Yes, tmap interactive maps now work perfectly without need to do anything on my end. Thanks!
