### ISSUE TITLE
Too many packages in Imports

### ISSUE THREAD

**Issue by mtennekes** [r-tmap/tmap#988]
As of the fix #987, we now have too many packages in the imports.

Any suggestions?

Of course, I can migrate the 'view' mode to a new package `tmap.view`. But there may be easier solutions. Ideas?

**Comment by tim-salabim** [comment]
Second @Nowosad 's approach of moving things to suggests. E.g. `leafsync` or maybe `cli` (though I'm not sure how much refactoring that would mean)? Also, I just saw that in mapview we have `methods` in depends...

**Comment by mtennekes** [comment]
Also thought about moving packages to 'depends' to bypass this limit 🤣 Actually, I see that tmaptools also has `methods` in the depends....

Moving any of the leafX packages to suggests can be done, but not ideal because they are all part of the view mode.

Would it be possible somehow to migrate the view mode to a new package called `tmap.view`, and put this package into Imports? 🤔

**Comment by Nowosad** [comment]
Also maybe the itsdepends package could help here to make decisions:

``` r
# devtools::install_github("jimhester/itdepends")
library(itdepends)
library(dplyr)
all_f = itdepends::dep_usage_pkg("tmap")

all_f |>
    group_by(pkg) |>
    count() |>
    arrange(n)
#> # A tibble: 37 × 2
#> # Groups:   pkg [37]
#>    pkg             n
#>    <chr>       <int>
#>  1 av              1
#>  2 gifski          1
#>  3 widgetframe     1
#>  4 leafsync        2
#>  5 maptiles        2
#>  6 png             2
#>  7 rstudioapi      2
#>  8 cartogram       3
#>  9 colorspace      3
#> 10 leafem          3
#> # ℹ 27 more rows
```

**Comment by tim-salabim** [comment]
> Would it be possible somehow to migrate the view mode to a new package called tmap.view, and put this package into Imports?

I guess that highly depends on the internal of tmap and how much code duplication is needed for splitting the view from the plot mode codebase

**Comment by mtennekes** [comment]
> My thinking was to move servr to suggests (as it seems to be useful only for v. specific cases).

Also an options, although it is now used in two cases: VScode and in case `options(viewer = NULL)`  (or equivalently with the new tmap option `tmap_options(use_browser = TRUE)`)

https://github.com/r-tmap/tmap/blob/42ff35b907a58a673adf2a9b1f09534e4c0bcdd3/R/tmapLeafletRun.R#L93C4-L115C5

Or is there an alternative? (I'm not so familiar with these kind of tools)

**Comment by tim-salabim** [comment]
I think you need `servr` to properly serve the page as the `file:///` browsing is problematic in some scenarios (though I also don't know too much about these things). I can only say that this has been a smooth solution for mapview for quite some time now.

**Comment by mtennekes** [comment]
https://github.com/r-tmap/tmap/pull/990
