### ISSUE TITLE
tm_credits() fontface does not work?

### ISSUE THREAD

**Issue by Rapsodia86** [r-tmap/tmap#991]
It looks like that `fontface` parameter is not respected in tm_credits? 

I have updated to 3.99.9003

```
tm_shape(NLD_muni) +
  tm_polygons("pop_0_14",
              fill.scale = tm_scale_intervals(values = "pu_gn", n = 7)) +
  tm_facets_wrap(by = "province")+
  tm_credits("Test credits", fontface="italic", position = tm_pos_out(pos.h = "right", pos.v = "bottom"))
```

![image](https://github.com/user-attachments/assets/ea8a74ca-552a-4967-8ed0-9be1a53c4e53)

```
tm_shape(NLD_muni) +
  tm_polygons("pop_0_14",
              fill.scale = tm_scale_intervals(values = "pu_gn", n = 7)) +
  tm_facets_wrap(by = "province")+
  tm_credits("Test credits", fontface="bold", position = tm_pos_out(pos.h = "right", pos.v = "bottom"))
```

![image](https://github.com/user-attachments/assets/cc5ea3cf-bd49-4a58-b39a-523e94cbaacb)

The only difference is a slight horizontal shift of "Test credits" in locations. "bold.italic" does not work, nor numbers: bold = 2, italic = 3, bold.italic = 4.

**Comment by mtennekes** [comment]
Thx, fixed now
